<font size=10>**NETWORK**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

**Data**: 
- [*Portal BASE*](https://www.base.gov.pt/Base4/pt/pesquisa/?type=contratos&texto=&adjudicante=&adjudicataria=&tipo=2&tipocontrato=0&cpv=&aqinfo=&desdeprazoexecucao=&ateprazoexecucao=&sel_price=price_11&desdeprecocontrato=&ateprecocontrato=&desdeprecoefectivo=&ateprecoefectivo=&sel_date=date_11&desdedatacontrato=2023-01-01&atedatacontrato=2026-03-31&desdedatapublicacao=&atedatapublicacao=&desdedatafecho=&atedatafecho=&pais=0&distrito=0&concelho=0)

- [*Treated Datasets*](https://dados.gov.pt/pt/datasets/contratos-publicos-portal-base-impic-contratos-de-2012-a-2026/#/resources)

**Group B**
- Beatriz Marques 20231605
- Maria Inês Santos 20231630
- Luís Soeiro 20211536
- Rodrigo Silva 20231602

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a>  
- [1. Imports](#1)  
- [2. Data Integration](#2)  
- [3. First Network](#3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

In [3]:
import subprocess, sys, importlib
import pandas as pd
import plotly.express as px
import re
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

try:
    import openpyxl
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl"])
    importlib.invalidate_caches()
    import openpyxl
    
import os
import shutil

# <font color='#BFD72F' size=6>**2. Data Integration**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [4]:
data = pd.read_csv('../data/preprocessed_data.csv')
# data.head()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30485 entries, 0 to 30484
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   idcontrato                   30485 non-null  int64
 1   tipoContrato                 30485 non-null  str
 2   tipoFimContrato              4090 non-null   str
 3   CPV                          30485 non-null  str
 4   adjudicante                  30485 non-null  str
 5   adjudicatarios               30485 non-null  str
 6   concorrentes                 21158 non-null  str
 7   precoBaseProcedimento        30485 non-null  float64
 8   precoContratual              30485 non-null  float64
 9   PrecoTotalEfetivo            30485 non-null  float64
 10  dataDecisaoAdjudicacao       30485 non-null  str
 11  dataCelebracaoContrato       30485 non-null  str
 12  dataPublicacao               30485 non-null  str
 13  dataFechoContrato            4094 non-null   str
 14  nr_concorrentes              30485 non-null  int64
 15  contribuinte_adjudicante     30370 non-null  float64
 16  contribuinte_adjudicatarios  29731 non-null  float64
 17  city                         29574 non-null  str
dtypes: float64(5), int64(2), str(11)
memory usage: 4.2 MB

In [5]:
data["dataPublicacao"] = pd.to_datetime(data["dataPublicacao"], errors='coerce')
data["dataCelebracaoContrato"] = pd.to_datetime(data["dataCelebracaoContrato"], errors='coerce')
data["dataDecisaoAdjudicacao"] = pd.to_datetime(data["dataDecisaoAdjudicacao"], errors='coerce')
data["dataFechoContrato"] = pd.to_datetime(data["dataFechoContrato"], errors='coerce')

# <font color='#BFD72F' size=6>**3. The Network**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

## <font size=5>**3.1 Creating It**</font> <a class="anchor" id="3.1"></a>
  
[Back to TOC](#toc)

In [6]:
################
### BEA CODE ###
################

# # If your data is not a DataFrame, fix it
# if isinstance(data, dict):
#     data = pd.DataFrame(data)

# # Create directed graph
# G = nx.DiGraph()

# # Build graph
# for _, row in data.iterrows():
#     adjudicante = row['adjudicante']
#     adjudicatarios = row['adjudicatarios']
#     preco = row['precoContratual']
#     concorrentes = row.get('concorrentes', 0)

#     # Skip missing
#     if pd.isna(adjudicante) or pd.isna(adjudicatarios):
#         continue
#     if pd.isna(preco) or preco <= 0:
#         continue

#     log_price = np.log(preco)

#     # Handle concorrentes safely
#     if pd.isna(concorrentes):
#         concorrentes = 0

#     # Add/update nodes
#     if adjudicante not in G:
#         G.add_node(adjudicante, node_type='adjudicante')
#     else:
#         if G.nodes[adjudicante].get('node_type') == 'adjudicatario':
#             G.nodes[adjudicante]['node_type'] = 'both'

#     if adjudicatarios not in G:
#         G.add_node(adjudicatarios, node_type='adjudicatario')
#     else:
#         if G.nodes[adjudicatarios].get('node_type') == 'adjudicante':
#             G.nodes[adjudicatarios]['node_type'] = 'both'

#     # Add/update edge
#     if G.has_edge(adjudicante, adjudicatarios):
#         edge = G[adjudicante][adjudicatarios]
#         edge['weight'] += log_price
#         edge['contracts'] += 1
#         edge_conc = pd.to_numeric(edge.get('nr_concorrentes', 0), errors='coerce')
#         row_conc = pd.to_numeric(concorrentes, errors='coerce')
#         edge['nr_concorrentes'] = int(0 if pd.isna(edge_conc) else edge_conc) + int(0 if pd.isna(row_conc) else row_conc)
#     else:
#         G.add_edge(
#             adjudicante,
#             adjudicatarios,
#             weight=log_price,
#             contracts=1,
#             nr_concorrentes=concorrentes,
#             city=row.get('city', None)
#         )

In [7]:
def compute_weight(prices, mode="log_sum"):

    prices = np.array(prices)

    if mode == "sum_price":
        return prices.sum()

    elif mode == "avg_price":
        return prices.mean()

    elif mode == "log_sum":
        return np.log(prices).sum()

    elif mode == "log_mean":
        return np.log(prices).mean()

    else:
        raise ValueError(
            f"Unknown mode: {mode}. "
            f"Valid modes: sum_price, avg_price, log_sum, log_mean"
        )

In [8]:
def _ensure_dataframe(data):
    if isinstance(data, pd.DataFrame):
        return data.copy()

    if isinstance(data, dict):
        # CASE 1: dict of lists (valid dataframe)
        try:
            df = pd.DataFrame(data)
            return df
        except Exception:
            pass

        # CASE 2: dict of scalars → wrap into list
        return pd.DataFrame([data])

    raise TypeError(f"Unsupported input type: {type(data)}")

In [9]:
def build_contract_network(data, weight_mode="log_sum") -> nx.DiGraph:
    
    df = _ensure_dataframe(data)

    # --- CLEAN COLUMNS ---
    df = df.rename(columns={
        'precoContratual': 'price',
        'adjudicante': 'source',
        'adjudicatarios': 'target'
    })

    # --- BASIC CLEANING ---
    df = df.dropna(subset=['source', 'target', 'price'])
    df = df[df['price'] > 0]

    # --- CONCORRENTES ---
    if 'nr_concorrentes' in df.columns:
        df['concorrentes'] = df['nr_concorrentes']
    else:
        df['concorrentes'] = pd.to_numeric(df.get('concorrentes', 0), errors='coerce').fillna(0)

    # --- EDGE AGGREGATION ---
    edge_df = (
        df.groupby(['source', 'target'], as_index=False)
        .agg(
            total_price=('price', 'sum'),
            nr_concorrentes=('concorrentes', 'sum'),
            contracts=('price', 'count'),
            price_series=('price', list)
        )
    )

    # --- WEIGHT STRATEGY ---
    edge_df['weight'] = edge_df['price_series'].apply(
        lambda x: compute_weight(x, mode=weight_mode)
    )

    edge_df = edge_df.drop(columns=['price_series'])

    # --- BUILD GRAPH ---
    G = nx.DiGraph()

    for row in edge_df.itertuples(index=False):
        G.add_edge(
            row.source,
            row.target,
            weight=row.weight,
            total_price=row.total_price,
            nr_concorrentes=row.nr_concorrentes,
            contracts=row.contracts,
            weight_mode=weight_mode
        )

    # --- NODE TYPES ---
    sources = set(edge_df['source'])
    targets = set(edge_df['target'])

    for node in G.nodes():
        if node in sources and node in targets:
            G.nodes[node]['node_type'] = 'both'
        elif node in sources:
            G.nodes[node]['node_type'] = 'adjudicante'
        else:
            G.nodes[node]['node_type'] = 'adjudicatario'

    return G

# -------------------------------
# VISUAL ATTRIBUTES (UNIFIED)
# -------------------------------
def add_visual_attributes(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):
    conc = np.array([d['nr_concorrentes'] for _, _, d in G.edges(data=True)])
    weight = np.array([d['weight'] for _, _, d in G.edges(data=True)])

    def normalize(x):
        if len(x) == 0:
            return x

        range_ = np.ptp(x)  # max - min safely

        if range_ == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (range_ + 1e-9)

    # --- TRANSFORM ---
    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    # --- ASSIGN ---
    for i, (u, v, d) in enumerate(G.edges(data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G


# -------------------------------
# RUN PIPELINE
# -------------------------------
G = build_contract_network(data, weight_mode="log_sum")

# Linear scaling
G_linear = add_visual_attributes(
    G.copy(),
    thickness_mode="linear",
    size_mode="linear",
    suffix="_linear"
)

# Log scaling
G_log = add_visual_attributes(
    G.copy(),
    thickness_mode="log",
    size_mode="log",
    suffix="_log"
)

In [10]:
weight_modes = ["sum_price", "avg_price", "log_sum", "log_mean"]

graphs = {
    mode: build_contract_network(data, weight_mode=mode)
    for mode in weight_modes
}

In [11]:
for mode, G in graphs.items():
    volume = {
        node: sum(d["total_price"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    degree = dict(G.degree())

    corr = pd.Series(degree).corr(pd.Series(volume))

    print(f"{mode:10s} → degree-volume correlation: {corr:.3f}")

sum_price  → degree-volume correlation: 0.637
avg_price  → degree-volume correlation: 0.637
log_sum    → degree-volume correlation: 0.637
log_mean   → degree-volume correlation: 0.637

In [12]:
for mode, G in graphs.items():
    top = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:3]

    print(f"\nMode: {mode}")
    for node, deg in top:
        print(f"  {node}: {deg}")

Mode: sum_price
  Unidade Local de Saúde de São José, E. P. E.: 789
  Santa Casa da Misericórdia de Lisboa: 742
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: 730

Mode: avg_price
  Unidade Local de Saúde de São José, E. P. E.: 789
  Santa Casa da Misericórdia de Lisboa: 742
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: 730

Mode: log_sum
  Unidade Local de Saúde de São José, E. P. E.: 789
  Santa Casa da Misericórdia de Lisboa: 742
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: 730

Mode: log_mean
  Unidade Local de Saúde de São José, E. P. E.: 789
  Santa Casa da Misericórdia de Lisboa: 742
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: 730

In [13]:
rankings = {}

for mode, G in graphs.items():

    weighted_degree = {
        node: sum(d["weight"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    # convert to ranking (higher = better rank)
    ranked = pd.Series(weighted_degree).rank(ascending=False)

    rankings[mode] = ranked

sum_price → total contract value emphasis

avg_price → typical contract size

log_sum → interaction-frequency + heavy-tail compression

log_mean → normalized interaction intensity

In [14]:
rank_df = pd.DataFrame(rankings)
rank_df.head()

,sum_price,avg_price,log_sum,log_mean
"- - Inspeção-Geral do Ministério do Trabalho, Solidariedade e Segurança Social (IGMTSSS)",1016.0,1016.0,1019.0,1019.0
eden spring portugal,5594.5,5594.5,5594.5,5594.5
"- - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A.",809.0,825.0,374.0,417.0
- - B2MOBILITY GmbH,5594.5,5594.5,5594.5,5594.5
"Aon Portugal, S.A.",5594.5,5594.5,5594.5,5594.5

In [15]:
rank_df["rank_std"] = rank_df.std(axis=1)
rank_df["rank_mean"] = rank_df.mean(axis=1)

In [16]:
# Structurally important regardless of weight strategy

stable_nodes = rank_df.sort_values("rank_std").head(10)
stable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
"MArketingable, Lda",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
MEO,5594.5,5594.5,5594.5,5594.5,0.0,4475.6
Enzymatic S.A.,5594.5,5594.5,5594.5,5594.5,0.0,4475.6
SERVISAN PRODUTOS HIGIENE SA,5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"GRIFOLS PORTUGAL, LDA.",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"Servisan - Produtos de Higiene, S.A.",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"Grupnor Elevadores de Portugal, Lda.",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"BELTRAO COELHO, LDA.",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"ISOTOPOS E DERIVADOS (ISODER), LDA.",5594.5,5594.5,5594.5,5594.5,0.0,4475.6
"LABORATÓRIOS MEDINFAR, S. A",5594.5,5594.5,5594.5,5594.5,0.0,4475.6

<font color ='red'>These nodes:
- have identical ranks across ALL weighting schemes
- are structurally invariant in your network

They are topological anchors, not sensitive to how we measure money or interaction.

We see identical rank values like 5594.5, this suggests many tied ranks. So they are stable and saturated centrality nodes. This means that ranking resolution is too coarse and many nodes are indistinguishable under this metric.

In [17]:
# Importende depends heavily on how we measure importance

unstable_nodes = rank_df.sort_values("rank_std", ascending=False).head(10)
unstable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
"Vimeca Transportes - Viação Mecânica de Carnaxide, L.da",124.0,113.0,709.0,701.0,338.661458,397.132292
"Teatro Nacional D. Maria II, E. P. E.",127.0,116.0,711.0,703.0,338.084186,399.016837
CÂMARA MUNICIPAL DE SINTRA,131.0,121.0,712.0,704.0,336.058527,400.811705
Associação de Socorros da Freguesia da Encarnação,135.0,126.0,713.0,705.0,334.033307,402.606661
"AdP Energias - Energias Renováveis e Serviços Ambientais , S. A.",882.0,899.0,310.0,322.0,331.796499,548.959300
"Conselho Diretivo do Turismo de Portugal, IP",144.0,132.0,714.0,706.0,330.296836,405.259367
"Comissão Unitária de Reformados, Pensionistas e Idosos de São João da Talha",188.0,176.0,716.0,708.0,306.052283,418.810457
Associação para tratamento das toxicodependências,196.0,184.0,717.0,709.0,302.011589,421.602318
"- - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A.",927.0,933.0,405.0,451.0,290.447930,601.289586
Centro Social Paroquial de Barcarena,219.0,206.0,718.0,710.0,289.608212,428.521642

<font color='red'>These nodes change position dramatically depending on weighting scheme. Their importance depends on what we consider "importance". 

Pattern:
1. Mixed contract sizes
some large contracts
many small ones
2. irregular interaction structure
sporadic procurement behavior
3. heterogeneity in edges

sum_price -> rewards big contracts
avg_price -> smooths variability
log_sum -> rewards frequency
log_mean -> penalizes extreme dispersion

In [18]:
# # Visualize the graph
# # Layout (can take time for big graphs)
# pos = nx.spring_layout(G, k=0.15, iterations=20, seed=42)

# # Extract edge attributes
# weights = [G[u][v]['weight'] for u, v in G.edges()]
# widths = [G[u][v]['nr_concorrentes'] for u, v in G.edges()]

# # Avoid division by zero
# if len(widths) > 0 and max(widths) > 0:
#     widths = [w / max(widths) * 5 for w in widths]
# else:
#     widths = [1 for _ in widths]

# if len(weights) > 0 and max(weights) > 0:
#     weights_norm = [w / max(weights) for w in weights]
# else:
#     weights_norm = weights

# # Draw
# plt.figure(figsize=(12, 10))

# nx.draw_networkx_nodes(G, pos, node_size=50)

# nx.draw_networkx_edges(
#     G,
#     pos,
#     width=widths,                 # thickness = concorrentes
#     edge_color=weights_norm,      # color = log(price)
#     edge_cmap=plt.cm.Blues
# )

# plt.title("Network: Adjudicante → Adjudicatário")
# plt.axis('off')
# plt.show()

## <font size=5>**3.2 General Insights**</font> <a class="anchor" id="3.2"></a>
  
[Back to TOC](#toc)

In [19]:
# Number of nodes
print(f"Number of nodes: {G.number_of_nodes()}")
print(f"\t-> Number of adjudicantes: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both']) / G.number_of_nodes() * 100:.2f}%")
print(f"\t-> Number of adjudicatarios: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both']) / G.number_of_nodes() * 100:.2f}%")

# Number of edges
print(f"\nNumber of edges: {G.number_of_edges()}")

Number of nodes: 10163
	-> Number of adjudicantes: 1025, i.e., 10.09%
	-> Number of adjudicatarios: 9156, i.e., 90.09%

Number of edges: 19077

## <font size=5>**3.3 Rank All Entities By Degree (Number of Contracts)**</font> <a class="anchor" id="3.3"></a>
  
[Back to TOC](#toc)

In [20]:
def entity_type(node):
    node_type = G.nodes[node].get("node_type", "unknown")
    if node_type == "both":
        return "adjudicante and adjudicatario"
    return node_type

# Highest and lowest in-degree
highest_in = max(G.in_degree(), key=lambda x: x[1])
lowest_in = min(G.in_degree(), key=lambda x: x[1])

# Highest and lowest out-degree
highest_out = max(G.out_degree(), key=lambda x: x[1])
lowest_out = min(G.out_degree(), key=lambda x: x[1])

# Average in-degree and out-degree
in_degrees = [d for _, d in G.in_degree()]
out_degrees = [d for _, d in G.out_degree()]

avg_in = sum(in_degrees) / len(in_degrees)
avg_out = sum(out_degrees) / len(out_degrees)

print(f"Highest in-degree: {highest_in} -> {entity_type(highest_in[0])}")
print(f"Lowest out-degree: {lowest_out} -> {entity_type(lowest_out[0])}")

print(f"\nHighest out-degree: {highest_out} -> {entity_type(highest_out[0])}")
print(f"Lowest in-degree: {lowest_in} -> {entity_type(lowest_in[0])}")

print(f"\nAverage in-degree: {avg_in:.2f}")
print(f"Average out-degree: {avg_out:.2f}")

Highest in-degree: ('CLARANET II SOLUTIONS, S.A.', 63) -> adjudicatario
Lowest out-degree: ('eden spring portugal', 0) -> adjudicatario

Highest out-degree: ('Unidade Local de Saúde de São José, E. P. E.', 789) -> adjudicante
Lowest in-degree: ('- -   Inspeção-Geral do Ministério do Trabalho, Solidariedade e Segurança Social (IGMTSSS)', 0) -> adjudicante

Average in-degree: 1.88
Average out-degree: 1.88

The average in-degree and average out-degree are the same because, in any directed graph, the sum of all in-degrees equals the sum of all out-degrees, and both are equal to the number of edges.

Therefore:
  $$avg_{in}  = |E| / |V|$$
  $$avg_{out} = |E| / |V|$$

so they must be identical.

In [21]:
# Top 5 Degree Enitities
top5 = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:5]
print("Top 5 most connected entities:")
for entity, deg in top5:
    print(f"  {entity}: {deg}")

Top 5 most connected entities:
  Unidade Local de Saúde de São José, E. P. E.: 789
  Santa Casa da Misericórdia de Lisboa: 742
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: 730
  Unidade Local de Saúde de Santa Maria, E. P. E.: 596
  Município de Sintra: 566

In [22]:
# Degree-1 entities
deg1 = sorted(
    [(node, degree) for node, degree in G.degree() if degree == 1],
    key=lambda x: x[0]
)

print(f"Degree-1 entities: {len(deg1)}")
for i, (entity, degree) in enumerate(deg1[:20], start=1):
    node_type = G.nodes[entity].get("node_type", "unknown")
    if node_type == "both":
        node_type = "adjudicante and adjudicatario"
    print(f"{i:>3}. {entity} (degree={degree}, type={node_type})")

if len(deg1) > 20:
    print(f"... and {len(deg1) - 20} more")

Degree-1 entities: 6073
  1. - (degree=1, type=adjudicatario)
  2. - -   Inspeção-Geral do Ministério do Trabalho, Solidariedade e Segurança Social (IGMTSSS) (degree=1, type=adjudicante)
  3. - -  Lemaitre Vascular Spain SL (degree=1, type=adjudicatario)
  4. - - 3M ESPANHA SUCURSAL PORTUGAL (degree=1, type=adjudicatario)
  5. - - 3M España, S.A. (degree=1, type=adjudicatario)
  6. - - 3M España, S.L., Sucursal em Portugal (degree=1, type=adjudicatario)
  7. - - 826133058B01 (degree=1, type=adjudicatario)
  8. - - 85765766 (degree=1, type=adjudicatario)
  9. - - A. Milne Carmo SA. (degree=1, type=adjudicatario)
 10. - - AINIA (degree=1, type=adjudicatario)
 11. - - ALBAZUL SERVICIOS INTEGRALES, S.A. (degree=1, type=adjudicatario)
 12. - - ALBAZUL SERVICOS INTEGRALES SA (degree=1, type=adjudicatario)
 13. - - ALSEAMAR (degree=1, type=adjudicatario)
 14. - - ALTEL SISTEMAS S.L. (degree=1, type=adjudicatario)
 15. - - ALTEL SISTEMAS, SL (degree=1, type=adjudicatario)
 16. - - ANDERSEN TAX &amp; LEGAL IBERIA SLP - SUCURSAL EM PORTUGAL (degree=1, type=adjudicatario)
 17. - - ARGUs Media Limited (degree=1, type=adjudicatario)
 18. - - ATOS MEDICAL SPAIN S.L.SUCURSAL EM PORTUGAL. (degree=1, type=adjudicatario)
 19. - - ATOS MEDICAL SPAIN, SL (degree=1, type=adjudicatario)
 20. - - Ace Aeronautics LLC (ACE) (degree=1, type=adjudicatario)
... and 6053 more

In [23]:
# All contract pairs with amounts
print("Contracts with their amounts:")
for u, v, data in G.edges(data=True):
    print(f"  {u} -- {v} : €{data['weight']:,}")

Contracts with their amounts:
  - -   Inspeção-Geral do Ministério do Trabalho, Solidariedade e Segurança Social (IGMTSSS) -- eden spring portugal : €6.393590753950631
  - - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- - - B2MOBILITY GmbH : €9.972893272122906
  - - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Aon Portugal, S.A. : €10.134360356072131
  - - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- INETUM ESPAÑA, S.A. - Sucursal em Portugal : €9.936154141959744
  - - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- MDS – Corretor de Seguros, S.A : €8.968244318109551
  - - ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Previmed – Centro de Medicina Ocupacional, Lda. : €7.568329226592811
  - - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A. -- - - B2MOBILITY GmbH : €9.20515796648039
  - - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A. -- Aon Portugal, S.A. : €8.525562074419886
  - - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A. -- INETUM ESPAÑA, S.A. - Sucursal em Portugal : €7.967793045670471
  - - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A. -- MDS – Corretor de Seguros, S.A : €8.06414371457294
  - - AdP Energias - Energias Renováveis e Serviços Ambientais, S.A. -- Previmed – Centro de Medicina Ocupacional, Lda. : €6.269046242462549
  - - AdP Valor - Serviços Ambientais, S. A. -- - - B2MOBILITY GmbH : €10.264406726972833
  - - AdP Valor - Serviços Ambientais, S. A. -- Aon Portugal, S.A. : €10.69083202113875
  - - AdP Valor - Serviços Ambientais, S. A. -- INETUM ESPAÑA, S.A. - Sucursal em Portugal : €9.692781335925552
  - - AdP Valor - Serviços Ambientais, S. A. -- MDS – Corretor de Seguros, S.A : €9.440054536669813
  - - AdP Valor - Serviços Ambientais, S. A. -- Previmed – Centro de Medicina Ocupacional, Lda. : €7.809491283409699
  - - Administração Central do Sistema de Saúde, I. P. -- CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA : €6.067869878310387
  - - Administração Regional de Saúde de Lisboa e Vale do Tejo, I. P. -- Crayon Software Licensing, Unipessoal, Lda. : €9.040786164609173
  - - Autoridade Tributária e Aduaneira -- Claranet II Solutions, S. A. : €14.016297246698946
  - - Autoridade de Gestão do Programa Mar 2030 -- MEO : €9.661069434477222
  - - Direção-Geral de Alimentação e Veterinária -- SERVISAN PRODUTOS HIGIENE SA : €8.729541078683832
  - - Direção-Geral de Recursos Naturais, Segurança e Serviços Marítimos -- Servisan - Produtos de Higiene, S.A. : €8.785345289398679
  - - Direção-Geral do Tesouro e Finanças -- BELTRAO COELHO, LDA. : €9.103423089630105
  - - Direção-Geral do Tesouro e Finanças -- Servisan - Produtos de Higiene, S.A. : €7.7963129808777545
  - - EPAL - Empresa Portuguesa das Águas Livres, S. A. -- - - B2MOBILITY GmbH : €13.360662729159731
  - - EPAL - Empresa Portuguesa das Águas Livres, S. A. -- INETUM ESPAÑA, S.A. - Sucursal em Portugal : €13.750505378625366
  - - EPAL - Empresa Portuguesa das Águas Livres, S. A. -- MDS – Corretor de Seguros, S.A : €12.16601788676504
  - - Faculdade Ciências Universidade Lisboa -- MEO : €10.864436495234427
  - - Faculdade Ciências Universidade Lisboa -- PERENE, S.A. : €11.03835847943418
  - - Faculdade Medicina Universidade de Lisboa -- MEO : €10.936135237026782
  - - Faculdade Medicina Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.772002065618526
  - - Faculdade de Arquitetura da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.44299376110114
  - - Faculdade de Arquitetura da Universidade de Lisboa -- meo,sa : €8.69107926938909
  - - Faculdade de Belas Artes -- 1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A. : €8.806681631403386
  - - Faculdade de Belas Artes -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €8.58849379803293
  - - Faculdade de Direito da Universidade de Lisboa -- MEO - Serviços de Comunicações e Multimédia, S.A. : €8.92790849310653
  - - Faculdade de Direito da Universidade de Lisboa -- Relva Viva - Gestão Florestal e Jardins Unip. Lda. : €10.629899281928516
  - - Faculdade de Direito da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €8.396299322130425
  - - Faculdade de Farmácia da Universidade de Lisboa -- 1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A. : €9.766402424295164
  - - Faculdade de Farmácia da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €8.762264169863302
  - - Faculdade de Letras da Universidade de Lisboa -- 1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A. : €9.83259287375958
  - - Faculdade de Letras da Universidade de Lisboa -- Relva Viva - Gestão Florestal e Jardins Unip. Lda. : €10.45607786234906
  - - Faculdade de Letras da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.301992961855301
  - - Faculdade de Medicina Dentária da Universidade de Lisboa -- MEO- Serviços de Comunicações e Multimédia, S.A, : €8.657445448350174
  - - Faculdade de Medicina Dentária da Universidade de Lisboa -- Purgest, Serviços Ambientais : €9.524718171395707
  - - Faculdade de Medicina Dentária da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €7.842812807747695
  - - Faculdade de Medicina Veterinária da Universidade de Lisboa -- Meo - Serviços de Comunicações e Multimédia, SA : €9.57074116630596
  - - Faculdade de Medicina Veterinária da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €10.039147178863852
  - - Faculdade de Motricidade Humana -- Relva Viva - Gestão Florestal e Jardins Unip. Lda. : €10.663448632346347
  - - Faculdade de Motricidade Humana -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €8.976934341095465
  - - Faculdade de Motricidade Humana -- meo,sa : €9.273810822929812
  - - Faculdade de Psicologia da Universidade de Lisboa -- Relva Viva - Gestão Florestal e Jardins Unip. Lda. : €9.978296279104114
  - - Faculdade de Psicologia da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €8.024914504936826
  - - Faculdade de Psicologia da Universidade de Lisboa -- meo : €7.84120986553469
  - - Fundação para a Ciência e a Tecnologia I.P. -- LEASYS MOBILITY PORTUGAL, SA : €11.541629533098584
  - - Gabinete da Ministra da Agricultura  (SNCP) -- MEO - Serviços de Comunicações e Multimédia SA : €9.958530034926744
  - - Gabinete da Secretária de Estado das Pescas -- Meo - Serviços de Comunicações e Multimédia, SA : €9.623795474892178
  - - Gabinete de Planeamento, Estrategia, Avaliação e Relações Internacionais -- Servisan - Produtos de Higiene, S.a. : €4.221857882521061
  - - Gabinete do Secretário de Estado da Agricultura e do Desenvolvimento Rural -- MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA SA : €9.351867711641864
  - - Guarda Nacional Republicana -- Servisan - Produtos de Higiene, S.A. : €11.325322063762384
  - - INESC - Microsistemas e Nanotecnologias - Instituto de Engenharia de Sistemas e Computadores para os Microsistemas e as Nanotecnologias
- - INOV - Instituto de Engenharia de Sistemas e Computadores InovaçãoINESC - Instituto de Engenharia de Sistemas e Computadores
- - INESC ID - Instituto de Engenharia de Sistemas e Computadores, Investigação e Desenvolvimento em Lisboa -- Willis - Corretores de Seguros, S.A. : €12.541927798937555
  - - INFARMED - Autoridade Nacional do Medicamento e Produtos de Saúde, I. P. -- NOESIS Portugal – Consultadoria em Sistemas Informáticos SA : €12.224683386341182
  - - Instituto Nacional da Propriedade Industrial, I. P. -- Servisan - Produtos de Higiene, S.A. : €8.333102069865685
  - - Instituto Nacional de Investigação Agrária e Veterinária, I. P. -- MEO - Serviços de Comunicações e Multimédia, SA : €7.422971251049421
  - - Instituto Nacional de Saúde Doutor Ricardo Jorge, IP -- CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA. : €11.982644366184784
  - - Instituto Nacional para a Reabilitação (INR) -- eden spring portugal : €6.478048706500939
  - - Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E. -- Crayon Software Licensing, Unipessoal, Lda. : €11.910322043193295
  - - Instituto Português do Mar e da Atmosfera, I. P. -- meo,sa : €11.135260331719744
  - - Instituto Superior Técnico -- MEO - Serviços de Comunicações e Multimédia, S.A. : €11.664457862944303
  - - Instituto Superior de Agronomia -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.972315610442067
  - - Instituto Superior de Agronomia -- meo : €9.799991963487814
  - - Instituto Superior de Ciências Sociais e Políticas -- MEO - Serviços de Comunicações e Multimédia, S.A. : €10.048429101039682
  - - Instituto Superior de Ciências Sociais e Políticas -- Purgest, Serviços Ambientais : €9.961305415558327
  - - Instituto Superior de Ciências Sociais e Políticas -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.388051316212454
  - - Instituto Superior de Economia e Gestão -- MEO : €9.980637464723886
  - - Instituto Superior de Economia e Gestão -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €9.811306471990417
  - - Instituto de Ciências Sociais -- MEO : €8.569041531737291
  - - Instituto de Educação da Universidade de Lisboa -- MEO - Serviços de Comunicações e Multimédia, S.A. : €7.579760535788655
  - - Instituto de Financiamento da Agricultura e Pescas - IFAP, I. P. -- MEO - Serviços de Comunicações e Multimédia, S.A. : €11.407564949312402
  - - Instituto de Financiamento da Agricultura e Pescas - IFAP, I. P. -- SERVISAN PRODUTOS HIGIENE SA : €8.594154232552366
  - - Instituto de Geografia e Ordenamento do Território -- 1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A. : €7.838564111369202
  - - Instituto de Geografia e Ordenamento do Território -- PERENE, S.A. : €10.140320968576345
  - - Instituto de Geografia e Ordenamento do Território -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €7.887493937511834
  - - Instituto de Gestão Financeira e Equipamentos da Justiça, I. P. -- Servisan - Produtos de Higiene, S.A. : €6.525410816864686
  - - Instituto de Gestão da Tesouraria e Créd. Público -- Servisan - Produtos de Higiene, S.A. : €7.502683052035622
  - - Instituto de Proteção e Assistência na Doença, I. P. -- Exitus, Soluções Tecnológicas, Lda : €7.865955413933502
  - - Instituto de Proteção e Assistência na Doença, I. P. -- Vodafone Portugal, Comunicações Pessoais, S.A. : €12.822729849985436
  - - Instituto para os Comportamentos Aditivos e as Dependências, I.P. -- Crayon Software Licensing, Unipessoal, Lda. : €11.37562010272975
  - - Procuradoria-Geral da República -- Servisan - Produtos de Higiene, S.A. : €9.11382947159534
  - - Serviços de Ação Social da Universidade de Lisboa -- MEO - Serviços de Comunicações e Multimédia, S.A. : €9.615549447310753
  - - Serviços de Ação Social da Universidade de Lisboa -- Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda. : €10.14511521522749
  - - Supremo Tribunal Administrativo -- Servisan-Produtos de Higiene, S.A. : €6.934883946370389
  - - Supremo Tribunal de Justiça -- Servisan - Produtos de Higiene, S.A. : €7.855273323272865
  - - Tribunal Central Administrativo Sul -- Servisan - Produtos de Higiene, S.A. : €6.780558068715136
  - - Unidade Local de Saúde de Lisboa Ocidental, E. P. E. -- IPATIMUP - Instituto de Patologia e Imunologia Molecular da Universidade do Porto : €7.0326242610280065
  - - Unidade Local de Saúde de Loures-Odivelas, E. P. E. -- CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA : €13.168540549729716
  - - Unidade Local de Saúde de Loures-Odivelas, E. P. E. -- IPATIMUP - Instituto de Patologia e Imunologia Molecular da Universidade do Porto : €6.159095388491933
  - - Unidade Local de Saúde de Santa Maria, E. P. E. -- Crayon Software Licensing, Unipessoal, Lda. : €10.398610532574828
  - - Unidade Local de Saúde de Santa Maria, E. P. E. -- I.P.M. - Informática, Papelaria Mobiliário, Lda. : €7.647619046764605
  - - Unidade Local de Saúde de Santa Maria, E. P. E. -- IPATIMUP-INST.P.CL.MOL.U.PORTO : €7.167809184316444
  - - Unidade Local de Saúde de Santa Maria, E. P. E. -- IRPI - COMERCIO INFORMATICO, LDA : €13.041337708449271
  - - Unidade Local de Saúde de Santa Maria, E. P. E. -- Max One  Material de Escritório, Lda : €5.5020742040620565
  - - Unidade Local de Saúde de São José, E. P. E. -- Crayon Software Licensing, Unipessoal, Lda. : €13.209586545298015
  - - Unidade Local de Saúde de São José, E. P. E. -- IPATIMUP-INST.P.CL.MOL.U.PORTO : €6.873577827180551
  - - Águas do Tejo Atlântico, S. A. -- Aon Portugal, S.A. : €13.265062393656523
  - - Águas do Tejo Atlântico, S. A. -- B2Mobility GmbH : €12.706069539663723
  - - Águas do Tejo Atlântico, S. A. -- Inetum España, S.A. Sucursal em Portugal(Informática - El Corte Inglés) : €12.303822211248265
  - - Águas do Tejo Atlântico, S. A. -- MDS – Corretor de Seguros, S.A : €11.089863903713223
  A. D. A. M. - Águas do Alto Minho, S. A. -- Aon Portugal, S.A. : €11.256450588956325
  A. D. A. M. - Águas do Alto Minho, S. A. -- BASE2, LDA : €7.824046010856292
  A. D. A. M. - Águas do Alto Minho, S. A. -- Bravantic Evolving Technology, S.A : €10.40138597897538
  A. D. A. M. - Águas do Alto Minho, S. A. -- EVIO - Electrical Mobility, Lda : €7.824046010856292
  A. D. A. M. - Águas do Alto Minho, S. A. -- Iberdrola Clientes Portugal, Unipessoal, Lda : €10.492308682195032
  A. D. A. M. - Águas do Alto Minho, S. A. -- Luzboa - Comercializaçao de Energia, Lda : €8.23152242825849
  A. D. A. M. - Águas do Alto Minho, S. A. -- MDS - Corretor de Seguros, S.A. : €9.597327814638419
  A. D. A. M. - Águas do Alto Minho, S. A. -- Quinta de Jugais - Produtos Alimentares, Lda : €9.795002159530776
  A. D. A. M. - Águas do Alto Minho, S. A. -- Quinta do Jugais - Comércio de Produtos Alimentares Lda : €9.772923182515012
  A. D. A. M. - Águas do Alto Minho, S. A. -- SAPEC QUÍMICA S.A : €10.112126417647456
  A. D. A. M. - Águas do Alto Minho, S. A. -- VWR International - Material de Laboratório, Soc. Unipessoal, Lda. : €8.191144441019265
  ABA - Associação Beneficente de Ajuda -- VOMERA BUILDING SOLUTIONS, UNIPESSOAL LDA : €14.594043837130851
  ACSS-Administração Central do Sistema de Saúde,IP -- CLARANET II SOLUTIONS, S.A. : €8.433811582477187
  ACSS-Administração Central do Sistema de Saúde,IP -- Ohmtécnica - Representações de Marcas, Lda : €8.138672792171155
  ACSS-Administração Central do Sistema de Saúde,IP -- Primavera – Business Software Solutions S.A : €8.990615968707628
  ACSS-Administração Central do Sistema de Saúde,IP -- Timestamp - Sistemas de Informação, S.A. : €11.34954392823967
  ADENE - Agência para a Energia -- CENTERM – Centro Tecnológico para a Indústria Térmica, Energia e Ambiente : €11.130668941998945
  ADENE - Agência para a Energia -- DIGIBÉRIA INFORMATION TECHNOLOGIES, S.A. : €11.097410021008562
  ADENE - Agência para a Energia -- Digibéria Information Technologies S.A. : €11.923709734555993
  ADENE - Agência para a Energia -- Páginas aos Blocos, Lda. : €8.160932447399158
  ADIST- Associação para o Desenvolvimento do IST -- Jerónimo Martins – Restauração e Serviços S.A. : €12.794025963211613
  ADIST- Associação para o Desenvolvimento do IST -- Warpcom Services, S.A : €12.106243249433433
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- - - B2 MOBILITY, GMBH : €9.572148916410562
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Aon Portugal, S.A. : €9.22034582474719
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Companhia dos Cabazes, Unipessoal, Lda. : €7.357065008866719
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- EVIO - Electrical Mobility, Lda : €6.725429722180182
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- MDS - Corretor de Seguros, S.A. : €8.398709102126979
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- MDS – Corretor de Seguros, S.A : €6.7798423588537995
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- NOS - Comunicações S.A. : €10.341352084690952
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Quinta de Jugais - Comércio de Produtos Alimentares, Lda. : €7.113663145582233
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- Quinta de Jugais - Produtos Alimentares, Lda : €7.0418315231480975
  ADP - Águas de Portugal Internacional - Serviços Ambientais, S. A. -- VALPI RENT, S.A. : €11.082142548877775
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- AVVALE, UNIPESSOAL LDA : €11.577776437289845
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- BASEDOIS - Informática e Telecomunicações, Lda : €9.655026193237628
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- Companhia dos Cabazes, Unipessoal, Lda. : €7.5706391091647784
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- JOSÉ GONÇALVES E ALCINA, LDA : €11.327393624274812
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- LATITUDDE DIGITAL ENABLERS : €11.931635799828413
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- NATUREZA VERDE - GESTÃO DE RESÍDUOS, LDA. : €9.711115659888671
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- NOS - Comunicações S.A. : €10.510104967385837
  ADP VALOR - SERVIÇOS AMBIENTAIS, S.A. -- PETROGAL, S.A. : €8.880974822923884
  AMA - Agência para a Modernização Administrativa -- Construções David Carmo, Lda : €12.324376656566425
  ANI - Agência Nacional de Inovação, S. A. -- Euromex - Facility Services, Lda : €11.355517686551593
  ANI - Agência Nacional de Inovação, S. A. -- Idoneos, Lda. : €11.982241357779467
  ANI - Agência Nacional de Inovação, S. A. -- Idóneos, Lda : €13.016513853312476
  ANI - Agência Nacional de Inovação, S. A. -- Linkcom - Sistemas de Informacao, SA : €11.942849011910766
  ANI - Agência Nacional de Inovação, S. A. -- Solidnetworks - Business Consulting, Lda. : €11.945875381420489
  ANI - Agência Nacional de Inovação, S. A. -- TBFILES Portugal, Lda. : €12.947743288031006
  APL - Administração do Porto de Lisboa, S. A. -- - - DRAVO, S.A. : €15.871760235367434
  APL - Administração do Porto de Lisboa, S. A. -- ALMOVI - MAQUINAS E EQUIPAMENTOS, LDA. : €13.080420796928756
  APL - Administração do Porto de Lisboa, S. A. -- Ahlers Lindley : €12.488597693359464
  APL - Administração do Porto de Lisboa, S. A. -- CECÍLIO &amp; CARLOS SANFINS, LDA : €11.128413145778596
  APL - Administração do Porto de Lisboa, S. A. -- CLARANET II SOLUTIONS, S.A. : €11.565182059829514
  APL - Administração do Porto de Lisboa, S. A. -- Canon Portugal, S.A. : €11.483060101743666
  APL - Administração do Porto de Lisboa, S. A. -- Claranet II Solutions, S.A. : €10.531455447149492
  APL - Administração do Porto de Lisboa, S. A. -- Claranet II Solutions, SA : €10.372209110279307
  APL - Administração do Porto de Lisboa, S. A. -- Douro Gás Natural - Comércio de Gás Natural e Energia, SA : €10.105944197694825
  APL - Administração do Porto de Lisboa, S. A. -- EIPEOPLE Empresa de Trabalho Temporário Lda : €12.516827250658586
  APL - Administração do Porto de Lisboa, S. A. -- ENDESA ENERGIA SA - SUCURSAL PORTUGAL : €13.329701705625615
  APL - Administração do Porto de Lisboa, S. A. -- EVENTO - Engenharia e Construção Civil, Lda. : €11.73049752430751
  APL - Administração do Porto de Lisboa, S. A. -- Endesa Energia, S.A. – Sucursal Portugal : €13.667246255094565
  APL - Administração do Porto de Lisboa, S. A. -- Fidelidade – Companhia de Seguros, S.A. : €11.90422558836956
  APL - Administração do Porto de Lisboa, S. A. -- Gas Natural Comercializadora, S.A. - Sucursal em Portugal : €9.703392580202497
  APL - Administração do Porto de Lisboa, S. A. -- Gold Energy - Comercializadora de Energia, S.A. : €11.618530110825853

## <font size=5>**3.4 Total Contracts Volume (Price) per Entity**</font> <a class="anchor" id="3.4"></a>
  
[Back to TOC](#toc)

In [24]:
volume = {node: 0 for node in G.nodes()}

# Step 2
for u, v, data in G.edges(data=True):
    volume[u] += data["weight"]
    volume[v] += data["weight"]

# Step 3
sorted_volume = sorted(volume.items(), key=lambda x: x[1], reverse=True)
print("Entity volume ranking:")
for entity, vol in sorted_volume:
    print(f"  {entity}: €{vol:,.0f}")

Entity volume ranking:
  Unidade Local de Saúde de São José, E. P. E.: €7,198
  Santa Casa da Misericórdia de Lisboa: €6,735
  Município de Sintra: €6,262
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.: €6,145
  Unidade Local de Saúde de Santa Maria, E. P. E.: €5,589
  Município de Oeiras: €5,050
  Centro Hospitalar Universitário Lisboa Central, E. P. E.: €4,079
  Centro Hospitalar Universitário de Lisboa Central, E.P.E. (CHULC): €3,331
  Município de Cascais: €3,133
  Unidade Local de Saúde de Lisboa Ocidental, E. P. E.: €2,781
  Unidade Local de Saúde de São José, EPE: €2,719
  Unidade Local de Saúde de Loures-Odivelas, E. P. E.: €2,716
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A.: €2,698
  Guarda Nacional Republicana: €2,295
  Centro Hospitalar Universitário de Lisboa Norte, E. P. E.: €2,280
  Município de Lisboa: €2,251
  Unidade Local de Saúde de Loures-Odivelas, EPE: €2,247
  Instituto Português de Oncologia de Lisboa FG, E.P.E.: €2,222
  Serviços Municipalizados de Água e Saneamento de Sintra: €2,192
  Município de Loures: €2,032
  Unidade Local de Saúde de Santa Maria, EPE: €1,909
  Centro Hospitalar de Lisboa Ocidental, E. P. E.: €1,799
  Serviços Intermunicipalizados de Água e Saneamento dos Municípios de Oeiras e Amadora: €1,656
  Secretaria-Geral do Ministério da Administração Interna: €1,643
  Município de Vila Franca de Xira: €1,602
  Centro Hospitalar Universitário de Lisboa Norte, EPE: €1,575
  Serviços Intermunicipalizados de Águas e Resíduos dos Municípios de Loures e Odivelas: €1,549
  Estado Maior da Força Aérea: €1,473
  Águas do Tejo Atlântico, S. A.: €1,423
  Município da Amadora: €1,412
  Autoridade Tributária e Aduaneira: €1,407
  Estado-Maior-General das Forças Armadas (EMGFA): €1,397
  EMEL - Empresa Municipal de Mobilidade e Estacionamento de Lisboa, E. M., S. A.: €1,312
  Município de Odivelas: €1,297
  Centro Hospitalar de Lisboa Ocidental, EPE (CHLO): €1,287
  Município de Mafra: €1,212
  Instituto Hidrográfico: €1,203
  Tratolixo - Tratamento de Residuos Sólidos, E. I. M. - Empresa Intermunicipal, S. A.: €1,120
  Fundação INATEL: €1,119
  Rádio e Televisão de Portugal, S. A.: €1,104
  EMAC - Empresa Municipal de Ambiente de Cascais, E. M., S. A.: €1,103
  SPMS - Serviços Partilhados do Ministério da Saúde, E. P. E.: €1,084
  Parques de Sintra - Monte da Lua, S. A.: €1,073
  Município de Torres Vedras: €975
  EPAL - Empresa Portuguesa das Águas Livres, S. A.: €971
  Instituto Superior de Economia e Gestão: €945
  Serviços de Ação Social da Universidade de Lisboa: €935
  Universidade Nova de Lisboa: €932
  Banco de Portugal: €930
  Unidade Local de Saúde de Lisboa Ocidental, EPE: €919
  Casa Pia de Lisboa, I. P.: €908
  Infraestruturas de Portugal, S. A.: €906
  Metropolitano de Lisboa, E. P. E.: €896
  Agência para a Modernização Administrativa, I. P.: €877
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E. M., S. A.: €871
  Estado-Maior do Exército: €870
  Polícia de Segurança Pública: €814
  Unidade Local de Saúde de Amadora/Sintra, E. P. E.: €803
  Instituto de Gestão Financeira e Equipamentos da Justiça, I. P.: €716
  CLARANET II SOLUTIONS, S.A.: €708
  Assembleia da República: €700
  Águas do Tejo Atlântico, SA: €697
  Instituto Nacional de Investigação Agrária e Veterinária, I. P.: €695
  Instituto de Ação Social das Forças Armadas, I. P.: €687
  Serviços Municipalizados de Águas e Saneamento de Mafra - SMAS de Mafra: €684
  Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P.: €683
  Secretaria-Geral do Ministério do Trabalho, Solidariedade e Segurança Social: €680
  Instituto Nacional de Emergência Médica, I. P.: €679
  Serviço de Utilização Comum dos Hospitais: €671
  Município de Alenquer: €671
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR): €649
  Universidade de Lisboa: €615
  Ministério da Defesa Nacional - Marinha: €603
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A.: €599
  ESTADO-MAIOR-GENERAL DAS FORÇAS ARMADAS: €577
  Lisboa Ocidental, SRU - Sociedade de Reabilitação Urbana E. M., S. A.: €573
  Entidade de Serviços Partilhados da Administração Pública, I. P.: €570
  Imprensa Nacional - Casa da Moeda, S. A.: €569
  ISCTE - Instituto Universitário de Lisboa: €567
  Comissão do Mercado de Valores Mobiliários: €558
  Instituto Superior Técnico: €533
  Instituto de Informática, I. P.: €532
  Unidade Local de Saude Amadora/Sintra, E.P.E.: €528
  Escola Superior Náutica Infante D. Henrique: €527
  BASE2, LDA: €518
  Autoridade Nacional de Emergência e Proteção Civil: €514
  Autoridade Nacional de Comunicações: €509
  Secretaria-Geral da Presidência da República: €507
  Instituto da Mobilidade e dos Transportes, I. P.: €500
  Instituto Português de Oncologia de Lisboa Francisco Gentil, EPE: €493
  Direção-Geral de Alimentação e Veterinária: €491
  Secretaria-Geral do Ministério da Defesa Nacional: €489
  MEO - Serviços de Comunicações e Multimédia, S.A.: €488
  Município do Cadaval: €483
  Instituto do Turismo de Portugal, I. P.: €480
  Petrogal, S.A.: €477
  Hospital Professor Doutor Fernando Fonseca, E. P. E.: €470
  INETUM ESPAÑA, S.A. - Sucursal em Portugal: €451
  APL - Administração do Porto de Lisboa, S. A.: €450
  Adm.Reg.de Saúde de Lisboa e Vale do Tejo (ARSLVT): €448
  Instituto Politécnico de Lisboa: €446
  Secretaria-Geral do Ministério dos Negócios Estrangeiros: €443
  Construção Pública, E. P. E.: €438
  Município de Arruda dos Vinhos: €437
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM): €426
  LM - Laboratório Nacional do Medicamento: €421
  Instituto da Conservação da Natureza e das Florestas, I. P.: €416
  Instituto Nacional de Medicina Legal e Ciências Forenses, I. P.: €411
  Instituto da Habitação e da Reabilitação Urbana, I. P.: €409
  Instituto Nacional de Estatística, I. P.: €404
  Autoridade para as Condições do Trabalho: €404
  Warpcom Services, S.A.: €399
  Direção-Geral do Livro, dos Arquivos e das Bibliotecas: €389
  Autoridade Nacional de Segurança Rodoviária: €388
  CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA: €387
  Hospital de Loures, E. P. E.: €384
  Procuradoria-Geral da República: €382
  Centro de Formação Profissional da Indústria da Construção Civil e Obras Públicas do Sul (CENFIC): €377
  Vodafone Portugal, Comunicações Pessoais, S.A.: €377
  Faculdade de Medicina Veterinária: €374
  Instituto Português do Desporto e Juventude, I. P.: €370
  INFARMED - Autoridade Nacional do Medicamento e Produtos de Saúde, I. P.: €366
  NOS - Comunicações S.A.: €358
  Fundação para a Ciência e a Tecnologia, I. P.: €357
  Agência para a Integração, Migrações e Asilo, I. P.: €356
  Direção-Geral do Tribunal de Contas: €354
  Exitus, Soluções Tecnológicas, Lda.: €353
  Fine Facility Services, Lda: €349
  Laboratório Nacional de Engenharia Civil, I. P.: €342
  Instituto Nacional de Saúde Doutor Ricardo Jorge, IP: €341
  Instituto do Emprego e da Formação Profissional, I. P.: €341
  Ordem dos Contabilistas Certificados: €341
  Companhia Carris de Ferro de Lisboa, E. M., S. A.: €338
  Agência para o Desenvolvimento e Coesão, I. P.: €333
  Município da Lourinhã: €330
  INETUM ESPAÑA  SA: €329
  Ohmtécnica - Representações de Marcas, Lda: €323
  Timestamp - Sistemas de Informação, S.A.: €321
  Faculdade de Farmácia da Universidade de Lisboa: €315
  Freguesia de Benfica: €312
  Interlimpe - Facility services, SA: €310
  Polícia Judiciária: €309
  PETROGAL, S.A.: €308
  CLARANET PORTUGAL, S.A.: €305
  Escola Secundária Gago Coutinho, Alverca do Ribatejo - Vila Franca de Xira: €301
  Associação de Turismo de Lisboa - Visitors and Convention Bureau: €301
  Logicalis Portugal, SA: €299
  OPART - Organismo de Produção Artística, E. P. E.: €294
  Sá Limpa - Facility Services, Lda: €293
  Secretaria-Geral do Ministério da Economia: €288
  Serviços Sociais da Guarda Nacional Republicana: €288
  Secretaria-Geral da Presidência do Conselho de Ministros: €287
  Instituto dos Registos e do Notariado, I. P.: €284
  Direção-Geral de Recursos Naturais, Segurança e Serviços Marítimos: €280
  Freguesia de Marvila: €277
  Município de Azambuja: €275
  1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A.: €275
  Faculdade de Direito da Universidade de Lisboa: €272
  Parques Tejo, E. M.: €270
  SIMAR – Serviços Intermunicipalizados de Loures e Odivelas: €270
  Câmara Municipal de Vila Franca de Xira: €268
  Reload - Consultoria Informática Unipessoal, Lda: €267
  Faculdade Medicina Universidade de Lisboa: €267
  Sogenave - Sociedade Geral de Abastecimentos à Navegação e Indústria Hoteleira, SA: €266
  Serviços Municipalizados de Sintra (SMAS): €266
  RIOBOCO - Serviços Gerais, engenharia e Manutenção, S.A.: €263
  Direção-Geral da Educação: €263
  Direção-Geral do Território: €262
  Fundação Centro Cultural de Belém: €262
  EMEL - EMPRESA MUNICIPAL DE MOBILIDADE E ESTACIONAMENTO DE LISBOA, E.M., S.A: €261
  BANCO DE PORTUGAL: €260
  Instituto Português do Mar e da Atmosfera, I. P.: €259
  BELTRAO COELHO, LDA.: €258
  Cascais Envolvente -  Gestão Social da Habitação, E. M., S. A.: €253
  AdP - Águas de Portugal, SGPS, S. A.: €253
  SPMS- Serviços Partilhados do M. da Saúde, E.P.E.: €253
  Autoridade de Supervisão de Seguros e Fundos de Pensões (ASF): €251
  Ciência Viva - Agência Nacional para a Cultura Científica e Tecnológica: €250
  EXUMAS CONSULTING GROUP LDA.: €250
  Águas do Vale do Tejo, S. A.: €243
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E.M., S.A.: €242
  Servisan - Produtos de Higiene, S.A.: €238
  Rádio e Televisão de Portugal, SA: €233
  Parques de Sintra - Monte da Lua, SA: €224
  Instituto de Gestão Financeira da Educação, I. P.: €223
  SYNCHRO - SERVIÇOS EM OUTSOURCING, LDA: €223
  Municipio da Amadora: €222
  Instituto de Financiamento da Agricultura e Pescas - IFAP, I. P.: €221
  IMPRENSA NACIONAL - CASA DA MOEDA SA: €221
  Força Aérea Portuguesa: €221
  MEDTRONIC PORTUGAL, LDA.: €219
  Agência para a Reforma Tecnológica do Estado, IP: €218
  IHRU Instituto da Habitação e da Reabilitação Urbana: €218
  NTT Data Portugal, S.A: €218
  Faculdade de Letras da Universidade de Lisboa: €217
  Tratolixo - Tratamento de Residuos Sólidos, EIM - Empresa Intermunicipal, SA: €217
  IDW - Consultoria em Serviços de Informação, Lda: €216
  Fidelidade – Companhia de Seguros, S.A: €215
  CASA PIA DE LISBOA, I.P.: €214
  Lucro Exponencial, Unipessoal, Lda: €214
  Autoridade da Mobilidade e dos Transportes: €213
  GENERALI SEGUROS, SA: €212
  Faculdade de Motricidade Humana: €210
  Unidade Local de Saúde do Estuário do Tejo, E.P.E.: €209
  Instituto da Segurança Social, I. P.: €209
  TML - Transportes Metropolitanos de Lisboa, E. M. T., S. A.: €209
  Freguesia de Parque das Nações: €208
  Docapesca - Portos e Lotas, S. A.: €208
  Parques de Sintra-Monte da Lua, SA: €207
  AXIANSEU II DIGITAL CONSULTING, S.A.: €206
  Instituto Superior de Ciências Sociais e Políticas: €205
  Instituto Superior de Engenharia de Lisboa: €204
  MARL - Mercado Abastecedor da Região de Lisboa, S. A.: €204
  Leaseplan Portugal, Lda.: €204
  Secretaria-Geral do Governo: €204
  HOSPITAL PROFESSOR DOUTOR FERNANDO FONSECA, EPE: €203
  C. E. C. D. Mira Sintra - Centro de Educação para o Cidadão Deficiente, C. R. L.: €202
  Cooptécnica - Gustave Eiffel, Cooperativa de Ensino e Formação Técnico Profissional, C. R. L.: €201
  ISEG - Instituto Superior de Economia e Gestão: €201
  Corbroker  - Corretores de Seguros, S.A: €201
  Serviços Municipalizados de Água e Saneamento da Câmara Municipal Vila Franca de Xira: €201
  LOCARENT - COMPANHIA PORTUGUESA DE ALUGUER DE VIATURAS, S.A.: €199
  Escola Superior de hotelaria e Turismo do Estoril: €199
  EPAL - Empresa Portuguesa das Águas Livres, SA: €199
  Fundação Cultursintra, FP: €196
  Iberdrola Clientes Portugal Unipessoal: €192
  PERENE, S.A.: €192
  CSH, COMERCIO SERVIÇO HIGIENE, LDA.: €191
  Timestamp – Sistemas de Informação, S.A.: €191
  SMAS: €191
  AXIANSEU DIGITAL SOLUTIONS, S.A.: €190
  Serviços Sociais da Administração Pública: €189
  Instituto de Ação Social das Forças Armadas, I.P.: €188
  VWR International - Material de Laboratório, Soc. Unipessoal, Lda: €187
  Turismo de Portugal, IP: €186
  CICCOPN - Centro de Formação Profissional da Indústria da Construção Civil e Obras Públicas: €185
  Agência Portuguesa do Ambiente, I. P.: €184
  Luzboa - Comercialização, Lda: €183
  Companhia Carris de Ferro de Lisboa, EM, SA: €183
  Claranet II Solutions, S.A.: €181
  Beltrão Coelho - Sistemas de Escritório, Lda: €180
  Ambienti D'Interni Lda: €179
  BRAVANTIC, SA: €177
  Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda.: €177
  Secretaria-Geral do MAI: €177
  ENSINUS - Estudos Técnicos e Profissionais, S. A.: €176
  Águas do Centro Litoral, S. A.: €172
  Instituto de Gestão Financeira e Equipamentos da Justiça, IP: €172
  AdP Valor - Serviços Ambientais, S. A.: €172
  Confederação dos Agricultores de Portugal: €172
  MEDTRONIC PORTUGAL, LDA: €171
  VODAFONE PORTUGAL - Comunicações Pessoais, S.A.: €168
  Reload - Consultoria Informática, Lda: €168
  Autoridade Nacional de Aviação Civil: €167
  Serviços Partilhados do Ministério da Saúde, EPE: €167
  Município de Sobral de Monte Agraço: €167
  INETUM ESPAÑA, S.A. - SUCURSAL EM PORTUGAL: €166
  Estrutura de Missão para a Gestão do Plano Estratégico da Política Agrícola Comum no Continente: €166
  Instituto de Proteção e Assistência na Doença, I. P.: €165
  Vodafone Portugal - Comunicações Pessoais, S.A.: €165
  General Electric Healthcare Portugal, Sociedade Unipessoal, Lda.: €165
  IGNÍT PEOPLE, S.A.: €164
  Faculdade Ciências Universidade Lisboa: €163
  HIGIENOVA-HIGIENE E LIMPEZA INDUSTRIAL, LDA: €163
  Medtronic Portugal, Lda.: €163
  Laboratório Nacional do Medicamento: €163
  Quilaban, S.A: €163
  TMLJ - FACILITY SERVICES, UNIPESSOAL LDA: €162
  Boston Scientific Portugal, Dispositivos Médicos, Lda.: €161
  Entidade de Serviços Partilhados da Administração Pública, IP: €161
  Serviços Sociais da Câmara Municipal de Lisboa: €157
  WERFEN PORTUGAL, LDA.: €156
  PTTEX, LDA: €155
  LeasePlan Portugal - Com. e Alug. de Autom. e Equip., Unip. Lda.: €155
  Instituto Superior de Agronomia: €154
  Transtejo - Transportes Tejo, S. A.: €154
  Ambimed - Gestão Ambiental, Lda: €153
  Centro de Formação Profissional da Reparação Automóvel: €153
  Unidade Local de Saúde do Estuário do Tejo, E. P. E.: €153
  Caravela Companhia de Seguros SA: €153
  Autoridade da Concorrência: €153
  CCR Legal - Sociedade de Advogados, SP, RL: €152
  HOSPITAL DE LOURES, E.P.E: €149
  PRICEWATERHOUSECOOPERS LEGAL – SOCIEDADE DE ADVOGADOS, SP, RL: €148
  Construção Pública, E.P.E.: €147
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P.: €147
  Faculdade de Arquitetura da Universidade de Lisboa: €147
  Instituto de Informática, IP.: €146
  MDS - Corretor de Seguros, S.A.: €146
  Faculdade de Medicina Dentária da Universidade de Lisboa: €146
  APPACDM DE LISBOA - Associação Portuguesa de Pais e Amigos do Cidadão Deficiente Mental: €145
  AECI, Arquitectura Construção e Empreendimentos Imobiliários, SA: €145
  KONICA MINOLTA BUSINESS SOLUTIONS PORTUGAL, UNIPESSOAL, LDA: €144
  B. BRAUN MEDICAL, UNIPESSOAL LDA: €144
  CLINIFAR SA: €144
  Estrutura de Missão «Recuperar Portugal»: €144
  Oramix Sistemas de Informação S.A: €144
  Endesa Energia, S.A. – Sucursal Portugal: €143
  Iberdrola Clientes Portugal Unipessoal, Lda.: €143
  Hospital de Vila Franca de Xira, E.P.E.: €143
  Meo - Serviços de Comunicações e Multimédia, SA: €142
  Centro Formação Profissional Para o Sector Alimentar: €142
  maquilotus-comercio de produtos de limpeza lda: €141
  BASEDOIS - Informática e Telecomunicações, Lda.: €140
  Barraqueiro Transportes SA: €140
  B.Braun Medical, Unipessoal Lda.: €140
  EDNI  - Empresa Distribiudora de Material Informático, Lda: €140
  Capgemini Portugal, S.A.: €139
  Escola Nacional de Bombeiros: €138
  ECOAMBIENTE - Serviços e Meio Ambiente S.A.: €137
  B. Braun Medical, Unipessoal Lda.: €137
  Instituto da Conservação da Natureza e das Florestas, IP: €137
  Conselho Português para os Refugiados - CPR: €136
  IEFP: €136
  SIMAS Oeiras e Amadora: €136
  Uniself - Sociedade de Restaurantes Públicos e Privados, S.A.: €136
  Direção-Geral da Administração da Justiça: €135
  HCCM CONSULTING, S.A.: €134
  Exitus, Soluções Tecnológicas, Lda: €134
  Infraestruturas de Portugal: €132
  Entidade Reguladora dos Serviços de Águas e Resíduos: €132
  Relva Viva - Gestão Florestal e Jardins Unip. Lda.: €132
  Instituto do Turismo de Portugal, IP: €131
  Instituto do Emprego e Formação Profissional, IP: €131
  Constradas - Estradas e Construção Civil, S.A.: €130
  ESTAMO - Participações Imobiliárias, SA: €130
  Frilabo II, Lda.: €130
  Fidelidade Companhia de Seguros, S.A.: €130
  Aon Portugal, S.A.: €130
  Teprel - Equipamentos Médicos SA: €129
  FUJIFILM PORTUGAL, S.A.: €129
  Lusopalex - Produtos de Saude Unipessoal Lda: €129
  OutSystems - Software em Rede, S.A.: €129
  VALPI RENT, LDA: €129
  - - PETROGAL, S.A.: €129
  WIKIBUILD,S.A: €128
  Municipio da Lourinhã: €128
  Instituto de Gestão Financeira da Segurança Social, I. P.: €128
  Planeta Vertical Lda: €127
  Ordem dos Solicitadores e dos Agentes de Execução: €127
  Claranet Portugal, S.A.: €127
  Cascais Dinâmica - Gestão de Economia, Turismo e Empreendorismo, E. M., S. A.: €126
  MEDICINÁLIA CORMÉDICA - MCMEDICAL, LIMITADA: €125
  SUCH | Serviço de Utilização Comum dos Hospitais: €125
  EVONIC - EVOLUTION AND INNOVATION CONSULTING, LDA: €125
  Martins Pereira, João Careca &amp; Associados - Soc. de Revisores Oficiais de Contas, Lda.: €125
  Faculdade de Belas Artes: €124
  METROPOLITANO DE LISBOA, E.P.E: €124
  Willis - Corretores de Seguros, S.A.: €123
  Direção-Geral da Administração e do Emprego Público: €123
  ICA - Indústria e Comércio Alimentar, S.A.: €123
  Administração Regional de Saúde de Lisboa e Vale do Tejo, I. P.: €123
  Logicalis Portugal, S.A.: €122
  Ordem dos Advogados: €122
  Openline Facility Services, S.A.: €122
  - - B2 MOBILITY, GMBH: €122
  TRATOLIXO - Tratamento de Resíduos Sólidos, EIM: €122
  Operandus - Limpeza Profissional, Lda.: €121
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A.: €121
  Cooptécnica - Gustave Eiffel, Cooperativa de Ensino e Formação Técnico Profissional, CRL: €121
  ADPN-ENGENHARIA E MANUTENÇÃO, UNIPESSOAL LDA: €121
  DIGIBÉRIA INFORMATION TECHNOLOGIES, S.A.: €120
  FIDELIDADE - COMPANHIA DE SEGUROS, SA: €120
  NOVA EXPRESSÃO- Planeamento de Meios e Publicidade , S.A.: €120
  BioMerieux Portugal: €120
  ENVIMAN - Manutenção de Sistemas Ambientais, Lda.: €120
  GIATUL - Atividades Lúdicas, Infraestruturas e Rodovias, E. M., S. A.: €120
  Hospital Prof. Doutor Fernando Fonseca E.P.E.: €119
  COPS Companhia Operacional de Segurança, Unipessoal Lda.: €119
  Freguesia de Alvalade: €119
  MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A.: €119
  Faculdade de Psicologia da Universidade de Lisboa: €119
  OPART - Organismo de Produção Artística, EPE: €119
  Virtugal, Lda: €118
  AIG EUROPE S.A.: €118
  BIOSONDA, COMERCIO DE MATERIAL HOSPITALAR, LDA: €117
  BOSTON SCIENTIFIC PORTUGAL, LDA: €117
  Freguesia de Arroios: €117
  MDS – Corretor de Seguros, S.A: €117
  Gertal - Companhia Geral de Restaurantes e Alimentação, S.A.: €117
  Área Metropolitana de Lisboa: €117
  Linde Portugal, Lda.: €116
  Freguesia da Misericórdia: €115
  Oeiras Viva - Gestão de Equipamentos Sócio Culturais e Desportivos, E. M.: €115
  ConfigBit, Lda: €115
  Hospitex - Material Hospitalar, Lda.: €115
  LISBOA OCIDENTAL, SRU - SOCIEDADE DE REABILITAÇÃO URBANA, EM, S.A.: €114
  Instituto de Informática, IP: €114
  UNIKONSTRÓI, Lda.: €114
  Meristema, S.A.: €114
  ENGIBENE LDA: €113
  Stryker Portugal Produtos Médicos, Lda.: €113
  Bio-Rad Laboratories, Lda.: €113
  Medline international Portugal, Unipessoal, Lda.: €113

## <font size=5>**3.5 Degree VS Volume**</font> <a class="anchor" id="3.5"></a>
  
[Back to TOC](#toc)

- Degree $\rightarrow$ number of contracts associated with each entity (network degree = in_degree + out_degree)
- Volume $\rightarrow$ total contracted amount associated with each entity (sum of incident edge weights)

**Purpose**: assess which entities are most valuable and how activity (degree) relates to economic impact (volume).

Planned steps:
- compute degree and volume per node
- plot degree vs. volume (use log–log scatter), annotate top entities
- report Pearson and Spearman correlations
- fit a linear model on log-transformed values and flag outliers (high volume/low degree and high degree/low volume)

In [25]:
# Degree and volume per node
metrics = pd.DataFrame({
    "degree": pd.Series(dict(G.degree())),
    "volume": pd.Series(volume)
}).fillna(0)

In [26]:
# Keep only positive values for log-log analysis
pos = metrics[(metrics["degree"] > 0) & (metrics["volume"] > 0)].copy()
pos["log_degree"] = np.log10(pos["degree"])
pos["log_volume"] = np.log10(pos["volume"])

# Correlations on log-transformed values
pearson = pos["log_degree"].corr(pos["log_volume"], method="pearson")
spearman = pos["log_degree"].corr(pos["log_volume"], method="spearman")

print(f"Nodes used in log-log analysis: {len(pos)}")
print(f"Pearson correlation (log10):  {pearson:.4f}")
print(f"Spearman correlation (log10): {spearman:.4f}")

Nodes used in log-log analysis: 10161
Pearson correlation (log10):  0.9697
Spearman correlation (log10): 0.8734

In [27]:
# Linear model in log-log space
slope, intercept = np.polyfit(pos["log_degree"], pos["log_volume"], 1)
pos["pred_log_volume"] = intercept + slope * pos["log_degree"]
pos["residual"] = pos["log_volume"] - pos["pred_log_volume"]

print(f"\nlog10(volume) = {intercept:.4f} + {slope:.4f} * log10(degree)")

log10(volume) = 1.0241 + 0.9907 * log10(degree)

In [28]:
# Flag outliers using the box-plot rule (IQR)
degree_dict = dict(G.degree())

q1 = pd.Series(volume).quantile(0.25)
q3 = pd.Series(volume).quantile(0.75)
iqr = q3 - q1
volume_threshold = q3 + 1.5 * iqr

print(f"Volume threshold from box plot rule: €{volume_threshold:,.0f}")
print("Flagged entities (degree ≥ 3 AND volume above upper fence):")

flagged = []
for entity in G.nodes():
    if degree_dict[entity] >= 3 and volume[entity] > volume_threshold:
        flagged.append((entity, degree_dict[entity], volume[entity]))

flagged.sort(key=lambda x: x[2], reverse=True)
for entity, deg, vol in flagged:
    print(f"  {entity}  degree={deg}  volume=€{vol:,.0f}")

print(f"\nTotal flagged: {len(flagged)}")

Volume threshold from box plot rule: €46
Flagged entities (degree ≥ 3 AND volume above upper fence):
  Unidade Local de Saúde de São José, E. P. E.  degree=789  volume=€7,198
  Santa Casa da Misericórdia de Lisboa  degree=742  volume=€6,735
  Município de Sintra  degree=566  volume=€6,262
  Instituto Português de Oncologia de Lisboa Francisco Gentil, E. P. E.  degree=730  volume=€6,145
  Unidade Local de Saúde de Santa Maria, E. P. E.  degree=596  volume=€5,589
  Município de Oeiras  degree=428  volume=€5,050
  Centro Hospitalar Universitário Lisboa Central, E. P. E.  degree=450  volume=€4,079
  Centro Hospitalar Universitário de Lisboa Central, E.P.E. (CHULC)  degree=366  volume=€3,331
  Município de Cascais  degree=257  volume=€3,133
  Unidade Local de Saúde de Lisboa Ocidental, E. P. E.  degree=264  volume=€2,781
  Unidade Local de Saúde de São José, EPE  degree=285  volume=€2,719
  Unidade Local de Saúde de Loures-Odivelas, E. P. E.  degree=320  volume=€2,716
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A.  degree=233  volume=€2,698
  Guarda Nacional Republicana  degree=230  volume=€2,295
  Centro Hospitalar Universitário de Lisboa Norte, E. P. E.  degree=241  volume=€2,280
  Município de Lisboa  degree=186  volume=€2,251
  Unidade Local de Saúde de Loures-Odivelas, EPE  degree=268  volume=€2,247
  Instituto Português de Oncologia de Lisboa FG, E.P.E.  degree=263  volume=€2,222
  Serviços Municipalizados de Água e Saneamento de Sintra  degree=198  volume=€2,192
  Município de Loures  degree=166  volume=€2,032
  Unidade Local de Saúde de Santa Maria, EPE  degree=206  volume=€1,909
  Centro Hospitalar de Lisboa Ocidental, E. P. E.  degree=176  volume=€1,799
  Serviços Intermunicipalizados de Água e Saneamento dos Municípios de Oeiras e Amadora  degree=153  volume=€1,656
  Secretaria-Geral do Ministério da Administração Interna  degree=145  volume=€1,643
  Município de Vila Franca de Xira  degree=133  volume=€1,602
  Centro Hospitalar Universitário de Lisboa Norte, EPE  degree=166  volume=€1,575
  Serviços Intermunicipalizados de Águas e Resíduos dos Municípios de Loures e Odivelas  degree=138  volume=€1,549
  Estado Maior da Força Aérea  degree=137  volume=€1,473
  Águas do Tejo Atlântico, S. A.  degree=119  volume=€1,423
  Município da Amadora  degree=117  volume=€1,412
  Autoridade Tributária e Aduaneira  degree=119  volume=€1,407
  Estado-Maior-General das Forças Armadas (EMGFA)  degree=131  volume=€1,397
  EMEL - Empresa Municipal de Mobilidade e Estacionamento de Lisboa, E. M., S. A.  degree=107  volume=€1,312
  Município de Odivelas  degree=102  volume=€1,297
  Centro Hospitalar de Lisboa Ocidental, EPE (CHLO)  degree=121  volume=€1,287
  Município de Mafra  degree=99  volume=€1,212
  Instituto Hidrográfico  degree=134  volume=€1,203
  Tratolixo - Tratamento de Residuos Sólidos, E. I. M. - Empresa Intermunicipal, S. A.  degree=97  volume=€1,120
  Fundação INATEL  degree=111  volume=€1,119
  Rádio e Televisão de Portugal, S. A.  degree=102  volume=€1,104
  EMAC - Empresa Municipal de Ambiente de Cascais, E. M., S. A.  degree=93  volume=€1,103
  SPMS - Serviços Partilhados do Ministério da Saúde, E. P. E.  degree=92  volume=€1,084
  Parques de Sintra - Monte da Lua, S. A.  degree=97  volume=€1,073
  Município de Torres Vedras  degree=84  volume=€975
  EPAL - Empresa Portuguesa das Águas Livres, S. A.  degree=78  volume=€971
  Instituto Superior de Economia e Gestão  degree=91  volume=€945
  Serviços de Ação Social da Universidade de Lisboa  degree=88  volume=€935
  Universidade Nova de Lisboa  degree=81  volume=€932
  Banco de Portugal  degree=78  volume=€930
  Unidade Local de Saúde de Lisboa Ocidental, EPE  degree=91  volume=€919
  Casa Pia de Lisboa, I. P.  degree=89  volume=€908
  Infraestruturas de Portugal, S. A.  degree=73  volume=€906
  Metropolitano de Lisboa, E. P. E.  degree=72  volume=€896
  Agência para a Modernização Administrativa, I. P.  degree=76  volume=€877
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E. M., S. A.  degree=72  volume=€871
  Estado-Maior do Exército  degree=78  volume=€870
  Polícia de Segurança Pública  degree=70  volume=€814
  Unidade Local de Saúde de Amadora/Sintra, E. P. E.  degree=76  volume=€803
  Instituto de Gestão Financeira e Equipamentos da Justiça, I. P.  degree=57  volume=€716
  CLARANET II SOLUTIONS, S.A.  degree=63  volume=€708
  Assembleia da República  degree=60  volume=€700
  Águas do Tejo Atlântico, SA  degree=58  volume=€697
  Instituto Nacional de Investigação Agrária e Veterinária, I. P.  degree=67  volume=€695
  Instituto de Ação Social das Forças Armadas, I. P.  degree=66  volume=€687
  Serviços Municipalizados de Águas e Saneamento de Mafra - SMAS de Mafra  degree=62  volume=€684
  Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P.  degree=79  volume=€683
  Secretaria-Geral do Ministério do Trabalho, Solidariedade e Segurança Social  degree=63  volume=€680
  Instituto Nacional de Emergência Médica, I. P.  degree=76  volume=€679
  Serviço de Utilização Comum dos Hospitais  degree=62  volume=€671
  Município de Alenquer  degree=60  volume=€671
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR)  degree=62  volume=€649
  Universidade de Lisboa  degree=56  volume=€615
  Ministério da Defesa Nacional - Marinha  degree=55  volume=€603
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A.  degree=51  volume=€599
  ESTADO-MAIOR-GENERAL DAS FORÇAS ARMADAS  degree=53  volume=€577
  Lisboa Ocidental, SRU - Sociedade de Reabilitação Urbana E. M., S. A.  degree=43  volume=€573
  Entidade de Serviços Partilhados da Administração Pública, I. P.  degree=46  volume=€570
  Imprensa Nacional - Casa da Moeda, S. A.  degree=50  volume=€569
  ISCTE - Instituto Universitário de Lisboa  degree=50  volume=€567
  Comissão do Mercado de Valores Mobiliários  degree=49  volume=€558
  Instituto Superior Técnico  degree=46  volume=€533
  Instituto de Informática, I. P.  degree=47  volume=€532
  Unidade Local de Saude Amadora/Sintra, E.P.E.  degree=49  volume=€528
  Escola Superior Náutica Infante D. Henrique  degree=51  volume=€527
  BASE2, LDA  degree=49  volume=€518
  Autoridade Nacional de Emergência e Proteção Civil  degree=47  volume=€514
  Autoridade Nacional de Comunicações  degree=44  volume=€509
  Secretaria-Geral da Presidência da República  degree=45  volume=€507
  Instituto da Mobilidade e dos Transportes, I. P.  degree=45  volume=€500
  Instituto Português de Oncologia de Lisboa Francisco Gentil, EPE  degree=51  volume=€493
  Direção-Geral de Alimentação e Veterinária  degree=40  volume=€491
  Secretaria-Geral do Ministério da Defesa Nacional  degree=45  volume=€489
  MEO - Serviços de Comunicações e Multimédia, S.A.  degree=44  volume=€488
  Município do Cadaval  degree=46  volume=€483
  Instituto do Turismo de Portugal, I. P.  degree=40  volume=€480
  Petrogal, S.A.  degree=41  volume=€477
  Hospital Professor Doutor Fernando Fonseca, E. P. E.  degree=42  volume=€470
  INETUM ESPAÑA, S.A. - Sucursal em Portugal  degree=38  volume=€451
  APL - Administração do Porto de Lisboa, S. A.  degree=39  volume=€450
  Adm.Reg.de Saúde de Lisboa e Vale do Tejo (ARSLVT)  degree=52  volume=€448
  Instituto Politécnico de Lisboa  degree=42  volume=€446
  Secretaria-Geral do Ministério dos Negócios Estrangeiros  degree=37  volume=€443
  Construção Pública, E. P. E.  degree=36  volume=€438
  Município de Arruda dos Vinhos  degree=38  volume=€437
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM)  degree=39  volume=€426
  LM - Laboratório Nacional do Medicamento  degree=42  volume=€421
  Instituto da Conservação da Natureza e das Florestas, I. P.  degree=36  volume=€416
  Instituto Nacional de Medicina Legal e Ciências Forenses, I. P.  degree=47  volume=€411
  Instituto da Habitação e da Reabilitação Urbana, I. P.  degree=39  volume=€409
  Instituto Nacional de Estatística, I. P.  degree=36  volume=€404
  Autoridade para as Condições do Trabalho  degree=37  volume=€404
  Warpcom Services, S.A.  degree=35  volume=€399
  Direção-Geral do Livro, dos Arquivos e das Bibliotecas  degree=35  volume=€389
  Autoridade Nacional de Segurança Rodoviária  degree=35  volume=€388
  CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA  degree=33  volume=€387
  Hospital de Loures, E. P. E.  degree=38  volume=€384
  Procuradoria-Geral da República  degree=36  volume=€382
  Centro de Formação Profissional da Indústria da Construção Civil e Obras Públicas do Sul (CENFIC)  degree=37  volume=€377
  Vodafone Portugal, Comunicações Pessoais, S.A.  degree=32  volume=€377
  Faculdade de Medicina Veterinária  degree=35  volume=€374
  Instituto Português do Desporto e Juventude, I. P.  degree=31  volume=€370
  INFARMED - Autoridade Nacional do Medicamento e Produtos de Saúde, I. P.  degree=30  volume=€366
  NOS - Comunicações S.A.  degree=31  volume=€358
  Fundação para a Ciência e a Tecnologia, I. P.  degree=31  volume=€357
  Agência para a Integração, Migrações e Asilo, I. P.  degree=30  volume=€356
  Direção-Geral do Tribunal de Contas  degree=36  volume=€354
  Exitus, Soluções Tecnológicas, Lda.  degree=35  volume=€353
  Fine Facility Services, Lda  degree=31  volume=€349
  Laboratório Nacional de Engenharia Civil, I. P.  degree=35  volume=€342
  Instituto Nacional de Saúde Doutor Ricardo Jorge, IP  degree=38  volume=€341
  Instituto do Emprego e da Formação Profissional, I. P.  degree=29  volume=€341
  Ordem dos Contabilistas Certificados  degree=31  volume=€341
  Companhia Carris de Ferro de Lisboa, E. M., S. A.  degree=26  volume=€338
  Agência para o Desenvolvimento e Coesão, I. P.  degree=28  volume=€333
  Município da Lourinhã  degree=30  volume=€330
  INETUM ESPAÑA  SA  degree=29  volume=€329
  Ohmtécnica - Representações de Marcas, Lda  degree=46  volume=€323
  Timestamp - Sistemas de Informação, S.A.  degree=26  volume=€321
  Faculdade de Farmácia da Universidade de Lisboa  degree=32  volume=€315
  Freguesia de Benfica  degree=26  volume=€312
  Interlimpe - Facility services, SA  degree=25  volume=€310
  Polícia Judiciária  degree=29  volume=€309
  PETROGAL, S.A.  degree=26  volume=€308
  CLARANET PORTUGAL, S.A.  degree=25  volume=€305
  Escola Secundária Gago Coutinho, Alverca do Ribatejo - Vila Franca de Xira  degree=31  volume=€301
  Associação de Turismo de Lisboa - Visitors and Convention Bureau  degree=24  volume=€301
  Logicalis Portugal, SA  degree=25  volume=€299
  OPART - Organismo de Produção Artística, E. P. E.  degree=26  volume=€294
  Sá Limpa - Facility Services, Lda  degree=24  volume=€293
  Secretaria-Geral do Ministério da Economia  degree=26  volume=€288
  Serviços Sociais da Guarda Nacional Republicana  degree=26  volume=€288
  Secretaria-Geral da Presidência do Conselho de Ministros  degree=23  volume=€287
  Instituto dos Registos e do Notariado, I. P.  degree=22  volume=€284
  Direção-Geral de Recursos Naturais, Segurança e Serviços Marítimos  degree=25  volume=€280
  Freguesia de Marvila  degree=24  volume=€277
  Município de Azambuja  degree=23  volume=€275
  1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A.  degree=26  volume=€275
  Faculdade de Direito da Universidade de Lisboa  degree=25  volume=€272
  Parques Tejo, E. M.  degree=23  volume=€270
  SIMAR – Serviços Intermunicipalizados de Loures e Odivelas  degree=24  volume=€270
  Câmara Municipal de Vila Franca de Xira  degree=23  volume=€268
  Reload - Consultoria Informática Unipessoal, Lda  degree=22  volume=€267
  Faculdade Medicina Universidade de Lisboa  degree=25  volume=€267
  Sogenave - Sociedade Geral de Abastecimentos à Navegação e Indústria Hoteleira, SA  degree=25  volume=€266
  Serviços Municipalizados de Sintra (SMAS)  degree=24  volume=€266
  RIOBOCO - Serviços Gerais, engenharia e Manutenção, S.A.  degree=23  volume=€263
  Direção-Geral da Educação  degree=23  volume=€263
  Direção-Geral do Território  degree=21  volume=€262
  Fundação Centro Cultural de Belém  degree=22  volume=€262
  EMEL - EMPRESA MUNICIPAL DE MOBILIDADE E ESTACIONAMENTO DE LISBOA, E.M., S.A  degree=22  volume=€261
  BANCO DE PORTUGAL  degree=23  volume=€260
  Instituto Português do Mar e da Atmosfera, I. P.  degree=21  volume=€259
  BELTRAO COELHO, LDA.  degree=24  volume=€258
  Cascais Envolvente -  Gestão Social da Habitação, E. M., S. A.  degree=23  volume=€253
  AdP - Águas de Portugal, SGPS, S. A.  degree=24  volume=€253
  SPMS- Serviços Partilhados do M. da Saúde, E.P.E.  degree=21  volume=€253
  Autoridade de Supervisão de Seguros e Fundos de Pensões (ASF)  degree=21  volume=€251
  Ciência Viva - Agência Nacional para a Cultura Científica e Tecnológica  degree=21  volume=€250
  EXUMAS CONSULTING GROUP LDA.  degree=25  volume=€250
  Águas do Vale do Tejo, S. A.  degree=21  volume=€243
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E.M., S.A.  degree=20  volume=€242
  Servisan - Produtos de Higiene, S.A.  degree=26  volume=€238
  Rádio e Televisão de Portugal, SA  degree=20  volume=€233
  Parques de Sintra - Monte da Lua, SA  degree=19  volume=€224
  Instituto de Gestão Financeira da Educação, I. P.  degree=18  volume=€223
  SYNCHRO - SERVIÇOS EM OUTSOURCING, LDA  degree=19  volume=€223
  Municipio da Amadora  degree=19  volume=€222
  Instituto de Financiamento da Agricultura e Pescas - IFAP, I. P.  degree=18  volume=€221
  IMPRENSA NACIONAL - CASA DA MOEDA SA  degree=19  volume=€221
  Força Aérea Portuguesa  degree=20  volume=€221
  MEDTRONIC PORTUGAL, LDA.  degree=21  volume=€219
  Agência para a Reforma Tecnológica do Estado, IP  degree=19  volume=€218
  IHRU Instituto da Habitação e da Reabilitação Urbana  degree=20  volume=€218
  NTT Data Portugal, S.A  degree=18  volume=€218
  Faculdade de Letras da Universidade de Lisboa  degree=20  volume=€217
  Tratolixo - Tratamento de Residuos Sólidos, EIM - Empresa Intermunicipal, SA  degree=18  volume=€217
  IDW - Consultoria em Serviços de Informação, Lda  degree=19  volume=€216
  Fidelidade – Companhia de Seguros, S.A  degree=18  volume=€215
  CASA PIA DE LISBOA, I.P.  degree=24  volume=€214
  Lucro Exponencial, Unipessoal, Lda  degree=32  volume=€214
  Autoridade da Mobilidade e dos Transportes  degree=20  volume=€213
  GENERALI SEGUROS, SA  degree=17  volume=€212
  Faculdade de Motricidade Humana  degree=19  volume=€210
  Unidade Local de Saúde do Estuário do Tejo, E.P.E.  degree=18  volume=€209
  Instituto da Segurança Social, I. P.  degree=19  volume=€209
  TML - Transportes Metropolitanos de Lisboa, E. M. T., S. A.  degree=17  volume=€209
  Freguesia de Parque das Nações  degree=19  volume=€208
  Docapesca - Portos e Lotas, S. A.  degree=19  volume=€208
  Parques de Sintra-Monte da Lua, SA  degree=19  volume=€207
  AXIANSEU II DIGITAL CONSULTING, S.A.  degree=16  volume=€206
  Instituto Superior de Ciências Sociais e Políticas  degree=20  volume=€205
  Instituto Superior de Engenharia de Lisboa  degree=17  volume=€204
  MARL - Mercado Abastecedor da Região de Lisboa, S. A.  degree=17  volume=€204
  Leaseplan Portugal, Lda.  degree=18  volume=€204
  Secretaria-Geral do Governo  degree=17  volume=€204
  HOSPITAL PROFESSOR DOUTOR FERNANDO FONSECA, EPE  degree=19  volume=€203
  C. E. C. D. Mira Sintra - Centro de Educação para o Cidadão Deficiente, C. R. L.  degree=20  volume=€202
  Cooptécnica - Gustave Eiffel, Cooperativa de Ensino e Formação Técnico Profissional, C. R. L.  degree=18  volume=€201
  ISEG - Instituto Superior de Economia e Gestão  degree=20  volume=€201
  Corbroker  - Corretores de Seguros, S.A  degree=20  volume=€201
  Serviços Municipalizados de Água e Saneamento da Câmara Municipal Vila Franca de Xira  degree=17  volume=€201
  LOCARENT - COMPANHIA PORTUGUESA DE ALUGUER DE VIATURAS, S.A.  degree=18  volume=€199
  Escola Superior de hotelaria e Turismo do Estoril  degree=21  volume=€199
  EPAL - Empresa Portuguesa das Águas Livres, SA  degree=17  volume=€199
  Fundação Cultursintra, FP  degree=17  volume=€196
  Iberdrola Clientes Portugal Unipessoal  degree=14  volume=€192
  PERENE, S.A.  degree=17  volume=€192
  CSH, COMERCIO SERVIÇO HIGIENE, LDA.  degree=22  volume=€191
  Timestamp – Sistemas de Informação, S.A.  degree=16  volume=€191
  SMAS  degree=17  volume=€191
  AXIANSEU DIGITAL SOLUTIONS, S.A.  degree=16  volume=€190
  Serviços Sociais da Administração Pública  degree=18  volume=€189
  Instituto de Ação Social das Forças Armadas, I.P.  degree=19  volume=€188
  VWR International - Material de Laboratório, Soc. Unipessoal, Lda  degree=21  volume=€187
  Turismo de Portugal, IP  degree=15  volume=€186
  CICCOPN - Centro de Formação Profissional da Indústria da Construção Civil e Obras Públicas  degree=19  volume=€185
  Agência Portuguesa do Ambiente, I. P.  degree=16  volume=€184
  Luzboa - Comercialização, Lda  degree=14  volume=€183
  Companhia Carris de Ferro de Lisboa, EM, SA  degree=15  volume=€183
  Claranet II Solutions, S.A.  degree=16  volume=€181
  Beltrão Coelho - Sistemas de Escritório, Lda  degree=16  volume=€180
  Ambienti D'Interni Lda  degree=16  volume=€179
  BRAVANTIC, SA  degree=16  volume=€177
  Rentokil Initial Portugal - Serviços de Protecção Ambiental, Lda.  degree=19  volume=€177
  Secretaria-Geral do MAI  degree=15  volume=€177
  ENSINUS - Estudos Técnicos e Profissionais, S. A.  degree=16  volume=€176
  Águas do Centro Litoral, S. A.  degree=17  volume=€172
  Instituto de Gestão Financeira e Equipamentos da Justiça, IP  degree=13  volume=€172
  AdP Valor - Serviços Ambientais, S. A.  degree=17  volume=€172
  Confederação dos Agricultores de Portugal  degree=15  volume=€172
  MEDTRONIC PORTUGAL, LDA  degree=17  volume=€171
  VODAFONE PORTUGAL - Comunicações Pessoais, S.A.  degree=15  volume=€168
  Reload - Consultoria Informática, Lda  degree=14  volume=€168
  Autoridade Nacional de Aviação Civil  degree=15  volume=€167
  Serviços Partilhados do Ministério da Saúde, EPE  degree=14  volume=€167
  Município de Sobral de Monte Agraço  degree=14  volume=€167
  INETUM ESPAÑA, S.A. - SUCURSAL EM PORTUGAL  degree=14  volume=€166
  Estrutura de Missão para a Gestão do Plano Estratégico da Política Agrícola Comum no Continente  degree=14  volume=€166
  Instituto de Proteção e Assistência na Doença, I. P.  degree=17  volume=€165
  Vodafone Portugal - Comunicações Pessoais, S.A.  degree=15  volume=€165
  General Electric Healthcare Portugal, Sociedade Unipessoal, Lda.  degree=15  volume=€165
  IGNÍT PEOPLE, S.A.  degree=14  volume=€164
  Faculdade Ciências Universidade Lisboa  degree=14  volume=€163
  HIGIENOVA-HIGIENE E LIMPEZA INDUSTRIAL, LDA  degree=17  volume=€163
  Medtronic Portugal, Lda.  degree=16  volume=€163
  Laboratório Nacional do Medicamento  degree=18  volume=€163
  Quilaban, S.A  degree=19  volume=€163
  TMLJ - FACILITY SERVICES, UNIPESSOAL LDA  degree=14  volume=€162
  Boston Scientific Portugal, Dispositivos Médicos, Lda.  degree=15  volume=€161
  Entidade de Serviços Partilhados da Administração Pública, IP  degree=14  volume=€161
  Serviços Sociais da Câmara Municipal de Lisboa  degree=14  volume=€157
  WERFEN PORTUGAL, LDA.  degree=14  volume=€156
  PTTEX, LDA  degree=16  volume=€155
  LeasePlan Portugal - Com. e Alug. de Autom. e Equip., Unip. Lda.  degree=14  volume=€155
  Instituto Superior de Agronomia  degree=13  volume=€154
  Transtejo - Transportes Tejo, S. A.  degree=12  volume=€154
  Ambimed - Gestão Ambiental, Lda  degree=14  volume=€153
  Centro de Formação Profissional da Reparação Automóvel  degree=14  volume=€153
  Unidade Local de Saúde do Estuário do Tejo, E. P. E.  degree=13  volume=€153
  Caravela Companhia de Seguros SA  degree=13  volume=€153
  Autoridade da Concorrência  degree=14  volume=€153
  CCR Legal - Sociedade de Advogados, SP, RL  degree=18  volume=€152
  HOSPITAL DE LOURES, E.P.E  degree=14  volume=€149
  PRICEWATERHOUSECOOPERS LEGAL – SOCIEDADE DE ADVOGADOS, SP, RL  degree=17  volume=€148
  Construção Pública, E.P.E.  degree=13  volume=€147

In [29]:
# Plotting

# prepare fit line
x_line = np.logspace(np.log10(pos["degree"].min()), np.log10(pos["degree"].max()), 200)
y_line = 10 ** (intercept + slope * np.log10(x_line))

# main traces
scatter = go.Scatter(
    x=pos["degree"],
    y=pos["volume"],
    mode="markers",
    marker=dict(size=6, color="steelblue", opacity=0.5),
    name="nodes",
    hovertemplate="%{text}<br>Degree: %{x}<br>Volume: €%{y:,.0f}",
    text=pos.index
)

fit_line = go.Scatter(
    x=x_line,
    y=y_line,
    mode="lines",
    line=dict(color="crimson", width=2),
    name="log-log fit"
)

# annotations for top entities
annotations = []
top_entities = [entity for entity, _ in top5]

for node in top_entities:
    x = metrics.loc[node, "degree"]
    y = metrics.loc[node, "volume"]
    annotations.append(
        dict(
            x=x,
            y=y,
            text=node,
            showarrow=True,
            arrowhead=2,
            ax=10,
            ay=-10,
            font=dict(size=10),
        )
    )

fig = go.Figure(data=[scatter, fit_line])
fig.update_layout(
    title="Degree VS Volume",
    xaxis=dict(title="Degree", type="log"),
    yaxis=dict(title="Volume (€)", type="log"),
    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_layout(
    title="Degree vs Volume",
    
    xaxis=dict(
        title="Degree",
        type="log",
        dtick=1,              # only 10^n ticks → 1, 10, 100, 1000
        tickformat=".0f"      # show full numbers instead of scientific notation
    ),
    
    yaxis=dict(
        title="Volume (€)",
        type="log",
        dtick=1,
        # tickformat=".0f"
    ),

    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_xaxes(showgrid=True, gridwidth=1)
fig.update_yaxes(showgrid=True, gridwidth=1)

fig.show()

In [30]:
# TODO: add attribute adjudicante/adjudicatario to hoover in plot and maybe change the color of the point based on it

## <font size=5>**3.6 Exporting It**</font> <a class="anchor" id="3.6"></a>
  
[Back to TOC](#toc)

In [31]:
output_path = '../graphs/gephi_graph01.gexf'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
nx.write_gexf(G, output_path)
print(f'Graph exported to {output_path}')

Graph exported to ../graphs/gephi_graph01.gexf