<font size=10>**NETWORK**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

<font color='#BFD72' size=5>**RESEARCH QUESTION**: </font><font size=5>*Which companies have a dominant position within specific municipalities?*</font> 

**Data**: 
- [*Portal BASE*](https://www.base.gov.pt/Base4/pt/pesquisa/?type=contratos&texto=&adjudicante=&adjudicataria=&tipo=2&tipocontrato=0&cpv=&aqinfo=&desdeprazoexecucao=&ateprazoexecucao=&sel_price=price_11&desdeprecocontrato=&ateprecocontrato=&desdeprecoefectivo=&ateprecoefectivo=&sel_date=date_11&desdedatacontrato=2023-01-01&atedatacontrato=2026-03-31&desdedatapublicacao=&atedatapublicacao=&desdedatafecho=&atedatafecho=&pais=0&distrito=0&concelho=0)

- [*Treated Datasets*](https://dados.gov.pt/pt/datasets/contratos-publicos-portal-base-impic-contratos-de-2012-a-2026/#/resources)

**Group B**
- Beatriz Marques 20231605
- Maria Inês Santos 20231630
- Luís Soeiro 20211536
- Rodrigo Silva 20231602

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a>  
- [1. Imports](#1)  
- [2. Data Integration](#2)  
- [3. First Network](#3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

Failed to read module file 'c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\pydoc_data\topics.py' for module 'pydoc_data.topics': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3128: character maps to <undefined>
Failed to read module file 'c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\re\_casefix.py' for module 're._casefix': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 911: character maps to <undefined>
Failed to read module file 'c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\shlex.py' for module 'shlex': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1482: character maps to <undefined>
Failed to read module file 'c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py' for module 'urllib.parse': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2031: character maps to <undefined>
Failed to read module file 'c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\functools.py' for module 'functools': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Roaming\Python\Python312\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\Rafael\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 308: character maps to <undefined>

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

In [3]:
import subprocess, sys, importlib
import pandas as pd
import plotly.express as px
import re
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

try:
    import openpyxl
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl"])
    importlib.invalidate_caches()
    import openpyxl
    
import os
import shutil

# <font color='#BFD72F' size=6>**2. Data Integration**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [4]:
data = pd.read_csv('../data/preprocessed_data.csv')
# data.head()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 16989 entries, 0 to 16988
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   idcontrato                   16989 non-null  int64
 1   tipoContrato                 16989 non-null  str
 2   tipoFimContrato              16972 non-null  str
 3   CPV                          16989 non-null  str
 4   adjudicante                  16989 non-null  str
 5   adjudicatarios               16989 non-null  str
 6   concorrentes                 14707 non-null  str
 7   precoBaseProcedimento        16989 non-null  float64
 8   precoContratual              16989 non-null  float64
 9   PrecoTotalEfetivo            16989 non-null  float64
 10  LocalExecucao                16989 non-null  str
 11  dataDecisaoAdjudicacao       16989 non-null  str
 12  dataCelebracaoContrato       16989 non-null  str
 13  dataPublicacao               16989 non-null  str
 14  dataFechoContrato            16989 non-null  str
 15  nr_concorrentes              16989 non-null  int64
 16  contribuinte_adjudicante     16962 non-null  float64
 17  contribuinte_adjudicatarios  16583 non-null  float64
 18  country                      16989 non-null  str
 19  district                     14718 non-null  str
 20  city                         14215 non-null  str
 21  cpv_prefix                   16989 non-null  int64
 22  agg_cpv                      16989 non-null  str
 23  adjudicante_clean            16989 non-null  str
 24  adjudicatarios_clean         16989 non-null  str
dtypes: float64(5), int64(3), str(17)
memory usage: 3.2 MB

In [5]:
data["dataPublicacao"] = pd.to_datetime(data["dataPublicacao"], errors='coerce')
data["dataCelebracaoContrato"] = pd.to_datetime(data["dataCelebracaoContrato"], errors='coerce')
data["dataDecisaoAdjudicacao"] = pd.to_datetime(data["dataDecisaoAdjudicacao"], errors='coerce')
data["dataFechoContrato"] = pd.to_datetime(data["dataFechoContrato"], errors='coerce')

# <font color='#BFD72F' size=6>**3. The Network**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

## <font size=5>**3.2 Public entities / Companies network**</font> <a class="anchor" id="3.1"></a>
  
[Back to TOC](#toc)

In [6]:
################
### BEA CODE ###
################

# # If your data is not a DataFrame, fix it
# if isinstance(data, dict):
#     data = pd.DataFrame(data)

# # Create directed graph
# G = nx.DiGraph()

# # Build graph
# for _, row in data.iterrows():
#     adjudicante = row['adjudicante']
#     adjudicatarios = row['adjudicatarios']
#     preco = row['precoContratual']
#     concorrentes = row.get('concorrentes', 0)

#     # Skip missing
#     if pd.isna(adjudicante) or pd.isna(adjudicatarios):
#         continue
#     if pd.isna(preco) or preco <= 0:
#         continue

#     log_price = np.log(preco)

#     # Handle concorrentes safely
#     if pd.isna(concorrentes):
#         concorrentes = 0

#     # Add/update nodes
#     if adjudicante not in G:
#         G.add_node(adjudicante, node_type='adjudicante')
#     else:
#         if G.nodes[adjudicante].get('node_type') == 'adjudicatario':
#             G.nodes[adjudicante]['node_type'] = 'both'

#     if adjudicatarios not in G:
#         G.add_node(adjudicatarios, node_type='adjudicatario')
#     else:
#         if G.nodes[adjudicatarios].get('node_type') == 'adjudicante':
#             G.nodes[adjudicatarios]['node_type'] = 'both'

#     # Add/update edge
#     if G.has_edge(adjudicante, adjudicatarios):
#         edge = G[adjudicante][adjudicatarios]
#         edge['weight'] += log_price
#         edge['contracts'] += 1
#         edge_conc = pd.to_numeric(edge.get('nr_concorrentes', 0), errors='coerce')
#         row_conc = pd.to_numeric(concorrentes, errors='coerce')
#         edge['nr_concorrentes'] = int(0 if pd.isna(edge_conc) else edge_conc) + int(0 if pd.isna(row_conc) else row_conc)
#     else:
#         G.add_edge(
#             adjudicante,
#             adjudicatarios,
#             weight=log_price,
#             contracts=1,
#             nr_concorrentes=concorrentes,
#             city=row.get('city', None)
#         )

In [7]:
def compute_weight(prices, mode="log_sum"):

    prices = np.array(prices)

    if mode == "sum_price":
        return prices.sum()

    elif mode == "avg_price":
        return prices.mean()

    elif mode == "log_sum":
        return np.log(prices).sum()

    elif mode == "log_mean":
        return np.log(prices).mean()

    else:
        raise ValueError(
            f"Unknown mode: {mode}. "
            f"Valid modes: sum_price, avg_price, log_sum, log_mean"
        )

In [8]:
def _ensure_dataframe(data):
    if isinstance(data, pd.DataFrame):
        return data.copy()

    if isinstance(data, dict):
        # CASE 1: dict of lists (valid dataframe)
        try:
            df = pd.DataFrame(data)
            return df
        except Exception:
            pass

        # CASE 2: dict of scalars → wrap into list
        return pd.DataFrame([data])

    raise TypeError(f"Unsupported input type: {type(data)}")

In [9]:
from collections import Counter

def most_common(x):
    if isinstance(x, list) and len(x) > 0:
        return Counter(x).most_common(1)[0][0]
    return "Outros / Não classificado"

In [10]:
def build_contract_network(data, weight_mode="log_sum") -> nx.DiGraph:
    
    df = _ensure_dataframe(data)

    # --- CLEAN COLUMNS ---
    df = df.rename(columns={
        'precoContratual': 'price',
        'adjudicante_clean': 'source',
        'adjudicatarios_clean': 'target'
    })

    # --- BASIC CLEANING ---
    df = df.dropna(subset=['source', 'target', 'price'])
    df = df[df['price'] > 0]

    # --- CONCORRENTES ---
    if 'nr_concorrentes' in df.columns:
        df['concorrentes'] = df['nr_concorrentes']
    else:
        df['concorrentes'] = pd.to_numeric(df.get('concorrentes', 0), errors='coerce').fillna(0)

    # --- EDGE AGGREGATION ---
    edge_df = (
        df.groupby(['source', 'target'], as_index=False)
        .agg(
            total_price=('price', 'sum'),
            nr_concorrentes=('concorrentes', 'sum'),
            contracts=('price', 'count'),
            price_series=('price', list),
            idcontrato=('idcontrato', list),
            tipoContrato=('tipoContrato', list),
            tipoFimContrato=('tipoFimContrato', list),
            CPV=('CPV', list),
            precoBaseProcedimento=('precoBaseProcedimento', list),
            precoContratual=('price', list),
            PrecoTotalEfetivo=('PrecoTotalEfetivo', list),
            dataDecisaoAdjudicacao=('dataDecisaoAdjudicacao', list),
            dataCelebracaoContrato=('dataCelebracaoContrato', list),
            dataPublicacao=('dataPublicacao', list),
            dataFechoContrato=('dataFechoContrato', list),
            nr_concorrentes_list=('nr_concorrentes', list),
            contribuinte_adjudicante=('contribuinte_adjudicante', list),
            contribuinte_adjudicatarios=('contribuinte_adjudicatarios', list),
            city=('city', lambda x: Counter(x).most_common(1)[0][0]),
            cpv_prefix=('cpv_prefix', list),
            agg_cpv=('agg_cpv', lambda x: Counter(x).most_common(1)[0][0])
        )
    )

    # --- WEIGHT STRATEGY ---
    edge_df['weight'] = edge_df['price_series'].apply(
        lambda x: compute_weight(x, mode=weight_mode)
    )

    edge_df = edge_df.drop(columns=['price_series'])

    # --- BUILD GRAPH ---
    G = nx.DiGraph()

    for row in edge_df.itertuples(index=False):
        G.add_edge(
            row.source,
            row.target,
            weight=row.weight,
            total_price=row.total_price,
            nr_concorrentes=row.nr_concorrentes,
            contracts=row.contracts,
            weight_mode=weight_mode,
            idcontrato=row.idcontrato,
            tipoContrato=row.tipoContrato,
            tipoFimContrato=row.tipoFimContrato,
            CPV=row.CPV,
            precoBaseProcedimento=row.precoBaseProcedimento,
            precoContratual=row.precoContratual,
            PrecoTotalEfetivo=row.PrecoTotalEfetivo,
            dataDecisaoAdjudicacao=row.dataDecisaoAdjudicacao,
            dataCelebracaoContrato=row.dataCelebracaoContrato,
            dataPublicacao=row.dataPublicacao,
            dataFechoContrato=row.dataFechoContrato,
            nr_concorrentes_list=row.nr_concorrentes_list,
            contribuinte_adjudicante=row.contribuinte_adjudicante,
            contribuinte_adjudicatarios=row.contribuinte_adjudicatarios,
            city=row.city,
            cpv_prefix=row.cpv_prefix,
            agg_cpv=row.agg_cpv
        )

    # --- NODE TYPES ---
    sources = set(edge_df['source'])
    targets = set(edge_df['target'])

    for node in G.nodes():
        if node in sources and node in targets:
            G.nodes[node]['node_type'] = 'both'
        elif node in sources:
            G.nodes[node]['node_type'] = 'adjudicante'
        else:
            G.nodes[node]['node_type'] = 'adjudicatario'

    return G

# -------------------------------
# VISUAL ATTRIBUTES (UNIFIED)
# -------------------------------
def add_visual_attributes(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):
    conc = np.array([d['nr_concorrentes'] for _, _, d in G.edges(data=True)])
    weight = np.array([d['weight'] for _, _, d in G.edges(data=True)])

    def normalize(x):
        if len(x) == 0:
            return x

        range_ = np.ptp(x)  # max - min safely

        if range_ == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (range_ + 1e-9)

    # --- TRANSFORM ---
    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    # --- ASSIGN ---
    for i, (u, v, d) in enumerate(G.edges(data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G


# -------------------------------
# RUN PIPELINE
# -------------------------------
G = build_contract_network(data, weight_mode="log_sum")

# Linear scaling
G_linear = add_visual_attributes(
    G.copy(),
    thickness_mode="linear",
    size_mode="linear",
    suffix="_linear"
)

# Log scaling
G_log = add_visual_attributes(
    G.copy(),
    thickness_mode="log",
    size_mode="log",
    suffix="_log"
)

In [11]:
def prepare_for_gephi(G):

    G_export = G.copy()

    # --- EDGE ATTRIBUTES ---
    for u, v, d in G_export.edges(data=True):

        for key, value in d.items():

            # convert lists to strings
            if isinstance(value, list):
                d[key] = "; ".join(map(str, value))

            # convert numpy types
            elif isinstance(value, np.generic):
                d[key] = value.item()

    # --- NODE ATTRIBUTES ---
    for n, d in G_export.nodes(data=True):

        for key, value in d.items():

            if isinstance(value, list):
                d[key] = "; ".join(map(str, value))

            elif isinstance(value, np.generic):
                d[key] = value.item()

    return G_export

G_gephi = prepare_for_gephi(G)

nx.write_gexf(G_gephi, "contracts_network.gexf")

## <font size=5>**3.1 City / Companies network**</font> <a class="anchor" id="3.1"></a>

which are the most dominant companies in the country over last 3 years?

[Back to TOC](#toc)

In [12]:
def build_city_contract_network(data) -> nx.MultiDiGraph:

    df = _ensure_dataframe(data)

    # --- CLEAN COLUMNS ---
    df = df.rename(columns={
        'precoContratual': 'price',
        'city': 'source',
        'adjudicatarios_clean': 'target'
    })

    # --- BASIC CLEANING ---
    df = df.dropna(subset=['source', 'target', 'price'])
    df = df[df['price'] > 0]

    # remove empty city names
    df = df[df['source'].astype(str).str.strip() != ""]

    # --- CONCORRENTES ---
    if 'nr_concorrentes' in df.columns:
        df['concorrentes'] = df['nr_concorrentes']
    else:
        df['concorrentes'] = pd.to_numeric(
            df.get('concorrentes', 0),
            errors='coerce'
        ).fillna(0)

    # --- BUILD MULTI GRAPH ---
    # each edge = one contract
    G = nx.MultiDiGraph()

    for row in df.itertuples(index=False):

        weight = compute_weight([row.price], mode="sum_price")

        G.add_edge(
            row.source,
            row.target,

            # unique edge key
            key=row.idcontrato,
            id=str(row.idcontrato),

            # edge attributes
            weight=weight,
            total_price=row.price,
            nr_concorrentes=row.concorrentes,
            contracts=1,

            idcontrato=row.idcontrato,
            tipoContrato=row.tipoContrato,
            tipoFimContrato=row.tipoFimContrato,
            CPV=row.CPV,

            precoBaseProcedimento=row.precoBaseProcedimento,
            precoContratual=row.price,
            PrecoTotalEfetivo=row.PrecoTotalEfetivo,

            dataDecisaoAdjudicacao=row.dataDecisaoAdjudicacao,
            dataCelebracaoContrato=row.dataCelebracaoContrato,
            dataPublicacao=row.dataPublicacao,
            dataFechoContrato=row.dataFechoContrato,

            contribuinte_adjudicante=row.contribuinte_adjudicante,
            contribuinte_adjudicatarios=row.contribuinte_adjudicatarios,

            adjudicante=row.adjudicante_clean,

            city=row.source,

            cpv_prefix=row.cpv_prefix,
            agg_cpv=row.agg_cpv
        )

    # --- NODE TYPES ---
    cities = set(df['source'])
    targets = set(df['target'])

    for node in G.nodes():

        if node in cities and node in targets:
            G.nodes[node]['node_type'] = 'both'

        elif node in cities:
            G.nodes[node]['node_type'] = 'city'

        else:
            G.nodes[node]['node_type'] = 'adjudicatario'

    return G

In [13]:
def add_visual_attributes_multigraph(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):

    conc = np.array([
        d['nr_concorrentes']
        for _, _, _, d in G.edges(keys=True, data=True)
    ])

    weight = np.array([
        d['weight']
        for _, _, _, d in G.edges(keys=True, data=True)
    ])

    def normalize(x):

        if len(x) == 0:
            return x

        range_ = np.ptp(x)

        if range_ == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (range_ + 1e-9)

    # --- TRANSFORM ---
    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    # --- ASSIGN ---
    for i, (u, v, k, d) in enumerate(
        G.edges(keys=True, data=True)
    ):

        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G

G_city = build_city_contract_network(data)

G_city_linear = add_visual_attributes_multigraph(
    G_city.copy(),
    thickness_mode="linear",
    size_mode="linear",
    suffix="_linear"
)

G_city_log = add_visual_attributes_multigraph(
    G_city.copy(),
    thickness_mode="log",
    size_mode="log",
    suffix="_log"
)

In [14]:
from datetime import datetime

def prepare_for_gephi(G):

    G_export = G.copy()

    # --- EDGE ATTRIBUTES ---
    for u, v, k, d in G_export.edges(keys=True, data=True):

        for key, value in d.items():

            # lists -> string
            if isinstance(value, list):
                d[key] = "; ".join(map(str, value))

            # pandas timestamps / datetime
            elif isinstance(value, (pd.Timestamp, datetime)):
                d[key] = value.strftime("%Y-%m-%d")

            # numpy types
            elif isinstance(value, np.generic):
                d[key] = value.item()

    # --- NODE ATTRIBUTES ---
    for n, d in G_export.nodes(data=True):

        for key, value in d.items():

            if isinstance(value, list):
                d[key] = "; ".join(map(str, value))

            elif isinstance(value, (pd.Timestamp, datetime)):
                d[key] = value.strftime("%Y-%m-%d")

            elif isinstance(value, np.generic):
                d[key] = value.item()

    return G_export


G_gephi = prepare_for_gephi(G_city_log)

nx.write_gexf(
    G_gephi,
    "municipalities_network.gexf"
)

In [15]:
from collections import Counter

adj_in_degrees = [
    G_city.in_degree(n)
    for n, d in G_city.nodes(data=True)
    if d["node_type"] == "adjudicatario"
]

adj_degree_counts = Counter(adj_in_degrees)

total_adj_nodes = sum(adj_degree_counts.values())

adj_degree_distribution = (
    pd.DataFrame(
        adj_degree_counts.items(),
        columns=["in_degree", "num_nodes"]
    )
    .sort_values("in_degree")
    .reset_index(drop=True)
)

# add percentage column
adj_degree_distribution["percent"] = (
    adj_degree_distribution["num_nodes"] / total_adj_nodes * 100
).round(1)

adj_degree_distribution

    in_degree  num_nodes  percent
0           1       2581     52.8
1           2        902     18.4
2           3        434      8.9
3           4        236      4.8
4           5        182      3.7
5           6        113      2.3
6           7         87      1.8
7           8         54      1.1
8           9         38      0.8
9          10         35      0.7
10         11         32      0.7
11         12         30      0.6
12         13         25      0.5
13         14         24      0.5
14         15         13      0.3
15         16         15      0.3
16         17          9      0.2
17         18          5      0.1
18         19          8      0.2
19         20          6      0.1
20         22          9      0.2
21         23          5      0.1
22         24          6      0.1
23         25          4      0.1
24         26         10      0.2
25         27          5      0.1
26         28          3      0.1
27         29          3      0.1
28         30          1      0.0
29         31          2      0.0
30         32          1      0.0
31         34          2      0.0
32         35          2      0.0
33         37          1      0.0
34         39          1      0.0
35         42          2      0.0
36         44          2      0.0
37         60          1      0.0
38         70          1      0.0
39         85          1      0.0
40         92          1      0.0

In [16]:
import plotly.express as px

fig = px.bar(
    adj_degree_distribution,
    x="in_degree",
    y="num_nodes",
    title="In-Degree Distribution (Adjudicatarios)",
    labels={
        "in_degree": "In-degree",
        "num_nodes": "Number of nodes"
    }
)

fig.show()

In [17]:
import plotly.express as px

adj_in_degrees = [
    G_city.in_degree(n)
    for n, d in G_city.nodes(data=True)
    if d["node_type"] == "adjudicatario"
]

fig = px.box(
    y=adj_in_degrees,
    points="all",  # shows individual nodes as dots
    title="In-Degree Distribution (Adjudicatarios)",
    labels={"y": "In-degree"}
)

fig.show()

In [18]:
fig = px.box(
    y=adj_in_degrees,
    title="In-Degree Distribution (Log Perspective)",
    labels={"y": "In-degree"}
)

fig.update_yaxes(type="log")

fig.show()

In [19]:
adj_in_degree = {
    n: G_city.in_degree(n)
    for n, d in G_city.nodes(data=True)
    if d["node_type"] == "adjudicatario"
}
df_deg = pd.DataFrame(
    list(adj_in_degree.items()),
    columns=["company", "in_degree"]
)
Q1 = df_deg["in_degree"].quantile(0.25)
Q3 = df_deg["in_degree"].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

outliers = df_deg[df_deg["in_degree"] > upper_bound]

top_outliers = (
    outliers.sort_values("in_degree", ascending=False)
    .head(10)
    .reset_index(drop=True)
)



fig = px.bar(
    top_outliers,
    x="in_degree",
    y="company",
    orientation="h",
    title="Top Dominant Adjudicatarios (Outliers by In-Degree)",
    labels={
        "in_degree": "Number of Cities Connected",
        "company": "Company"
    }
)

fig.update_layout(yaxis={"categoryorder": "total ascending"})
fig.show()

> Geographical constraint is a major limitation in public procurement competition

> There are a few companies that are able to overcome this limitation

____

## <font size=5>**3.1 CPV / Companies network**</font> <a class="anchor" id="3.1"></a>
  
[Back to TOC](#toc)

In [20]:
def build_cpv_contract_network(data) -> nx.MultiDiGraph:
    # Ensure dataframe (replaced your custom function with standard pandas)
    df = data.copy() if isinstance(data, pd.DataFrame) else pd.DataFrame(data)

    # Rename to set CPV as source and Company (adjudicatario) as target
    df = df.rename(columns={
        'precoContratual': 'price',
        'agg_cpv': 'source',
        'adjudicatarios_clean': 'target'
    })

    # Clean missing and invalid data
    df = df.dropna(subset=['source', 'target', 'price'])
    df = df[df['price'] > 0]

    df["source"] = df["source"].astype(str).str.strip()
    df["target"] = df["target"].astype(str).str.strip()
    df = df[(df["source"] != "") & (df["target"] != "")]

    G = nx.MultiDiGraph()

    # Build Edges
    for row in df.itertuples(index=False):
        G.add_edge(
            row.source,
            row.target,
            key=str(row.idcontrato),
            
            # Numeric/Weights
            weight=row.price,
            total_price=row.price,
            nr_concorrentes=getattr(row, "nr_concorrentes", 0),
            contracts=1,
            precoBaseProcedimento=row.precoBaseProcedimento,
            precoContratual=row.price,
            PrecoTotalEfetivo=row.PrecoTotalEfetivo,
            
            # Identifiers & Categories
            idcontrato=row.idcontrato,
            tipoContrato=row.tipoContrato,
            tipoFimContrato=row.tipoFimContrato,
            CPV=row.CPV,
            cpv_prefix=row.cpv_prefix,
            agg_cpv=row.source, # We renamed agg_cpv to 'source' above
            
            # Dates
            dataDecisaoAdjudicacao=row.dataDecisaoAdjudicacao,
            dataCelebracaoContrato=row.dataCelebracaoContrato,
            dataPublicacao=row.dataPublicacao,
            dataFechoContrato=row.dataFechoContrato,
            
            # Entities
            contribuinte_adjudicante=row.contribuinte_adjudicante,
            contribuinte_adjudicatarios=row.contribuinte_adjudicatarios,
            adjudicante=getattr(row, "adjudicante_clean", "")
        )

    # Assign Node Types (Optimized)
    # Extracting the set outside the loop drastically improves performance
    cpv_nodes = set(df["source"])
    
    for n in G.nodes():
        if n in cpv_nodes:
            G.nodes[n]["node_type"] = "cpv"
            G.nodes[n]["bipartite"] = 0 # Standard NetworkX bipartite flag
        else:
            G.nodes[n]["node_type"] = "adjudicatario"
            G.nodes[n]["bipartite"] = 1

    return G

In [21]:
def add_visual_attributes_multigraph(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):
    conc = np.array([
        d.get('nr_concorrentes', 0)
        for _, _, _, d in G.edges(keys=True, data=True)
    ])

    weight = np.array([
        d.get('weight', 0)
        for _, _, _, d in G.edges(keys=True, data=True)
    ])

    def normalize(x):
        if len(x) == 0:
            return x
        range_ = np.ptp(x)
        if range_ == 0:
            return np.zeros_like(x)
        return (x - np.min(x)) / (range_ + 1e-9)

    # --- TRANSFORM ---
    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    # --- ASSIGN ---
    for i, (u, v, k, d) in enumerate(G.edges(keys=True, data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G

In [22]:
def prepare_for_gephi(G):
    G_export = G.copy()

    # ---------------------------
    # EDGE ATTRIBUTES
    # ---------------------------
    for u, v, k, d in G_export.edges(keys=True, data=True):
        keys_to_convert = list(d.keys())

        for key in keys_to_convert:
            value = d[key]

            if isinstance(value, list) or isinstance(value, set):
                d[key] = "; ".join(map(str, value))
            elif isinstance(value, (pd.Timestamp, datetime)):
                d[key] = value.strftime("%Y-%m-%d")
            elif isinstance(value, np.generic):
                d[key] = value.item()
            elif pd.isna(value) or value is None: # Catches pandas NaN types safely
                d[key] = ""

        # Gephi requirement for MultiDiGraphs
        if "id" not in d:
            d["id"] = str(k)

    # ---------------------------
    # NODE ATTRIBUTES
    # ---------------------------
    for n, d in G_export.nodes(data=True):
        keys_to_convert = list(d.keys())

        for key in keys_to_convert:
            value = d[key]

            if isinstance(value, list) or isinstance(value, set):
                d[key] = "; ".join(map(str, value))
            elif isinstance(value, (pd.Timestamp, datetime)):
                d[key] = value.strftime("%Y-%m-%d")
            elif isinstance(value, np.generic):
                d[key] = value.item()
            elif pd.isna(value) or value is None:
                d[key] = ""

    return G_export

In [23]:
# 1. Build the network
G_cpv = build_cpv_contract_network(data)

# 2. Add visual scaling (Linear)
G_cpv_linear = add_visual_attributes_multigraph(
    G_cpv.copy(),
    thickness_mode="linear",
    size_mode="linear",
    suffix="_linear"
)

# 3. Add visual scaling (Logarithmic)
G_cpv_log = add_visual_attributes_multigraph(
    G_cpv.copy(),
    thickness_mode="log",
    size_mode="log",
    suffix="_log"
)

# 4. Prepare for Gephi Export
G_gephi = prepare_for_gephi(G_cpv)

# 5. Export to GEXF
nx.write_gexf(
    G_gephi,
    "cpv_network.gexf",
    version="1.2draft"
)

In [24]:
from collections import Counter
import pandas as pd

# --- compute in-degrees ---
adj_in_degrees = [
    G_cpv.in_degree(n)
    for n, d in G_cpv.nodes(data=True)
    if d["node_type"] == "adjudicatario"
]

# --- distribution ---
adj_degree_counts = Counter(adj_in_degrees)

adj_degree_distribution = (
    pd.DataFrame(
        adj_degree_counts.items(),
        columns=["in_degree", "num_nodes"]
    )
    .sort_values("in_degree")
    .reset_index(drop=True)
)

# --- correct total (IMPORTANT FIX) ---
total_nodes = len(adj_in_degrees)

# --- percentage ---
adj_degree_distribution["percent"] = (
    adj_degree_distribution["num_nodes"] / total_nodes * 100
).round(1)

adj_degree_distribution

    in_degree  num_nodes  percent
0           1       2738     51.3
1           2        957     17.9
2           3        484      9.1
3           4        270      5.1
4           5        203      3.8
5           6        139      2.6
6           7         98      1.8
7           8         61      1.1
8           9         49      0.9
9          10         38      0.7
10         11         50      0.9
11         12         34      0.6
12         13         28      0.5
13         14         21      0.4
14         15         20      0.4
15         16         17      0.3
16         17         14      0.3
17         18          6      0.1
18         19         15      0.3
19         20          6      0.1
20         21          6      0.1
21         22          7      0.1
22         23          3      0.1
23         24          7      0.1
24         25          7      0.1
25         26          7      0.1
26         27          6      0.1
27         28          8      0.1
28         29          4      0.1
29         30          4      0.1
30         31          1      0.0
31         32          2      0.0
32         33          3      0.1
33         34          1      0.0
34         35          1      0.0
35         36          2      0.0
36         37          2      0.0
37         38          1      0.0
38         39          2      0.0
39         40          1      0.0
40         41          1      0.0
41         42          3      0.1
42         44          1      0.0
43         45          1      0.0
44         46          1      0.0
45         50          1      0.0
46         51          1      0.0
47         52          1      0.0
48         73          1      0.0
49         76          1      0.0
50         87          1      0.0
51        118          1      0.0
52        152          1      0.0

In [25]:
import plotly.express as px

fig = px.bar(
    adj_degree_distribution,
    x="in_degree",
    y="num_nodes",
    title="In-Degree Distribution (Adjudicatarios)",
    labels={
        "in_degree": "In-degree",
        "num_nodes": "Number of nodes"
    }
)

fig.show()

In [26]:
import plotly.express as px

adj_in_degrees = [
    G_cpv.in_degree(n)
    for n, d in G_cpv.nodes(data=True)
    if d["node_type"] == "adjudicatario"
]

fig = px.box(
    y=adj_in_degrees,
    points="all",  # shows individual nodes as dots
    title="In-Degree Distribution (Adjudicatarios)",
    labels={"y": "In-degree"}
)

fig.show()

In [27]:
fig = px.box(
    y=adj_in_degrees,
    title="In-Degree Distribution (Log Perspective)",
    labels={"y": "In-degree"}
)

fig.update_yaxes(type="log")

fig.show()

In [28]:
from collections import Counter

specialization = {}

for company, d in G_cpv.nodes(data=True):

    if d["node_type"] != "adjudicatario":
        continue

    # all CPVs connected to company
    cpvs = [
        u
        for u, v, k in G_cpv.in_edges(company, keys=True)
    ]

    if len(cpvs) == 0:
        continue

    counts = Counter(cpvs)

    total = sum(counts.values())

    proportions = [
        c / total
        for c in counts.values()
    ]

    H = sum(p**2 for p in proportions)

    specialization[company] = H

df_spec = pd.DataFrame(
    specialization.items(),
    columns=["company", "specialization_index"]
)

fig = px.histogram(
    df_spec,
    x="specialization_index",
    nbins=30,
    title="Company Specialization Index"
)

fig.show()

pi = proportion of contracts in CPV i

<br>

| H value  | Meaning                         |
| -------- | ------------------------------- |
| ~1       | almost all contracts in one CPV |
| 0.5      | concentrated                    |
| 0.1      | diversified                     |
| very low | broad generalist                |

<br>

> Companies do not win contracts outside of their cpv area

In [28]:
adj_in_degree = {
    n: G_cpv.in_degree(n)
    for n, d in G_cpv.nodes(data=True)
    if d["node_type"] == "adjudicatario"
}
df_deg = pd.DataFrame(
    list(adj_in_degree.items()),
    columns=["company", "in_degree"]
)
Q1 = df_deg["in_degree"].quantile(0.25)
Q3 = df_deg["in_degree"].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

outliers = df_deg[df_deg["in_degree"] > upper_bound]

top_outliers = (
    outliers.sort_values("in_degree", ascending=False)
    .head(10)
    .reset_index(drop=True)
)



fig = px.bar(
    top_outliers,
    x="in_degree",
    y="company",
    orientation="h",
    title="Top Dominant Adjudicatarios (Outliers by In-Degree)",
    labels={
        "in_degree": "Number of Cities Connected",
        "company": "Company"
    }
)

fig.update_layout(yaxis={"categoryorder": "total ascending"})
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# -----------------------------------
# AVAILABLE CPV AREAS
# -----------------------------------
cpv_options = sorted([
    n for n, d in G_cpv.nodes(data=True)
    if d["node_type"] == "cpv"
])

# -----------------------------------
# INTERACTIVE PLOT FUNCTION
# -----------------------------------
def plot_cpv_dominance(selected_cpv):

    # -----------------------------------
    # CONTRACT COUNT PER COMPANY
    # (inside selected CPV only)
    # -----------------------------------
    contracts_per_company = {}

    for _, company, k, d in G_cpv.edges(
        selected_cpv,
        keys=True,
        data=True
    ):

        contracts_per_company[company] = (
            contracts_per_company.get(company, 0) + 1
        )

    # -----------------------------------
    # DATAFRAME
    # -----------------------------------
    df_deg = pd.DataFrame(
        list(contracts_per_company.items()),
        columns=["company", "contracts"]
    )

    if df_deg.empty:
        print("No companies found for this CPV.")
        return

    # -----------------------------------
    # OUTLIER DETECTION
    # -----------------------------------
    Q1 = df_deg["contracts"].quantile(0.25)
    Q3 = df_deg["contracts"].quantile(0.75)
    IQR = Q3 - Q1

    upper_bound = Q3 + 1.5 * IQR

    outliers = df_deg[
        df_deg["contracts"] > upper_bound
    ]

    # fallback if no outliers
    if outliers.empty:
        outliers = df_deg

    top_outliers = (
        outliers
        .sort_values("contracts", ascending=False)
        .head(10)
    )

    # -----------------------------------
    # PLOT
    # -----------------------------------
    fig = px.bar(
        top_outliers.sort_values("contracts"),
        x="contracts",
        y="company",
        orientation="h",
        title=f"Top Dominant Companies — {selected_cpv}",
        labels={
            "contracts": "Number of Contracts",
            "company": "Company"
        }
    )

    fig.update_layout(
        height=600,
        yaxis={"categoryorder": "total ascending"}
    )

    fig.show()

# -----------------------------------
# DROPDOWN SELECTION
# -----------------------------------
dropdown = widgets.Dropdown(
    options=cpv_options,
    description="CPV:",
    layout=widgets.Layout(width="70%")
)

interactive_plot = widgets.interactive_output(
    plot_cpv_dominance,
    {"selected_cpv": dropdown}
)

display(dropdown, interactive_plot)

Dropdown(description='CPV:', layout=Layout(width='70%'), options=('Agricultura & recursos naturais', 'Ambiente…

Output()

In [29]:
from collections import Counter
import numpy as np
import pandas as pd
import plotly.express as px

# ----------------------------------------
# CITY DIVERSITY
# ----------------------------------------
# number of unique cities per company

city_diversity = {}

for n, d in G_city.nodes(data=True):

    if d["node_type"] != "adjudicatario":
        continue

    cities = set(G_city.predecessors(n))

    city_diversity[n] = len(cities)

# ----------------------------------------
# CPV ENTROPY
# ----------------------------------------

cpv_entropy = {}

for n, d in G_cpv.nodes(data=True):

    if d["node_type"] != "adjudicatario":
        continue

    cpvs = [
        u
        for u, v, k in G_cpv.in_edges(n, keys=True)
    ]

    if len(cpvs) == 0:
        continue

    counts = Counter(cpvs)

    total = sum(counts.values())

    proportions = [
        c / total
        for c in counts.values()
    ]

    H = -sum(p * np.log(p) for p in proportions)

    # normalized entropy
    if len(counts) > 1:
        H_norm = H / np.log(len(counts))
    else:
        H_norm = 0

    cpv_entropy[n] = H_norm

# ----------------------------------------
# MERGE METRICS
# ----------------------------------------

common_companies = (
    set(city_diversity.keys())
    & set(cpv_entropy.keys())
)

df_compare = pd.DataFrame({
    "company": list(common_companies),
    "city_diversity": [
        city_diversity[c]
        for c in common_companies
    ],
    "cpv_entropy": [
        cpv_entropy[c]
        for c in common_companies
    ]
})

# optional: log scale for city diversity
df_compare["log_city_diversity"] = np.log1p(
    df_compare["city_diversity"]
)

# ----------------------------------------
# SCATTER PLOT
# ----------------------------------------

fig = px.scatter(
    df_compare,
    x="city_diversity",
    y="cpv_entropy",
    hover_data=["company"],
    title="CPV Entropy vs City Diversity",
    labels={
        "city_diversity": "Number of Cities",
        "cpv_entropy": "Normalized CPV Entropy"
    }
)

fig.update_layout(
    height=700
)

fig.show()

---

In [40]:
weight_modes = ["sum_price", "avg_price", "log_sum", "log_mean"]

graphs = {
    mode: build_contract_network(data, weight_mode=mode)
    for mode in weight_modes
}

In [41]:
for mode, G in graphs.items():
    volume = {
        node: sum(d["total_price"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    degree = dict(G.degree())

    corr = pd.Series(degree).corr(pd.Series(volume))

    print(f"{mode:10s} → degree-volume correlation: {corr:.3f}")

sum_price  → degree-volume correlation: 0.618
avg_price  → degree-volume correlation: 0.618
log_sum    → degree-volume correlation: 0.618
log_mean   → degree-volume correlation: 0.618

In [42]:
for mode, G in graphs.items():
    top = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:3]

    print(f"\nMode: {mode}")
    for node, deg in top:
        print(f"  {node}: {deg}")

Mode: sum_price
  guarda nacional republicana: 62
  secretaria geral do ministerio da administracao interna: 26
  casa pia de lisboa i p: 18

Mode: avg_price
  guarda nacional republicana: 62
  secretaria geral do ministerio da administracao interna: 26
  casa pia de lisboa i p: 18

Mode: log_sum
  guarda nacional republicana: 62
  secretaria geral do ministerio da administracao interna: 26
  casa pia de lisboa i p: 18

Mode: log_mean
  guarda nacional republicana: 62
  secretaria geral do ministerio da administracao interna: 26
  casa pia de lisboa i p: 18

In [43]:
rankings = {}

for mode, G in graphs.items():

    weighted_degree = {
        node: sum(d["weight"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    # convert to ranking (higher = better rank)
    ranked = pd.Series(weighted_degree).rank(ascending=False)

    rankings[mode] = ranked

sum_price → total contract value emphasis

avg_price → typical contract size

log_sum → interaction-frequency + heavy-tail compression

log_mean → normalized interaction intensity

In [44]:
rank_df = pd.DataFrame(rankings)
rank_df.head()

,sum_price,avg_price,log_sum,log_mean
acss administracao central do sistema de saude ip,95.0,93.0,61.0,57.0
claranet ii solutions,347.0,347.0,347.0,347.0
primavera business software solutions,347.0,347.0,347.0,347.0
timestamp sistemas de informacao,347.0,347.0,347.0,347.0
adene agencia para a energia,84.0,82.0,79.0,77.0

In [45]:
rank_df["rank_std"] = rank_df.std(axis=1)
rank_df["rank_mean"] = rank_df.mean(axis=1)

In [46]:
# Structurally important regardless of weight strategy

stable_nodes = rank_df.sort_values("rank_std").head(10)
stable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
crc car rental company,347.0,347.0,347.0,347.0,0.0,277.6
claranet ii solutions,347.0,347.0,347.0,347.0,0.0,277.6
primavera business software solutions,347.0,347.0,347.0,347.0,0.0,277.6
timestamp sistemas de informacao,347.0,347.0,347.0,347.0,0.0,277.6
nova expressao planeamento de meios e publicidade,347.0,347.0,347.0,347.0,0.0,277.6
digiberia information technologies,347.0,347.0,347.0,347.0,0.0,277.6
paginas aos blocos,347.0,347.0,347.0,347.0,0.0,277.6
administracao central do sistema de saude i p,126.0,126.0,126.0,126.0,0.0,100.8
claranet portugal,347.0,347.0,347.0,347.0,0.0,277.6
onretrieval group,347.0,347.0,347.0,347.0,0.0,277.6

<font color ='red'>These nodes:
- have identical ranks across ALL weighting schemes
- are structurally invariant in your network

They are topological anchors, not sensitive to how we measure money or interaction.

We see identical rank values like 5594.5, this suggests many tied ranks. So they are stable and saturated centrality nodes. This means that ranking resolution is too coarse and many nodes are indistinguishable under this metric.

In [47]:
# Importende depends heavily on how we measure importance

unstable_nodes = rank_df.sort_values("rank_std", ascending=False).head(10)
unstable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
area metropolitana de lisboa,53.0,117.0,10.0,122.0,53.792812,71.158562
instituto do emprego e formacao profissional ip,8.0,7.0,84.0,83.0,43.882419,45.176484
instituto nacional de saude doutor ricardo jorge i p,88.0,86.0,27.0,22.0,36.151302,51.830260
such | servico de utilizacao comum dos hospitais,62.0,106.0,23.0,78.0,34.654245,60.730849
municipio da lourinha,105.0,109.0,45.0,56.0,32.968419,69.593684
agencia nacional para a qualificacao e o ensino profissional i p,75.0,70.0,16.0,18.0,32.118271,42.223654
instituto superior de economia e gestao,66.0,63.0,11.0,8.0,31.801467,35.960293
cascais dinamica gestao de economia turismo e empreendorismo e m,30.0,29.0,85.0,84.0,31.759513,51.951903
adp valor servicos ambientais,34.0,32.0,86.0,85.0,30.324632,53.464926
faculdade de letras da universidade de lisboa,94.0,92.0,43.0,39.0,30.077677,59.615535

<font color='red'>These nodes change position dramatically depending on weighting scheme. Their importance depends on what we consider "importance". 

Pattern:
1. Mixed contract sizes
some large contracts
many small ones
2. irregular interaction structure
sporadic procurement behavior
3. heterogeneity in edges

sum_price -> rewards big contracts
avg_price -> smooths variability
log_sum -> rewards frequency
log_mean -> penalizes extreme dispersion

In [48]:
# # Visualize the graph
# # Layout (can take time for big graphs)
# pos = nx.spring_layout(G, k=0.15, iterations=20, seed=42)

# # Extract edge attributes
# weights = [G[u][v]['weight'] for u, v in G.edges()]
# widths = [G[u][v]['nr_concorrentes'] for u, v in G.edges()]

# # Avoid division by zero
# if len(widths) > 0 and max(widths) > 0:
#     widths = [w / max(widths) * 5 for w in widths]
# else:
#     widths = [1 for _ in widths]

# if len(weights) > 0 and max(weights) > 0:
#     weights_norm = [w / max(weights) for w in weights]
# else:
#     weights_norm = weights

# # Draw
# plt.figure(figsize=(12, 10))

# nx.draw_networkx_nodes(G, pos, node_size=50)

# nx.draw_networkx_edges(
#     G,
#     pos,
#     width=widths,                 # thickness = concorrentes
#     edge_color=weights_norm,      # color = log(price)
#     edge_cmap=plt.cm.Blues
# )

# plt.title("Network: Adjudicante → Adjudicatário")
# plt.axis('off')
# plt.show()

## <font size=5>**3.2 General Insights**</font> <a class="anchor" id="3.2"></a>
  
[Back to TOC](#toc)

In [49]:
# Number of nodes
print(f"Number of nodes: {G.number_of_nodes()}")
print(f"\t-> Number of adjudicantes: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both']) / G.number_of_nodes() * 100:.2f}%")
print(f"\t-> Number of adjudicatarios: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both']) / G.number_of_nodes() * 100:.2f}%")

# Number of edges
print(f"\nNumber of edges: {G.number_of_edges()}")

Number of nodes: 564
	-> Number of adjudicantes: 129, i.e., 22.87%
	-> Number of adjudicatarios: 436, i.e., 77.30%

Number of edges: 566

## <font size=5>**3.3 Rank All Entities By Degree (Number of Contracts)**</font> <a class="anchor" id="3.3"></a>
  
[Back to TOC](#toc)

In [50]:
def entity_type(node):
    node_type = G.nodes[node].get("node_type", "unknown")
    if node_type == "both":
        return "adjudicante and adjudicatario"
    return node_type

# Highest and lowest in-degree
highest_in = max(G.in_degree(), key=lambda x: x[1])
lowest_in = min(G.in_degree(), key=lambda x: x[1])

# Highest and lowest out-degree
highest_out = max(G.out_degree(), key=lambda x: x[1])
lowest_out = min(G.out_degree(), key=lambda x: x[1])

# Average in-degree and out-degree
in_degrees = [d for _, d in G.in_degree()]
out_degrees = [d for _, d in G.out_degree()]

avg_in = sum(in_degrees) / len(in_degrees)
avg_out = sum(out_degrees) / len(out_degrees)

print(f"Highest in-degree: {highest_in} -> {entity_type(highest_in[0])}")
print(f"Lowest out-degree: {lowest_out} -> {entity_type(lowest_out[0])}")

print(f"\nHighest out-degree: {highest_out} -> {entity_type(highest_out[0])}")
print(f"Lowest in-degree: {lowest_in} -> {entity_type(lowest_in[0])}")

print(f"\nAverage in-degree: {avg_in:.2f}")
print(f"Average out-degree: {avg_out:.2f}")

Highest in-degree: ('claranet ii solutions', 14) -> adjudicatario
Lowest out-degree: ('claranet ii solutions', 0) -> adjudicatario

Highest out-degree: ('guarda nacional republicana', 62) -> adjudicante
Lowest in-degree: ('acss administracao central do sistema de saude ip', 0) -> adjudicante

Average in-degree: 1.00
Average out-degree: 1.00

The average in-degree and average out-degree are the same because, in any directed graph, the sum of all in-degrees equals the sum of all out-degrees, and both are equal to the number of edges.

Therefore:
  $$avg_{in}  = |E| / |V|$$
  $$avg_{out} = |E| / |V|$$

so they must be identical.

In [51]:
# Top 5 Degree Enitities
top5 = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:5]
print("Top 5 most connected entities:")
for entity, deg in top5:
    print(f"  {entity}: {deg}")

Top 5 most connected entities:
  guarda nacional republicana: 62
  secretaria geral do ministerio da administracao interna: 26
  casa pia de lisboa i p: 18
  servicos municipalizados de agua e saneamento de sintra: 18
  instituto nacional de medicina legal e ciencias forenses i p: 17

In [52]:
# Degree-1 entities
deg1 = sorted(
    [(node, degree) for node, degree in G.degree() if degree == 1],
    key=lambda x: x[0]
)

print(f"Degree-1 entities: {len(deg1)}")
for i, (entity, degree) in enumerate(deg1[:20], start=1):
    node_type = G.nodes[entity].get("node_type", "unknown")
    if node_type == "both":
        node_type = "adjudicante and adjudicatario"
    print(f"{i:>3}. {entity} (degree={degree}, type={node_type})")

if len(deg1) > 20:
    print(f"... and {len(deg1) - 20} more")

Degree-1 entities: 407
  1. 1 meo servicos de comunicacoes e multimedia (degree=1, type=adjudicatario)
  2. 2wayview (degree=1, type=adjudicatario)
  3. a barreira (degree=1, type=adjudicatario)
  4. a do carmo importacao exportacao e comercio (degree=1, type=adjudicatario)
  5. a gouv reparacao e manutencao de veiculos (degree=1, type=adjudicatario)
  6. a salgado distribuicao (degree=1, type=adjudicatario)
  7. abrancongelados produtos alimentares (degree=1, type=adjudicatario)
  8. adelaide ferreira (degree=1, type=adjudicatario)
  9. adelino pedro (degree=1, type=adjudicatario)
 10. administracao central do sistema de saude i p (degree=1, type=adjudicante)
 11. adp valor servicos ambientais (degree=1, type=adjudicante)
 12. ageas portugal companhia de seguros (degree=1, type=adjudicatario)
 13. agencia para o investimento e comercio externo de portugal e p e (degree=1, type=adjudicante)
 14. agripublic (degree=1, type=adjudicatario)
 15. agrupamento de escolas jose afonso loures (degree=1, type=adjudicante)
 16. aguas do tejo atlantico (degree=1, type=adjudicante)
 17. aguas do vale do tejo (degree=1, type=adjudicante)
 18. alacer mobiliario de escritorio (degree=1, type=adjudicatario)
 19. alexandre martos martinez (degree=1, type=adjudicatario)
 20. alive portugal (degree=1, type=adjudicatario)
... and 387 more

In [53]:
# All contract pairs with amounts
print("Contracts with their amounts:")
for u, v, data in G.edges(data=True):
    print(f"  {u} -- {v} : €{data['weight']:,}")

Contracts with their amounts:
  acss administracao central do sistema de saude ip -- claranet ii solutions : €8.433811582477187
  acss administracao central do sistema de saude ip -- primavera business software solutions : €8.990615968707628
  acss administracao central do sistema de saude ip -- timestamp sistemas de informacao : €11.34954392823967
  adene agencia para a energia -- digiberia information technologies : €11.923709734555993
  adene agencia para a energia -- paginas aos blocos : €8.160932447399158
  administracao central do sistema de saude i p -- claranet portugal : €6.763908002983978
  adp valor servicos ambientais -- hccm consulting : €13.283143542126385
  agencia nacional para a qualificacao e o ensino profissional i p -- chief security officers : €9.193273585525748
  agencia nacional para a qualificacao e o ensino profissional i p -- datagate desenvolvimento solucoes informaticas : €7.461640392208575
  agencia nacional para a qualificacao e o ensino profissional i p -- edni empresa distribiudora de material informatico : €7.622345896835734
  agencia nacional para a qualificacao e o ensino profissional i p -- exitus solucoes tecnologicas : €7.595889917718538
  agencia nacional para a qualificacao e o ensino profissional i p -- idoneos : €10.882753083571671
  agencia nacional para a qualificacao e o ensino profissional i p -- inetum espana sucursal em portugal : €11.232409653423147
  agencia nacional para a qualificacao e o ensino profissional i p -- jelskey jose gomes unipessoal limitada : €9.52806656577634
  agencia nacional para a qualificacao e o ensino profissional i p -- knowledge inside : €10.231553123382788
  agencia nacional para a qualificacao e o ensino profissional i p -- ph informatica e microssistemas : €9.141836666542293
  agencia nacional para a qualificacao e o ensino profissional i p -- ris 2048 sistemas informaticos e comunicacoes : €7.769391283704896
  agencia para a modernizacao administrativa i p -- apcer : €10.187349838885044
  agencia para a modernizacao administrativa i p -- axianseu digital solutions : €10.688950890033425
  agencia para a modernizacao administrativa i p -- base2 : €9.733937409075018
  agencia para a modernizacao administrativa i p -- claranet ii solutions : €10.606251661480803
  agencia para a modernizacao administrativa i p -- claranet portugal : €12.350357734342314
  agencia para a modernizacao administrativa i p -- digiberia information technologies : €9.631769478969021
  agencia para a modernizacao administrativa i p -- glfv : €10.808138807753252
  agencia para a modernizacao administrativa i p -- papelprint : €5.298011616834201
  agencia para a modernizacao administrativa i p -- pse produtos e servicos de estatistica : €7.773173680482536
  agencia para a modernizacao administrativa i p -- shield domain : €12.201153667168628
  agencia para a modernizacao administrativa i p -- sigmadetalhe : €10.505341474649683
  agencia para a modernizacao administrativa i p -- timestamp sistemas de informacao : €11.183422983081186
  agencia para a modernizacao administrativa i p -- xpand solutions informatica e novas tecnologias : €10.423931982957537
  agencia para a reforma tecnologica do estado ip -- multimac hito innovation : €11.33015376687788
  agencia para a reforma tecnologica do estado ip -- pdm e fc projecto desenvolvimento manutencao formacao e consultadoria : €11.765394781666265
  agencia para a reforma tecnologica do estado ip -- portfolio portugal : €9.920211917428539
  agencia para o investimento e comercio externo de portugal e p e -- movegreat transports : €12.096536758461866
  agrupamento de escolas jose afonso loures -- beltrao coelho sistemas de escritorio : €13.064400840343946
  aguas do tejo atlantico -- concessus sociedade de apetrechamento tecnico e cientifico : €8.496173824192162
  aguas do vale do tejo -- riportico engenharia : €12.939281531663966
  area metropolitana de lisboa -- cpcecho : €9.920744152396297
  arte agencia para a reforma tecnologica do estado -- multimac hito innovation : €13.128303817996628
  associacao de promocao da regiao autonoma da madeira -- diretriz duradoura : €12.047721489374798
  autoridade da mobilidade e dos transportes -- ambisig ambiente e sistemas de informacao geografica : €10.676601437881464
  autoridade da mobilidade e dos transportes -- base2 : €10.19421498317387
  autoridade nacional de comunicacoes -- hewlett packard : €12.014054871993325
  autoridade nacional de comunicacoes -- inetum tech portugal : €9.260031082912578
  autoridade nacional de comunicacoes -- prosonic produtos de imagem e comunicacao : €11.320553572322773
  autoridade nacional de seguranca rodoviaria -- advanced resources : €10.626739502775123
  autoridade nacional de seguranca rodoviaria -- nova expressao planeamento de media e publicidade : €11.621975291077785
  autoridade para as condicoes do trabalho -- claranet ii solutions : €11.843068968057189
  autoridade para as condicoes do trabalho -- devscope : €9.5396153417263
  autoridade para as condicoes do trabalho -- i p m informatica papelaria mobiliario : €9.58023218699976
  autoridade para as condicoes do trabalho -- oramix sistemas de informacao : €12.254743754993829
  autoridade para as condicoes do trabalho -- papelprint : €9.837162903888759
  autoridade para as condicoes do trabalho -- sebasi sistemas de informacao : €11.218554404367652
  autoridade tributaria e aduaneira -- hccm consulting : €13.368441900001034
  autoridade tributaria e aduaneira -- hewlett packard portugal : €12.095141084822892
  autoridade tributaria e aduaneira -- homeostase 2 intelligence : €13.075271769870477
  casa pia de lisboa i p -- adelaide ferreira : €7.868525946943292
  casa pia de lisboa i p -- bricantel comercio de material electrico de braganca : €9.314206571699875
  casa pia de lisboa i p -- casobra : €10.140918944783984
  casa pia de lisboa i p -- crc car rental company : €10.600377719374908
  casa pia de lisboa i p -- didatiarea : €6.814103722900682
  casa pia de lisboa i p -- escrinova mobiliario e equipamentos de escritorio : €7.600902459542082
  casa pia de lisboa i p -- inetum espana sucursal em portugal : €11.570409348061537
  casa pia de lisboa i p -- izumix : €11.56171562913966
  casa pia de lisboa i p -- ohmtecnica representacoes de marcas : €7.507690077819904
  casa pia de lisboa i p -- papelprint : €10.98164727274205
  casa pia de lisboa i p -- planetavertical : €9.475665278385158
  casa pia de lisboa i p -- strongplan : €12.567237494741757
  casa pia de lisboa i p -- topgim ibrafer material desportivo e fitness : €8.911014776029266
  casa pia de lisboa i p -- tronicom : €10.45965138933788
  casa pia de lisboa i p -- valpi rent : €9.330245593875887
  casa pia de lisboa i p -- viana musica artigos musicais : €9.71734419315976
  casa pia de lisboa i p -- vitor escada comercio e servicos : €8.986281401793944
  casa pia de lisboa i p -- vitor vaz : €9.44608657521237
  casa pia de lisboa ip -- americana papelaria : €7.839746116660362
  casa pia de lisboa ip -- papelprint : €7.278856659662342
  cascais dinamica gestao de economia turismo e empreendorismo e m -- sma seguranca privada : €13.513618939734075
  cascais proxima gestao de mobilidade espacos urbanos e energias e m -- carclasse comercio de automoveis : €10.760597120307324
  cascais proxima gestao de mobilidade espacos urbanos e energias e m -- prf gas tecnologia e construcao : €11.512925464970229
  centro de emprego de matosinhos -- sebasi sistemas de informacao : €12.264299099922814
  centro de emprego e formacao profissional de leiria -- boldint by devoteam : €10.896739325546411
  centro de emprego e formacao profissional de santarem -- papelprint : €8.094256337396033
  centro de emprego e formacao profissional de santarem -- tcsi digiberia tecnologia de inormacao : €8.914101796841281
  centro de emprego e formacao profissional de setubal -- wws consultoria informatica : €13.065499861254253
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim -- caravela companhia de seguros : €9.363213378783923
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim -- generali seguros : €10.887167146201948
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim -- lusitania companhia de seguros : €10.892675523922948
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim -- zoller iberica u : €10.035315495113096
  centro de formacao profissional da reparacao automovel -- casobra : €9.987415012471414
  centro de formacao profissional da reparacao automovel -- intermaco comercio e representacoes maquinas ferramentas : €9.795902341856191
  centro de formacao profissional da reparacao automovel -- modutronic : €8.850804195756417
  centro de formacao profissional das pescas e do mar for mar -- alacer mobiliario de escritorio : €10.169767218727474
  centro de formacao profissional das pescas e do mar for mar -- claranet portugal : €10.963257136596724
  centro de formacao profissional das pescas e do mar for mar -- engifrio sociedade de refrigeracao : €11.230297266821127
  centro de formacao profissional das pescas e do mar for mar -- exitus solucoes tecnologicas : €8.777555453213056
  centro de formacao profissional das pescas e do mar for mar -- expt sistemas de ensino e pesquisa para laboratorio : €12.733755386362587
  centro de formacao profissional das pescas e do mar for mar -- gouveia pereira costa freitas &amp associados sociedade de advogados s p r l : €9.9281801651265
  centro de formacao profissional das pescas e do mar for mar -- jmc cleaning services : €10.129586731675971
  centro de formacao profissional das pescas e do mar for mar -- modutronic comercio de equipamentos electronicos : €12.460714863903755
  centro de formacao profissional das pescas e do mar for mar -- nautilus : €10.454658641300215
  centro de formacao profissional das pescas e do mar for mar -- noveduc : €11.87114871963206
  centro de formacao profissional das pescas e do mar for mar -- noveduc material didatico : €10.308919326755392
  centro de formacao profissional das pescas e do mar for mar -- orey tecnica servicos navais : €10.90155928643844
  centro de formacao profissional das pescas e do mar for mar -- quaternaire portugal consultoria para o desenvolvimento s aforum oceano associacao da economia do mar : €11.399196699641886
  centro de formacao profissional das pescas e do mar for mar -- raah services and global solutions : €9.877554170509624
  centro de formacao profissional das pescas e do mar for mar -- vectortribute : €9.718362068409439
  centro de formacao profissional das pescas e do mar for mar -- wavelength technology center : €9.82937265728152
  centro humanitario vale do dao da cruz vermelha portuguesa -- medicinalia cormedica cormedica : €11.342137143989946
  comissao nacional de promocao dos direitos e protecao das criancas e jovens -- valpi rent : €10.261420704598939
  comissao para a igualdade no trabalho e no emprego -- ohmtecnica representacoes de marcas : €5.075173815233827
  direcao geral da seguranca social -- maquilotus comercio de produtos de limpeza : €7.413029522309792
  direcao geral do livro dos arquivos e das bibliotecas -- claranet ii solutions : €13.909565559452686
  direcao geral do livro dos arquivos e das bibliotecas -- noa gmbh : €12.946009824594539
  direcao geral do tribunal de contas -- claranet ii solutions : €8.511496998871356
  direcao geral do tribunal de contas -- zelo 2000 : €8.874727765766853
  docapesca portos e lotas -- avia te ? travel &amp events : €11.526039104115611
  docapesca portos e lotas -- market access consultores em negocio internacional : €11.829559359371776
  edurumos educacao l da -- inforlandia : €12.801248608864148
  edurumos educacao l da -- meo servicos de comunicacoes e multimedia s ainforabreu : €9.945110186459102
  egeac empresa de gestao de equipamentos e animacao cultural e m -- citirama viagens e turismo : €11.323216689742257
  egeac empresa de gestao de equipamentos e animacao cultural e m -- ecm mobiliario urbano : €11.329242982536933
  egeac empresa de gestao de equipamentos e animacao cultural e m -- maxiglobal equipamentos e servicos de informatica : €11.668676463603997
  egeac empresa de gestao de equipamentos e animacao cultural e m -- merging select : €10.398508132012998
  egeac empresa de gestao de equipamentos e animacao cultural e m -- nan audiovisuais representacao e distribuicao de equipamentos : €11.97595545985258
  egeac empresa de gestao de equipamentos e animacao cultural em -- nan audiovisuais representacao e distribuicao de equipamentos : €11.811336401772975
  egeac empresa de gestao de equipamentos e animacao cultural em -- stagetec estruturas especiais : €10.992049505350737
  emel empresa municipal de mobilidade e estacionamento de lisboa e m -- timestamp sistemas de informacao : €11.109698001466995
  ensiprof ensino e formacao profissional l da -- nautilus : €10.024720187034527
  ensiprof ensino e formacao profissional l da -- ris 2048 sistemas informaticos e comunicacoes : €12.534401097082725
  entidade orcamental -- basedois informatica e telecomunicacoes : €10.487823827237893
  entidade orcamental -- ohmtecnica representacoes de marcas : €6.665123051084064
  entidade orcamental -- toptoner rec e comercializacao consumiveis inf : €5.902633333401366
  escola superior nautica infante d henrique -- infosquad : €10.991708538137113
  escola superior nautica infante d henrique -- ordem didatica : €10.543278522886405
  escola superior nautica infante d henrique -- wavecom solucoes radio : €11.396388165562144
  esna europe startup nations alliance associacao -- babel iberica : €12.534222849900223
  estrutura de missao para a extensao da plataforma continental -- vodafone portugal comunicacoes pessoais : €4.2414706271123945
  faculdade de arquitetura da universidade de lisboa -- reload consultoria informatica : €11.77475404752424
  faculdade de letras da universidade de lisboa -- aps estudos projectos e montagens de iluminacao : €10.355322437721211
  faculdade de letras da universidade de lisboa -- edni empresa distribiudora de material informatico : €8.035583268968203
  faculdade de letras da universidade de lisboa -- exitus solucoes tecnologicas : €10.015534166340576
  faculdade de letras da universidade de lisboa -- meo servicos de comunicacoes e multimedia : €10.621983228109512
  freguesia de estrela -- barraqueiro transportes : €12.092399901041597
  freguesia de estrela -- graump maquinaria industrial : €12.211567521012135
  freguesia de estrela -- smile viagens e turismo : €12.02425096377787
  freguesia de marvila -- jpg transportes : €12.27769538920314
  freguesia de silveira -- meristema : €11.44336057276776
  fundacao centro cultural de belem -- dcinema : €11.320553572322773
  fundacao centro cultural de belem -- nan audiovisuais representacao e distribuicao de equipamentos audiovisuais : €13.407459654567193
  fundacao centro cultural de belem -- ohmtecnica representacoes de marcas : €7.897021341814079
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- autentifuturo restauros : €10.928962480594482
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- casadarte construcao civil : €10.777163016268934
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- cosmotriangular : €10.746691329302752
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- costa braga construcoes : €11.211279685501061
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- crvm engenharia e construcao : €11.02528844240787
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- declives e arestas construcoes e remodelacoes : €10.736529617176137
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- horacio mendes &amp bruno construcoes e obras publicas : €10.64108214783137
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- juvenal medeiros construcoes &amp remodelacoes unipessoal : €11.07997096191945
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- juvenal medeiros construcoes e remodelacoes : €11.107278027630613
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- margem mitica manutencao e reabilitacao : €10.645691046750661
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- metangular construcoes : €10.685412257861463
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- potencial abcissa construcoes : €10.9228543980539
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- resposta versatil : €10.815368575921584
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- resposta versatil construcao civil : €10.470970740806997
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- rubricas esplendidas construcoes : €10.76551653455434
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m -- vinculo perene engenharia e construcao : €11.335407193907288
  guarda nacional republicana -- a do carmo importacao exportacao e comercio : €9.44102740204626
  guarda nacional republicana -- a gouv reparacao e manutencao de veiculos : €10.300584410973777
  guarda nacional republicana -- abrancongelados produtos alimentares : €8.453386586711552
  guarda nacional republicana -- alexandre martos martinez : €10.717363204472408
  guarda nacional republicana -- alive portugal : €11.22390916950531
  guarda nacional republicana -- almeida &amp neves : €8.691398567607935
  guarda nacional republicana -- antero lopes : €10.168124624287467
  guarda nacional republicana -- beatriz soares ribeiro : €8.699514748210191
  guarda nacional republicana -- bestofgifts : €8.056426767522984
  guarda nacional republicana -- cacicambra comercio e industria de artigos de caca : €9.315241069287435
  guarda nacional republicana -- celicerca vedacoes e servicos equestres : €8.973668220432147
  guarda nacional republicana -- codigo azul : €9.97673164426375
  guarda nacional republicana -- comp lezirias : €8.699514748210191
  guarda nacional republicana -- consuma europa foods unipessoal : €11.225243392518447
  guarda nacional republicana -- costa &amp porfirio : €12.41157542944423
  guarda nacional republicana -- deltagel : €10.563866160047304
  guarda nacional republicana -- deltagel produtos alimentares : €9.22729713694482
  guarda nacional republicana -- domingos &amp nogueira : €9.880036160659545
  guarda nacional republicana -- dot viagens e turismo : €11.222573163962569
  guarda nacional republicana -- egipneus : €9.02067568826677
  guarda nacional republicana -- enerre : €5.3471075307174685
  guarda nacional republicana -- escola superior nautica infante d henrique : €11.075969689770693
  guarda nacional republicana -- exitus solucoes tecnologicas : €9.474549088242322
  guarda nacional republicana -- exumas consulting group : €9.382631631828323
  guarda nacional republicana -- frutas corvo imp exp frutos e produtos horticolas : €10.0996066072988
  guarda nacional republicana -- gabriel &amp silvia frutas : €7.415776975415394
  guarda nacional republicana -- geoclima : €9.28387889631098
  guarda nacional republicana -- gestinventos energias e representacoes de equipamentos : €8.366370301681654
  guarda nacional republicana -- inforlandia : €7.745262510048918
  guarda nacional republicana -- joaquim dias antunes : €9.67401149314871
  guarda nacional republicana -- lucstockfood venda e distribuicao alimentar : €10.45687225322077
  guarda nacional republicana -- manuel gonzalez martinez &amp filhos : €9.647465632812215
  guarda nacional republicana -- manuel gonzalez martins &amp amp filhos : €10.637539124221634
  guarda nacional republicana -- mariana de jesus goncalves mamede lopes : €10.085809109330082
  guarda nacional republicana -- mario andre goncalves reis : €9.487282928589401

## <font size=5>**3.4 Total Contracts Volume (Price) per Entity**</font> <a class="anchor" id="3.4"></a>
  
[Back to TOC](#toc)

In [54]:
volume = {node: 0 for node in G.nodes()}

# Step 2
for u, v, data in G.edges(data=True):
    volume[u] += data["weight"]
    volume[v] += data["weight"]

# Step 3
sorted_volume = sorted(volume.items(), key=lambda x: x[1], reverse=True)
print("Entity volume ranking:")
for entity, vol in sorted_volume:
    print(f"  {entity}: €{vol:,.0f}")

Entity volume ranking:
  guarda nacional republicana: €606
  secretaria geral do ministerio da administracao interna: €278
  servicos municipalizados de agua e saneamento de sintra: €203
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m: €174
  casa pia de lisboa i p: €173
  centro de formacao profissional das pescas e do mar for mar: €171
  instituto nacional de medicina legal e ciencias forenses i p: €149
  claranet ii solutions: €145
  instituto superior de economia e gestao: €142
  santa casa da misericordia de lisboa: €136
  agencia para a modernizacao administrativa i p: €131
  instituto de acao social das forcas armadas i p: €119
  servicos intermunicipalizados de aguas e residuos dos municipios de loures e odivelas: €119
  municipio de mafra: €112
  ministerio da defesa nacional marinha: €111
  municipio de oeiras: €99
  iseg instituto superior de economia e gestao: €99
  instituto nacional de estatistica i p: €92
  agencia nacional para a qualificacao e o ensino profissional i p: €91
  municipio de cascais: €89
  municipio de loures: €87
  servicos sociais da administracao publica: €83
  instituto nacional de saude doutor ricardo jorge i p: €81
  imprensa nacional casa da moeda: €73
  inetum espana sucursal em portugal: €72
  instituto da mobilidade e dos transportes i p: €72
  exitus solucoes tecnologicas: €66
  autoridade para as condicoes do trabalho: €64
  servicos sociais da guarda nacional republicana: €64
  instituto portugues do mar e da atmosfera i p: €62
  timestamp sistemas de informacao: €57
  egeac empresa de gestao de equipamentos e animacao cultural e m: €57
  municipio de alenquer: €54
  instituto de protecao e assistencia na doenca i p: €53
  municipio da amadora: €53
  instituto de gestao financeira e equipamentos da justica i p: €52
  secretaria geral do mai: €48
  instituto de informatica i p: €47
  municipio de odivelas: €47
  escola superior nautica infante d henrique: €44
  servicos intermunicipalizados de agua e saneamento dos municipios de oeiras e amadora: €44
  ohmtecnica representacoes de marcas: €42
  claranet portugal: €42
  papelprint: €41
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim: €41
  municipio do cadaval: €41
  base2: €40
  hccm consulting: €39
  faculdade de letras da universidade de lisboa: €39
  spms servicos partilhados do ministerio da saude e p e: €39
  autoridade tributaria e aduaneira: €39
  instituto portugues do desporto e juventude i p: €38
  meo servicos de comunicacoes e multimedia: €37
  avvale: €37
  secretaria geral do ministerio do trabalho solidariedade e seguranca social: €36
  freguesia de estrela: €36
  multimac hito innovation: €36
  planeta vertical: €36
  shield domain: €35
  reload consultoria informatica: €35
  warpcom services: €35
  renault portugal: €35
  servicos sociais da gnr: €34
  tecnirede comunicacao de dados: €34
  instituto para os comportamentos aditivos e as dependencias i p: €34
  digiberia information technologies: €34
  secretaria geral da presidencia da republica: €34
  contenur portugal: €34
  infraestruturas de portugal: €34
  instituto nacional de investigacao agraria e veterinaria i p: €33
  agencia para a reforma tecnologica do estado ip: €33
  fundacao centro cultural de belem: €33
  parques de sintra monte da lua: €33
  autoridade nacional de comunicacoes: €33
  basedois informatica e telecomunicacoes: €32
  advanced resources: €32
  prn informatica: €32
  ris 2048 sistemas informaticos e comunicacoes: €31
  nautilus: €31
  vodafone portugal comunicacoes pessoais: €31
  laboratorio nacional de engenharia civil i p: €29
  municipio da lourinha: €29
  acss administracao central do sistema de saude ip: €29
  centro de formacao profissional da reparacao automovel: €29
  direcao geral do livro dos arquivos e das bibliotecas: €27
  instituto da mobilidade e dos transportes: €26
  xix construcao projectos e gestao: €26
  municipio de sobral de monte agraco: €26
  crayon software licensing: €25
  oramix sistemas de informacao: €25
  linkcom sistemas de informacao: €24
  barraqueiro transportes: €24
  carclasse comercio de automoveis: €24
  fujitsu technology solutions: €24
  samsic portugal facility services: €24
  servicos municipalizados de sintra smas: €24
  policia de seguranca publica: €24
  nan audiovisuais representacao e distribuicao de equipamentos: €24
  axianseu digital solutions: €23
  sebasi sistemas de informacao: €23
  docapesca portos e lotas: €23
  sopsa eco innovation: €23
  raso viagens e turismo: €23
  noi: €23
  entidade orcamental: €23
  iberagar: €23
  janz contagem e gestao de fluidos: €23
  instituto da mobilidade e dos transportes i p imt i p: €23
  smile viagens e turismo: €23
  egeac empresa de gestao de equipamentos e animacao cultural em: €23
  idw consultoria em servicos de informacao: €23
  jmc cleaning services: €23
  edurumos educacao l da: €23
  ensiprof ensino e formacao profissional l da: €23
  tml transportes metropolitanos de lisboa e m t: €22
  bravantic: €22
  idoneos: €22
  dot viagens e turismo: €22
  cascais proxima gestao de mobilidade espacos urbanos e energias e m: €22
  autoridade nacional de seguranca rodoviaria: €22
  petrogal: €22
  codigo azul: €22
  beltrao coelho sistemas de escritorio: €22
  laboratorio nacional de engenharia civil ip: €22
  chief security officers: €21
  bricantel comercio de material electrico de braganca: €21
  simopecas: €21
  meristema: €21
  superintendencia do material direcao de infraestruturas: €21
  lnec laboratorio nacional de engenharia civil ip: €21
  eurest portugal: €21
  mendes &amp irmaos: €21
  autoridade da mobilidade e dos transportes: €21
  ambisig ambiente e sistemas de informacao geografica: €21
  inforlandia: €21
  almeida &amp neves: €20
  perene: €20
  edni empresa distribiudora de material informatico: €20
  casobra: €20
  nautiradar sistemas maritimos de electronica e de telecomunicacoes: €20
  adene agencia para a energia: €20
  ntg: €20
  knowledge inside: €20
  waste to me: €20
  such | servico de utilizacao comum dos hospitais: €20
  valpi rent: €20
  configbit solucoes tecnologicas: €19
  gestinventos energias e representacoes de equipamentos: €19
  vneto solucoes: €19
  antero lopes: €18
  megabarcelos informatica e tecnologia: €18
  direcao geral do tribunal de contas: €17
  centro de emprego e formacao profissional de santarem: €17
  casa pia de lisboa ip: €15
  paldata: €15
  instituto de protecao e assistencia na doenca ip adse ip: €15
  nos comunicacoes: €15
  instituto do emprego e formacao profissional ip: €15
  vortice equipamentos cientificos: €14
  cascais dinamica gestao de economia turismo e empreendorismo e m: €14
  sma seguranca privada: €14
  tecradio: €14
  nan audiovisuais representacao e distribuicao de equipamentos audiovisuais: €13
  navallethes: €13
  sibafil: €13
  construcoes pragosa: €13
  adp valor servicos ambientais: €13
  certoma comercio tecnico maquinas: €13
  sibafil sociedade de empreitadas: €13
  unikonstroi: €13
  boldint: €13
  arte agencia para a reforma tecnologica do estado: €13
  simopecas pecas e componentes para viaturas de limpeza urbana: €13
  homeostase 2 intelligence: €13
  centro de emprego e formacao profissional de setubal: €13
  wws consultoria informatica: €13
  agrupamento de escolas jose afonso loures: €13
  lisboa ocidental sru sociedade de reabilitacao urbana e m: €13
  pemofam facility services: €13
  noa gmbh: €13
  aguas do vale do tejo: €13
  riportico engenharia: €13
  eugreb invest: €13
  carlos ramos marques: €13
  ediperfil: €13
  blueotter circular: €13
  j vilaseca: €13
  tmlj facility services: €13
  policia judiciaria: €13
  evonic evolution and innovation consulting: €13
  expt sistemas de ensino e pesquisa para laboratorio: €13
  livraria e papelaria nova: €13
  know how sociedade de ensino de languas e accao social: €13
  litovale: €13
  strongplan: €13
  reditus networks innovation: €13
  protecnil sociedade tecnica de construcoes: €13
  esna europe startup nations alliance associacao: €13
  babel iberica: €13
  modutronic comercio de equipamentos electronicos: €12
  nors vt trucks and buses: €12
  costa &amp porfirio: €12
  universidade do minho: €12
  schmid construcoes: €12
  obrimix calcadas e construcoes: €12
  toptoner rec e comercializacao consumiveis inf: €12
  freguesia de marvila: €12
  jpg transportes: €12
  irlandox laboratorios de quimica analitica: €12
  centro de emprego de matosinhos: €12
  graump maquinaria industrial: €12
  olimec: €12
  cnmf &amp associados sp rl: €12
  instituto superior de engenharia de lisboa: €12
  agencia para o investimento e comercio externo de portugal e p e: €12
  movegreat transports: €12
  hewlett packard portugal: €12
  instituto nacional de estatistica ip: €12
  associacao de promocao da regiao autonoma da madeira: €12
  diretriz duradoura: €12
  goldfarma comercio de produtos farmaceuticos: €12
  hewlett packard: €12
  omep obras medicoes e projetos: €12
  fidelidade: €12
  tecnilab av portugal: €12
  mc computadores: €12
  instituto superior tecnico: €12
  pinto &amp cruz motores e equipamentos: €12
  bajomico org hotel e similares: €12
  noveduc: €12
  movex producao venda e aluguer de modulos pre fabricados: €12
  marinha direcao de navios: €12
  shamrock: €12
  lucena &amp lucena: €12
  market access consultores em negocio internacional: €12
  m r a instrumentacao para medicao registo e analises: €12
  flow systems sistemas de medicao de fluidos: €12
  faculdade de arquitetura da universidade de lisboa: €12
  rhmais: €12
  pdm e fc projecto desenvolvimento manutencao formacao e consultadoria: €12
  science4you: €12
  incm imprensa nacional casa da moeda: €12
  interessantequacao produtos consultoria e servicos: €12
  a barreira: €12
  rsf texteis: €12
  lactogal produtos alimentares: €12
  maxiglobal equipamentos e servicos de informatica: €12
  nova expressao planeamento de media e publicidade: €12
  motivo comercio e motivacao de mercados: €12
  provedoria de justica: €12
  spir sociedade portuguesa de inovacao em restauracao: €12
  xanauto comercio de veiculos automoveis: €12
  amigalecrim: €12
  fidelidade companhia de seguros: €12
  izumix: €12
  tropichance metalurgica e construcoes: €12
  diversoes simoes &amp filhos: €12
  avia te ? travel &amp events: €12
  mdn direcao geral da autoridade maritima: €12
  azores sub: €12
  prf gas tecnologia e construcao: €12
  euphoric flash: €12
  jopiramos: €11
  fachaimper: €11
  logicalis portugal: €11
  misterioportuno: €11
  instituto do emprego e da formacao profissional i p: €11
  freitas rosa: €11
  freguesia de silveira: €11
  funerexpress: €11
  pedcarsegur: €11
  quaternaire portugal consultoria para o desenvolvimento s aforum oceano associacao da economia do mar: €11
  moticristo: €11
  wavecom solucoes radio: €11
  novo corpo exercicio fisico e reabilitacao: €11
  globaltendas: €11
  centro humanitario vale do dao da cruz vermelha portuguesa: €11
  medicinalia cormedica cormedica: €11
  especial 1 seguranca privada: €11
  vinculo perene engenharia e construcao: €11
  ecm mobiliario urbano: €11
  citirama viagens e turismo: €11
  prosonic produtos de imagem e comunicacao: €11
  dcinema: €11
  autogirar soc comercial automoveis: €11
  blue ocean medical rescue ld a: €11
  ph informatica: €11
  instituto nacional da propriedade industrial i p: €11
  openline facility services: €11
  pricewaterhouse/ag assessoria de gestao: €11
  nonstop tradition: €11
  solvit innovation development on telecommunications: €11
  simar servicos intermunicipalizados de loures e odivelas: €11
  enermeter sistemas medicao: €11
  litoral leituras: €11
  m coutinho nordeste comercio de automoveis: €11
  engifrio sociedade de refrigeracao: €11
  consuma europa foods unipessoal: €11
  bravantic evolving technology: €11
  alive portugal: €11
  uniao para accao cultural e juvenil educativa: €11
  costa braga construcoes: €11
  indra sistemas portugal: €11
  mega local: €11
  cyberops: €11
  arvores &amp amp pessoas gestao arvore espaco urbano: €11
  anditec tecnologias reabilitacao: €11
  locarent companhia portuguesa de aluguer de viaturas: €11
  toyota caetano portugal: €11
  instituto da mobilidade e dos transportes ip: €11
  emel empresa municipal de mobilidade e estacionamento de lisboa e m: €11
  juvenal medeiros construcoes e remodelacoes: €11
  juvenal medeiros construcoes &amp remodelacoes unipessoal: €11
  ebsco information services u: €11
  ip infraestruturas de portugal: €11
  crvm engenharia e construcao: €11
  inforlandia sistemas e servicos de informatica: €11
  stagetec estruturas especiais: €11
  infosquad: €11
  top partner viagens &amp solucoes empresariais: €11
  carmo estruturas em madeira: €11
  periodic table of events: €11
  strobosom: €11
  autentifuturo restauros: €11
  meo servicos de comunicacoes multimedia: €11
  potencial abcissa construcoes: €11
  eco impact: €11
  orey tecnica servicos navais: €11
  centro de emprego e formacao profissional de leiria: €11
  boldint by devoteam: €11
  auto reno minho comercio de automoveis: €11
  lusitania companhia de seguros: €11
  generali seguros: €11
  ecoambiente servicos e meio ambiente: €11
  resposta versatil: €11
  glfv: €11
  casadarte construcao civil: €11
  rubricas esplendidas construcoes: €11
  cosmotriangular: €11
  declives e arestas construcoes e remodelacoes: €11
  jose silva carvalho catering: €11
  alexandre martos martinez: €11
  etnaga consultores sistemas de informacao: €11
  jose carlos andre transportes: €11
  maquilotus comercio de produtos de limpeza: €11
  ageas portugal companhia de seguros: €11
  metangular construcoes: €11
  rri servicos ambientais: €11
  isoroof impermeabilizacoes: €11
  instituto nacional de estatistica ip ine: €11
  margem mitica manutencao e reabilitacao: €11
  sergio jose mamede goncalves: €11
  santomargo construcoes: €11
  horacio mendes &amp bruno construcoes e obras publicas: €11
  manuel gonzalez martins &amp amp filhos: €11
  wrdn servicos de assistencia e manutencao global: €11
  leiridiesel comercio e rep de autom: €11
  nova expressao planeamento de meios e publicidade: €11
  crc car rental company: €11
  lusodoc: €11
  deltagel: €11
  noesis portugal consultadoria em sistemas informaticos: €11
  gartecnica unip: €11
  ordem didatica: €11
  oceano franzino: €11
  sigmadetalhe: €11
  contisystems tecnologias de informacao: €10
  resposta versatil construcao civil: €10
  tronicom: €10
  marl mercado abastecedor da regiao de lisboa: €10
  unnisa revestimentos manutencao e construcao: €10
  specanalitica equipamentos analiticos: €10
  lucstockfood venda e distribuicao alimentar: €10
  nautitejo: €10
  incentea tecnologia de gestao: €10
  xpand solutions informatica e novas tecnologias: €10
  redshift consulting: €10
  merging select: €10
  unidade local de saude de lisboa ocidental e p e: €10
  getinge group portugal: €10
  arquirenova reabilitacao edificios estruturas acos leves: €10
  jorge fernandes: €10
  marinha direcao de abastecimento: €10
  reta servicos tecnicos e rent a cargo: €10
  aps estudos projectos e montagens de iluminacao: €10
  tiberone portugal: €10
  configbit: €10
  premium green mail: €10
  instituto hidrografico: €10
  marsensing: €10
  armasul distribuidor de materiais electricos: €10
  noveduc material didatico: €10
  asc armenio salgado costa comercio de produtos de higiene: €10
  a gouv reparacao e manutencao de veiculos: €10
  sfs gestao e consultoria: €10
  paulo silva santos engenharia e construcoes: €10
  antao medical equipamentos medico cirurgicos: €10
  comissao nacional de promocao dos direitos e protecao das criancas e jovens: €10
  wpp media: €10
  fujifilm portugal: €10
  resende actividades turisticas: €10
  apcer: €10
  sopinal industria de equipamentos e contentores: €10
  alacer mobiliario de escritorio: €10
  ilc instrumentos de laboratorio e cientificos: €10
  viana musica: €10
  alpia2 new concept limitada: €10
  torfal: €10
  frutas corvo imp exp frutos e produtos horticolas: €10
  mariana de jesus goncalves mamede lopes: €10
  bio rad laboratories: €10
  wrdn servicos de assistencia e manutencao global unipessoal ld: €10
  milicia: €10
  zoller iberica u: €10
  ambienti d'interni: €10
  instituto da seguranca social i p: €10
  r f s telecomunicacoes: €10
  iberdigital servicos de informatica: €10
  bestofgifts brindes &amp amp companhia: €10
  kone portugal elevadores: €10
  sermotive: €10
  meo servicos de comunicacoes e multimedia s ainforabreu: €10
  cartonarte industria de cartonagem: €10
  gouveia pereira costa freitas &amp associados sociedade de advogados s p r l: €10
  area metropolitana de lisboa: €10
  cpcecho: €10
  portfolio portugal: €10
  2wayview: €10
  atmo sensation unip: €10
  domingos &amp nogueira: €10
  raah services and global solutions: €10
  eurosafe manufacturing of military &amp safety uniforms: €10
  m m cunha: €10
  nortel comercio de equipamentos hoteleiros: €10
  dps digital printing services: €10
  enveloprinter tipografia papelaria e similares: €10
  uniao panificadora da amadora: €10
  micotec electronica: €10
  wavelength technology center: €10
  evce power: €10
  smotiontv: €10
  intermaco comercio e representacoes maquinas ferramentas: €10
  alpia 2 new concept: €10
  sotkon portugal sistemas de residuos: €10
  o mundo da equitacao: €10
  cartonarte: €10
  vasconcelos &amp almeida engenharia: €10
  portral: €10
  vectortribute: €10
  viana musica artigos musicais: €10
  irradiare investigacao e desenvolvimento em energia e ambiente: €10
  goon services: €10
  joaquim dias antunes: €10
  corifa construcao civil: €10
  max one material de escritorio: €10
  manuel gonzalez martinez &amp filhos: €10
  letras &amp petalas: €10
  iberdata equipamentos: €10
  timberlake consultores: €10
  saborfrio: €10
  i p m informatica papelaria mobiliario: €10
  alugal: €10
  quilaban: €10
  mbit computadores e servicos de informatica: €10
  a salgado distribuicao: €10
  devscope: €10
  sebia fabrico aparelhos bioquimica: €10
  jelskey jose gomes unipessoal limitada: €10
  rodoviaria do alentejo: €10
  mario andre goncalves reis: €9
  sopromar centro nautico: €9
  planetavertical: €9
  vitor vaz: €9
  kone elevadores de portugal: €9
  rubis energia portugal: €9
  a do carmo importacao exportacao e comercio: €9
  megabarcelos informatica e tecnologia unip: €9
  frenetiksmile: €9
  exumas consulting group: €9
  saftur viagens e turismo: €9
  caravela companhia de seguros: €9
  niobo: €9
  esteriplas: €9
  lusopalex: €9
  cacicambra comercio e industria de artigos de caca: €9
  geoclima: €9
  humberto pocas: €9
  inetum tech portugal: €9
  beamian: €9
  deltagel produtos alimentares: €9
  ph informatica e microssistemas: €9
  adelino pedro: €9
  gades training: €9
  vwr international material de laboratorio: €9
  policarpo ferreira da silva: €9
  egipneus: €9
  instituto nacional de investigacao agraria e veterinaria ip: €9
  vwr international: €9
  rui &amp ferreira: €9
  primavera business software solutions: €9
  vitor escada comercio e servicos: €9
  celicerca vedacoes e servicos equestres: €9
  vale do ave transportes: €9
  sociedade barraqueiro transportes: €9
  zufrutti: €9
  tcsi digiberia tecnologia de inormacao: €9
  topgim ibrafer material desportivo e fitness: €9
  zelo 2000: €9
  modutronic: €9
  agripublic: €9
  dragondisplay: €9
  portral comercio e industria de carnes: €9
  soquimica sociedade de representacoes de quimica: €9
  iberian care 2016 portugal: €9
  beatriz soares ribeiro: €9
  comp lezirias: €9
  transfialense: €9
  palco e bancada venda e aluguer de equipamento para espectaculos e organizacao de eventos: €9
  medicinalia cormedica mcmedical limitada: €9
  1 meo servicos de comunicacoes e multimedia: €9
  neoparts equipamentos: €9
  johnson &amp johnson: €9
  creative minds: €9
  onretrieval group: €9
  servisan produtos de higiene: €9
  aguas do tejo atlantico: €8

## <font size=5>**3.5 Degree VS Volume**</font> <a class="anchor" id="3.5"></a>
  
[Back to TOC](#toc)

- Degree $\rightarrow$ number of contracts associated with each entity (network degree = in_degree + out_degree)
- Volume $\rightarrow$ total contracted amount associated with each entity (sum of incident edge weights)

**Purpose**: assess which entities are most valuable and how activity (degree) relates to economic impact (volume).

Planned steps:
- compute degree and volume per node
- plot degree vs. volume (use log–log scatter), annotate top entities
- report Pearson and Spearman correlations
- fit a linear model on log-transformed values and flag outliers (high volume/low degree and high degree/low volume)

In [55]:
# Degree and volume per node
metrics = pd.DataFrame({
    "degree": pd.Series(dict(G.degree())),
    "volume": pd.Series(volume)
}).fillna(0)

In [56]:
# Keep only positive values for log-log analysis
pos = metrics[(metrics["degree"] > 0) & (metrics["volume"] > 0)].copy()
pos["log_degree"] = np.log10(pos["degree"])
pos["log_volume"] = np.log10(pos["volume"])

# Correlations on log-transformed values
pearson = pos["log_degree"].corr(pos["log_volume"], method="pearson")
spearman = pos["log_degree"].corr(pos["log_volume"], method="spearman")

print(f"Nodes used in log-log analysis: {len(pos)}")
print(f"Pearson correlation (log10):  {pearson:.4f}")
print(f"Spearman correlation (log10): {spearman:.4f}")

Nodes used in log-log analysis: 564
Pearson correlation (log10):  0.9660
Spearman correlation (log10): 0.7834

In [57]:
# Linear model in log-log space
slope, intercept = np.polyfit(pos["log_degree"], pos["log_volume"], 1)
pos["pred_log_volume"] = intercept + slope * pos["log_degree"]
pos["residual"] = pos["log_volume"] - pos["pred_log_volume"]

print(f"\nlog10(volume) = {intercept:.4f} + {slope:.4f} * log10(degree)")

log10(volume) = 1.0157 + 1.0094 * log10(degree)

In [58]:
# Flag outliers using the box-plot rule (IQR)
degree_dict = dict(G.degree())

q1 = pd.Series(volume).quantile(0.25)
q3 = pd.Series(volume).quantile(0.75)
iqr = q3 - q1
volume_threshold = q3 + 1.5 * iqr

print(f"Volume threshold from box plot rule: €{volume_threshold:,.0f}")
print("Flagged entities (degree ≥ 3 AND volume above upper fence):")

flagged = []
for entity in G.nodes():
    if degree_dict[entity] >= 3 and volume[entity] > volume_threshold:
        flagged.append((entity, degree_dict[entity], volume[entity]))

flagged.sort(key=lambda x: x[2], reverse=True)
for entity, deg, vol in flagged:
    print(f"  {entity}  degree={deg}  volume=€{vol:,.0f}")

print(f"\nTotal flagged: {len(flagged)}")

Volume threshold from box plot rule: €35
Flagged entities (degree ≥ 3 AND volume above upper fence):
  guarda nacional republicana  degree=62  volume=€606
  secretaria geral do ministerio da administracao interna  degree=26  volume=€278
  servicos municipalizados de agua e saneamento de sintra  degree=18  volume=€203
  gebalis gestao do arrendamento da habitacao municipal de lisboa e m  degree=16  volume=€174
  casa pia de lisboa i p  degree=18  volume=€173
  centro de formacao profissional das pescas e do mar for mar  degree=16  volume=€171
  instituto nacional de medicina legal e ciencias forenses i p  degree=17  volume=€149
  claranet ii solutions  degree=14  volume=€145
  instituto superior de economia e gestao  degree=16  volume=€142
  santa casa da misericordia de lisboa  degree=15  volume=€136
  agencia para a modernizacao administrativa i p  degree=13  volume=€131
  instituto de acao social das forcas armadas i p  degree=11  volume=€119
  servicos intermunicipalizados de aguas e residuos dos municipios de loures e odivelas  degree=11  volume=€119
  municipio de mafra  degree=10  volume=€112
  ministerio da defesa nacional marinha  degree=11  volume=€111
  municipio de oeiras  degree=9  volume=€99
  iseg instituto superior de economia e gestao  degree=10  volume=€99
  instituto nacional de estatistica i p  degree=8  volume=€92
  agencia nacional para a qualificacao e o ensino profissional i p  degree=10  volume=€91
  municipio de cascais  degree=8  volume=€89
  municipio de loures  degree=7  volume=€87
  servicos sociais da administracao publica  degree=8  volume=€83
  instituto nacional de saude doutor ricardo jorge i p  degree=9  volume=€81
  imprensa nacional casa da moeda  degree=7  volume=€73
  inetum espana sucursal em portugal  degree=6  volume=€72
  instituto da mobilidade e dos transportes i p  degree=7  volume=€72
  exitus solucoes tecnologicas  degree=7  volume=€66
  autoridade para as condicoes do trabalho  degree=6  volume=€64
  servicos sociais da guarda nacional republicana  degree=6  volume=€64
  instituto portugues do mar e da atmosfera i p  degree=5  volume=€62
  timestamp sistemas de informacao  degree=5  volume=€57
  egeac empresa de gestao de equipamentos e animacao cultural e m  degree=5  volume=€57
  municipio de alenquer  degree=5  volume=€54
  instituto de protecao e assistencia na doenca i p  degree=6  volume=€53
  municipio da amadora  degree=4  volume=€53
  instituto de gestao financeira e equipamentos da justica i p  degree=4  volume=€52
  secretaria geral do mai  degree=4  volume=€48
  instituto de informatica i p  degree=5  volume=€47
  municipio de odivelas  degree=4  volume=€47
  escola superior nautica infante d henrique  degree=4  volume=€44
  servicos intermunicipalizados de agua e saneamento dos municipios de oeiras e amadora  degree=4  volume=€44
  ohmtecnica representacoes de marcas  degree=6  volume=€42
  claranet portugal  degree=4  volume=€42
  papelprint  degree=5  volume=€41
  centro de formacao profissional da industria metalurgica e metalomecanica cenfim  degree=4  volume=€41
  municipio do cadaval  degree=4  volume=€41
  base2  degree=4  volume=€40
  hccm consulting  degree=3  volume=€39
  faculdade de letras da universidade de lisboa  degree=4  volume=€39
  spms servicos partilhados do ministerio da saude e p e  degree=3  volume=€39
  autoridade tributaria e aduaneira  degree=3  volume=€39
  instituto portugues do desporto e juventude i p  degree=3  volume=€38
  meo servicos de comunicacoes e multimedia  degree=3  volume=€37
  avvale  degree=3  volume=€37
  secretaria geral do ministerio do trabalho solidariedade e seguranca social  degree=3  volume=€36
  freguesia de estrela  degree=3  volume=€36
  multimac hito innovation  degree=3  volume=€36
  planeta vertical  degree=4  volume=€36
  shield domain  degree=3  volume=€35
  reload consultoria informatica  degree=3  volume=€35

Total flagged: 60

In [59]:
# Plotting

# prepare fit line
x_line = np.logspace(np.log10(pos["degree"].min()), np.log10(pos["degree"].max()), 200)
y_line = 10 ** (intercept + slope * np.log10(x_line))

# main traces
scatter = go.Scatter(
    x=pos["degree"],
    y=pos["volume"],
    mode="markers",
    marker=dict(size=6, color="steelblue", opacity=0.5),
    name="nodes",
    hovertemplate="%{text}<br>Degree: %{x}<br>Volume: €%{y:,.0f}",
    text=pos.index
)

fit_line = go.Scatter(
    x=x_line,
    y=y_line,
    mode="lines",
    line=dict(color="crimson", width=2),
    name="log-log fit"
)

# annotations for top entities
annotations = []
top_entities = [entity for entity, _ in top5]

for node in top_entities:
    x = metrics.loc[node, "degree"]
    y = metrics.loc[node, "volume"]
    annotations.append(
        dict(
            x=x,
            y=y,
            text=node,
            showarrow=True,
            arrowhead=2,
            ax=10,
            ay=-10,
            font=dict(size=10),
        )
    )

fig = go.Figure(data=[scatter, fit_line])
fig.update_layout(
    title="Degree VS Volume",
    xaxis=dict(title="Degree", type="log"),
    yaxis=dict(title="Volume (€)", type="log"),
    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_layout(
    title="Degree vs Volume",
    
    xaxis=dict(
        title="Degree",
        type="log",
        dtick=1,              # only 10^n ticks → 1, 10, 100, 1000
        tickformat=".0f"      # show full numbers instead of scientific notation
    ),
    
    yaxis=dict(
        title="Volume (€)",
        type="log",
        dtick=1,
        # tickformat=".0f"
    ),

    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_xaxes(showgrid=True, gridwidth=1)
fig.update_yaxes(showgrid=True, gridwidth=1)

fig.show()

In [60]:
# TODO: add attribute adjudicante/adjudicatario to hoover in plot and maybe change the color of the point based on it

**NETWORK MUNICIPALITY**

In [61]:
import pandas as pd
import numpy as np
import networkx as nx


# =========================================================
# 1. INPUT HANDLING (DICT / LIST / DF SAFE)
# =========================================================
def ensure_dataframe(data):

    if isinstance(data, pd.DataFrame):
        return data.copy()

    if isinstance(data, list):
        return pd.DataFrame(data)

    if isinstance(data, dict):
        # dict of dataframes
        for v in data.values():
            if isinstance(v, pd.DataFrame):
                return v.copy()

        # dict of records
        return pd.DataFrame(data)

    raise TypeError(f"Unsupported input type: {type(data)}")


# =========================================================
# 2. WEIGHT FUNCTION
# =========================================================
def compute_weight(x, mode="log_sum"):
    x = np.array(x)

    if mode == "log_sum":
        return np.log1p(x).sum()
    elif mode == "sum":
        return x.sum()
    elif mode == "mean":
        return x.mean()
    else:
        raise ValueError("Unknown weight mode")


def standardize_contract_data(df):

    df = df.copy()

    # =====================================================
    # 1. SOURCE (company)
    # =====================================================
    if 'source_company' in df.columns:
        pass

    elif 'adjudicante' in df.columns:
        df['source_company'] = df['adjudicante']

    elif 'source' in df.columns:
        df['source_company'] = df['source']

    elif 'adjudicatarios' in df.columns:
        # fallback case where structure is inverted/mixed
        df['source_company'] = df['adjudicante'] if 'adjudicante' in df.columns else np.nan

    else:
        raise ValueError(f"Cannot find source column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 2. TARGET (company)
    # =====================================================
    if 'target_company' in df.columns:
        pass

    elif 'adjudicatarios' in df.columns:
        df['target_company'] = df['adjudicatarios']

    elif 'target' in df.columns:
        df['target_company'] = df['target']

    else:
        raise ValueError(f"Cannot find target column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 3. PRICE
    # =====================================================
    if 'price' in df.columns:
        pass

    elif 'precoContratual' in df.columns:
        df['price'] = df['precoContratual']

    else:
        raise ValueError(f"Cannot find price column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 4. CLEAN
    # =====================================================
    required = ['source_company', 'target_company', 'price']

    df = df.dropna(subset=required)
    df = df[df['price'] > 0]

    return df





# =========================================================
# 5. MUNICIPALITY NETWORK
# =========================================================
def build_municipality_network(data, weight_mode="log_sum"):

    df = ensure_dataframe(data)
    df = standardize_contract_data(df)

    if 'city' not in df.columns:
        raise ValueError("Missing 'city' column")

    df['source_municipality'] = df['city']
    df['target_company'] = df['target_company']

    edge_df = (
        df.groupby(['source_municipality', 'target_company'], as_index=False)
        .agg(
            total_price=('price', 'sum'),
            contracts=('price', 'count'),
            avg_price=('price', 'mean'),
            price_series=('price', list)
        )
    )

    edge_df['weight'] = edge_df['price_series'].apply(
        lambda x: compute_weight(x, mode=weight_mode)
    )

    G = nx.DiGraph()

    for row in edge_df.itertuples(index=False):
        G.add_edge(
            row.source_municipality,
            row.target_company,
            weight=row.weight,
            total_price=row.total_price,
            contracts=row.contracts,
            avg_price=row.avg_price
        )

    return G


# =========================================================
# 6. VISUAL ATTRIBUTES (OPTIONAL)
# =========================================================
def add_visual_attributes(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):

    conc = np.array([d.get('nr_concorrentes', 0) for _, _, d in G.edges(data=True)])
    weight = np.array([d['weight'] for _, _, d in G.edges(data=True)])

    def normalize(x):
        if len(x) == 0:
            return x

        r = np.ptp(x)
        if r == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (r + 1e-9)

    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    for i, (_, _, d) in enumerate(G.edges(data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G


# =========================================================
# 7. PIPELINE USAGE
# =========================================================

df = data  # raw input (dict/list/DataFrame supported)

# MUNICIPALITY NETWORK
G_municipality = build_municipality_network(df)
G_municipality = add_visual_attributes(G_municipality)

ValueError: Cannot find source column. Columns: ['weight', 'total_price', 'nr_concorrentes', 'contracts', 'weight_mode', 'idcontrato', 'tipoContrato', 'tipoFimContrato', 'CPV', 'precoBaseProcedimento', 'precoContratual', 'PrecoTotalEfetivo', 'dataDecisaoAdjudicacao', 'dataCelebracaoContrato', 'dataPublicacao', 'dataFechoContrato', 'nr_concorrentes_list', 'contribuinte_adjudicante', 'contribuinte_adjudicatarios', 'city', 'cpv_prefix', 'agg_cpv']

In [40]:
df = _ensure_dataframe(data)
print(df.columns)

Index(['weight', 'total_price', 'nr_concorrentes', 'contracts', 'weight_mode',
       'idcontrato', 'tipoContrato', 'tipoFimContrato', 'CPV',
       'precoBaseProcedimento', 'precoContratual', 'PrecoTotalEfetivo',
       'dataDecisaoAdjudicacao', 'dataCelebracaoContrato', 'dataPublicacao',
       'dataFechoContrato', 'nr_concorrentes_list', 'contribuinte_adjudicante',
       'contribuinte_adjudicatarios', 'city', 'cpv_prefix', 'agg_cpv'],
      dtype='str')

## <font size=5>**3.6 Exporting It**</font> <a class="anchor" id="3.6"></a>
  
[Back to TOC](#toc)

In [31]:
output_path = '../graphs/gephi_graph01.gexf'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
nx.write_gexf(G, output_path)
print(f'Graph exported to {output_path}')

TypeError: cannot unpack non-iterable int object