<font size=10>**NETWORK**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

<font color='#BFD72' size=5>**RESEARCH QUESTION**: </font><font size=5>*Which companies have a dominant position within specific municipalities?*</font> 

**Data**: 
- [*Portal BASE*](https://www.base.gov.pt/Base4/pt/pesquisa/?type=contratos&texto=&adjudicante=&adjudicataria=&tipo=2&tipocontrato=0&cpv=&aqinfo=&desdeprazoexecucao=&ateprazoexecucao=&sel_price=price_11&desdeprecocontrato=&ateprecocontrato=&desdeprecoefectivo=&ateprecoefectivo=&sel_date=date_11&desdedatacontrato=2023-01-01&atedatacontrato=2026-03-31&desdedatapublicacao=&atedatapublicacao=&desdedatafecho=&atedatafecho=&pais=0&distrito=0&concelho=0)

- [*Treated Datasets*](https://dados.gov.pt/pt/datasets/contratos-publicos-portal-base-impic-contratos-de-2012-a-2026/#/resources)

**Group B**
- Beatriz Marques 20231605
- Maria Inês Santos 20231630
- Luís Soeiro 20211536
- Rodrigo Silva 20231602

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a>  
- [1. Imports](#1)  
- [2. Data Integration](#2)  
- [3. First Network](#3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

Failed to read module file 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\functools.py' for module 'functools': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 308: character maps to <undefined>
Failed to read module file 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\shlex.py' for module 'shlex': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1482: character maps to <undefined>
Failed to read module file 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\re\_casefix.py' for module 're._casefix': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 913: character maps to <undefined>
Failed to read module file 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\parse.py' for module 'urllib.parse': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2030: character maps to <undefined>
Failed to read module file 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\pydoc_data\topics.py' for module 'pydoc_data.topics': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\wwwnj\OneDrive - NOVAIMS\Desktop\Network Analysis\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4751: character maps to <undefined>

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

In [3]:
import subprocess, sys, importlib
import pandas as pd
import plotly.express as px
import re
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

try:
    import openpyxl
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "openpyxl"])
    importlib.invalidate_caches()
    import openpyxl
    
import os
import shutil

# <font color='#BFD72F' size=6>**2. Data Integration**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [4]:
data = pd.read_csv('../data/preprocessed_data.csv')
# data.head()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   idcontrato                   690 non-null    int64
 1   tipoContrato                 690 non-null    str
 2   tipoFimContrato              690 non-null    str
 3   CPV                          690 non-null    str
 4   adjudicante                  690 non-null    str
 5   adjudicatarios               690 non-null    str
 6   concorrentes                 482 non-null    str
 7   precoBaseProcedimento        690 non-null    float64
 8   precoContratual              690 non-null    float64
 9   PrecoTotalEfetivo            690 non-null    float64
 10  dataDecisaoAdjudicacao       690 non-null    str
 11  dataCelebracaoContrato       690 non-null    str
 12  dataPublicacao               690 non-null    str
 13  dataFechoContrato            690 non-null    str
 14  nr_concorrentes              690 non-null    int64
 15  contribuinte_adjudicante     690 non-null    int64
 16  contribuinte_adjudicatarios  680 non-null    float64
 17  city                         677 non-null    str
 18  cpv_prefix                   690 non-null    int64
 19  agg_cpv                      690 non-null    str
 20  adjudicante_clean            690 non-null    str
 21  adjudicatarios_clean         690 non-null    str
dtypes: float64(4), int64(4), str(14)
memory usage: 118.7 KB

In [5]:
data["dataPublicacao"] = pd.to_datetime(data["dataPublicacao"], errors='coerce')
data["dataCelebracaoContrato"] = pd.to_datetime(data["dataCelebracaoContrato"], errors='coerce')
data["dataDecisaoAdjudicacao"] = pd.to_datetime(data["dataDecisaoAdjudicacao"], errors='coerce')
data["dataFechoContrato"] = pd.to_datetime(data["dataFechoContrato"], errors='coerce')

# <font color='#BFD72F' size=6>**3. The Network**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

## <font size=5>**3.1 Creating It**</font> <a class="anchor" id="3.1"></a>
  
[Back to TOC](#toc)

In [6]:
################
### BEA CODE ###
################

# # If your data is not a DataFrame, fix it
# if isinstance(data, dict):
#     data = pd.DataFrame(data)

# # Create directed graph
# G = nx.DiGraph()

# # Build graph
# for _, row in data.iterrows():
#     adjudicante = row['adjudicante']
#     adjudicatarios = row['adjudicatarios']
#     preco = row['precoContratual']
#     concorrentes = row.get('concorrentes', 0)

#     # Skip missing
#     if pd.isna(adjudicante) or pd.isna(adjudicatarios):
#         continue
#     if pd.isna(preco) or preco <= 0:
#         continue

#     log_price = np.log(preco)

#     # Handle concorrentes safely
#     if pd.isna(concorrentes):
#         concorrentes = 0

#     # Add/update nodes
#     if adjudicante not in G:
#         G.add_node(adjudicante, node_type='adjudicante')
#     else:
#         if G.nodes[adjudicante].get('node_type') == 'adjudicatario':
#             G.nodes[adjudicante]['node_type'] = 'both'

#     if adjudicatarios not in G:
#         G.add_node(adjudicatarios, node_type='adjudicatario')
#     else:
#         if G.nodes[adjudicatarios].get('node_type') == 'adjudicante':
#             G.nodes[adjudicatarios]['node_type'] = 'both'

#     # Add/update edge
#     if G.has_edge(adjudicante, adjudicatarios):
#         edge = G[adjudicante][adjudicatarios]
#         edge['weight'] += log_price
#         edge['contracts'] += 1
#         edge_conc = pd.to_numeric(edge.get('nr_concorrentes', 0), errors='coerce')
#         row_conc = pd.to_numeric(concorrentes, errors='coerce')
#         edge['nr_concorrentes'] = int(0 if pd.isna(edge_conc) else edge_conc) + int(0 if pd.isna(row_conc) else row_conc)
#     else:
#         G.add_edge(
#             adjudicante,
#             adjudicatarios,
#             weight=log_price,
#             contracts=1,
#             nr_concorrentes=concorrentes,
#             city=row.get('city', None)
#         )

In [7]:
def compute_weight(prices, mode="log_sum"):

    prices = np.array(prices)

    if mode == "sum_price":
        return prices.sum()

    elif mode == "avg_price":
        return prices.mean()

    elif mode == "log_sum":
        return np.log(prices).sum()

    elif mode == "log_mean":
        return np.log(prices).mean()

    else:
        raise ValueError(
            f"Unknown mode: {mode}. "
            f"Valid modes: sum_price, avg_price, log_sum, log_mean"
        )

In [8]:
def _ensure_dataframe(data):
    if isinstance(data, pd.DataFrame):
        return data.copy()

    if isinstance(data, dict):
        # CASE 1: dict of lists (valid dataframe)
        try:
            df = pd.DataFrame(data)
            return df
        except Exception:
            pass

        # CASE 2: dict of scalars → wrap into list
        return pd.DataFrame([data])

    raise TypeError(f"Unsupported input type: {type(data)}")

In [9]:
def build_contract_network(data, weight_mode="log_sum") -> nx.DiGraph:
    
    df = _ensure_dataframe(data)

    # --- CLEAN COLUMNS ---
    df = df.rename(columns={
        'precoContratual': 'price',
        'adjudicante': 'source',
        'adjudicatarios': 'target'
    })

    # --- BASIC CLEANING ---
    df = df.dropna(subset=['source', 'target', 'price'])
    df = df[df['price'] > 0]

    # --- CONCORRENTES ---
    if 'nr_concorrentes' in df.columns:
        df['concorrentes'] = df['nr_concorrentes']
    else:
        df['concorrentes'] = pd.to_numeric(df.get('concorrentes', 0), errors='coerce').fillna(0)

    # --- EDGE AGGREGATION ---
    edge_df = (
        df.groupby(['source', 'target'], as_index=False)
        .agg(
            total_price=('price', 'sum'),
            nr_concorrentes=('concorrentes', 'sum'),
            contracts=('price', 'count'),
            price_series=('price', list),
            idcontrato=('idcontrato', list),
            tipoContrato=('tipoContrato', list),
            tipoFimContrato=('tipoFimContrato', list),
            CPV=('CPV', list),
            precoBaseProcedimento=('precoBaseProcedimento', list),
            precoContratual=('price', list),
            PrecoTotalEfetivo=('PrecoTotalEfetivo', list),
            dataDecisaoAdjudicacao=('dataDecisaoAdjudicacao', list),
            dataCelebracaoContrato=('dataCelebracaoContrato', list),
            dataPublicacao=('dataPublicacao', list),
            dataFechoContrato=('dataFechoContrato', list),
            nr_concorrentes_list=('nr_concorrentes', list),
            contribuinte_adjudicante=('contribuinte_adjudicante', list),
            contribuinte_adjudicatarios=('contribuinte_adjudicatarios', list),
            city=('city', list),
            cpv_prefix=('cpv_prefix', list),
            agg_cpv=('agg_cpv', list)
        )
    )

    # --- WEIGHT STRATEGY ---
    edge_df['weight'] = edge_df['price_series'].apply(
        lambda x: compute_weight(x, mode=weight_mode)
    )

    edge_df = edge_df.drop(columns=['price_series'])

    # --- BUILD GRAPH ---
    G = nx.DiGraph()

    for row in edge_df.itertuples(index=False):
        G.add_edge(
            row.source,
            row.target,
            weight=row.weight,
            total_price=row.total_price,
            nr_concorrentes=row.nr_concorrentes,
            contracts=row.contracts,
            weight_mode=weight_mode,
            idcontrato=row.idcontrato,
            tipoContrato=row.tipoContrato,
            tipoFimContrato=row.tipoFimContrato,
            CPV=row.CPV,
            precoBaseProcedimento=row.precoBaseProcedimento,
            precoContratual=row.precoContratual,
            PrecoTotalEfetivo=row.PrecoTotalEfetivo,
            dataDecisaoAdjudicacao=row.dataDecisaoAdjudicacao,
            dataCelebracaoContrato=row.dataCelebracaoContrato,
            dataPublicacao=row.dataPublicacao,
            dataFechoContrato=row.dataFechoContrato,
            nr_concorrentes_list=row.nr_concorrentes_list,
            contribuinte_adjudicante=row.contribuinte_adjudicante,
            contribuinte_adjudicatarios=row.contribuinte_adjudicatarios,
            city=row.city,
            cpv_prefix=row.cpv_prefix,
            agg_cpv=row.agg_cpv
        )

    # --- NODE TYPES ---
    sources = set(edge_df['source'])
    targets = set(edge_df['target'])

    for node in G.nodes():
        if node in sources and node in targets:
            G.nodes[node]['node_type'] = 'both'
        elif node in sources:
            G.nodes[node]['node_type'] = 'adjudicante'
        else:
            G.nodes[node]['node_type'] = 'adjudicatario'

    return G

# -------------------------------
# VISUAL ATTRIBUTES (UNIFIED)
# -------------------------------
def add_visual_attributes(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):
    conc = np.array([d['nr_concorrentes'] for _, _, d in G.edges(data=True)])
    weight = np.array([d['weight'] for _, _, d in G.edges(data=True)])

    def normalize(x):
        if len(x) == 0:
            return x

        range_ = np.ptp(x)  # max - min safely

        if range_ == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (range_ + 1e-9)

    # --- TRANSFORM ---
    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    # --- ASSIGN ---
    for i, (u, v, d) in enumerate(G.edges(data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G


# -------------------------------
# RUN PIPELINE
# -------------------------------
G = build_contract_network(data, weight_mode="log_sum")

# Linear scaling
G_linear = add_visual_attributes(
    G.copy(),
    thickness_mode="linear",
    size_mode="linear",
    suffix="_linear"
)

# Log scaling
G_log = add_visual_attributes(
    G.copy(),
    thickness_mode="log",
    size_mode="log",
    suffix="_log"
)

In [10]:
weight_modes = ["sum_price", "avg_price", "log_sum", "log_mean"]

graphs = {
    mode: build_contract_network(data, weight_mode=mode)
    for mode in weight_modes
}

In [11]:
for mode, G in graphs.items():
    volume = {
        node: sum(d["total_price"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    degree = dict(G.degree())

    corr = pd.Series(degree).corr(pd.Series(volume))

    print(f"{mode:10s} → degree-volume correlation: {corr:.3f}")

sum_price  → degree-volume correlation: 0.627
avg_price  → degree-volume correlation: 0.627
log_sum    → degree-volume correlation: 0.627
log_mean   → degree-volume correlation: 0.627

In [12]:
for mode, G in graphs.items():
    top = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:3]

    print(f"\nMode: {mode}")
    for node, deg in top:
        print(f"  {node}: {deg}")

Mode: sum_price
  Guarda Nacional Republicana: 66
  Secretaria-Geral do Ministério da Administração Interna: 28
  Serviços Municipalizados de Água e Saneamento de Sintra: 19

Mode: avg_price
  Guarda Nacional Republicana: 66
  Secretaria-Geral do Ministério da Administração Interna: 28
  Serviços Municipalizados de Água e Saneamento de Sintra: 19

Mode: log_sum
  Guarda Nacional Republicana: 66
  Secretaria-Geral do Ministério da Administração Interna: 28
  Serviços Municipalizados de Água e Saneamento de Sintra: 19

Mode: log_mean
  Guarda Nacional Republicana: 66
  Secretaria-Geral do Ministério da Administração Interna: 28
  Serviços Municipalizados de Água e Saneamento de Sintra: 19

In [13]:
rankings = {}

for mode, G in graphs.items():

    weighted_degree = {
        node: sum(d["weight"] for _, _, d in G.edges(node, data=True))
        for node in G.nodes()
    }

    # convert to ranking (higher = better rank)
    ranked = pd.Series(weighted_degree).rank(ascending=False)

    rankings[mode] = ranked

sum_price → total contract value emphasis

avg_price → typical contract size

log_sum → interaction-frequency + heavy-tail compression

log_mean → normalized interaction intensity

In [14]:
rank_df = pd.DataFrame(rankings)
rank_df.head()

,sum_price,avg_price,log_sum,log_mean
"ACSS-Administração Central do Sistema de Saúde,IP",99.0,97.0,61.0,57.0
"CLARANET II SOLUTIONS, S.A.",390.0,390.0,390.0,390.0
Primavera – Business Software Solutions S.A,390.0,390.0,390.0,390.0
"Timestamp - Sistemas de Informação, S.A.",390.0,390.0,390.0,390.0
ADENE - Agência para a Energia,87.0,85.0,82.0,80.0

In [15]:
rank_df["rank_std"] = rank_df.std(axis=1)
rank_df["rank_mean"] = rank_df.mean(axis=1)

In [16]:
# Structurally important regardless of weight strategy

stable_nodes = rank_df.sort_values("rank_std").head(10)
stable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
dragondisplay unipessoal lda,390.0,390.0,390.0,390.0,0.0,312.0
"CLARANET II SOLUTIONS, S.A.",390.0,390.0,390.0,390.0,0.0,312.0
Primavera – Business Software Solutions S.A,390.0,390.0,390.0,390.0,0.0,312.0
"Timestamp - Sistemas de Informação, S.A.",390.0,390.0,390.0,390.0,0.0,312.0
NÓS COMUNICAÇÕES S.A.,390.0,390.0,390.0,390.0,0.0,312.0
Digibéria Information Technologies S.A.,390.0,390.0,390.0,390.0,0.0,312.0
"Páginas aos Blocos, Lda.",390.0,390.0,390.0,390.0,0.0,312.0
PH Informática,390.0,390.0,390.0,390.0,0.0,312.0
"MULTIMAC HITO INNOVATION, S.A.",390.0,390.0,390.0,390.0,0.0,312.0
"PREMIUM GREEN MAIL, LDA",390.0,390.0,390.0,390.0,0.0,312.0

<font color ='red'>These nodes:
- have identical ranks across ALL weighting schemes
- are structurally invariant in your network

They are topological anchors, not sensitive to how we measure money or interaction.

We see identical rank values like 5594.5, this suggests many tied ranks. So they are stable and saturated centrality nodes. This means that ranking resolution is too coarse and many nodes are indistinguishable under this metric.

In [17]:
# Importende depends heavily on how we measure importance

unstable_nodes = rank_df.sort_values("rank_std", ascending=False).head(10)
unstable_nodes

,sum_price,avg_price,log_sum,log_mean,rank_std,rank_mean
Área Metropolitana de Lisboa,54.0,124.0,10.0,130.0,57.766772,75.153354
"Instituto do Emprego e Formação Profissional, IP",8.0,7.0,88.0,87.0,46.191630,47.238326
"Imprensa Nacional - Casa da Moeda, S. A.",115.0,113.0,47.0,43.0,39.878984,71.575797
"Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P.",91.0,89.0,26.0,23.0,37.845079,53.369016
SUCH | Serviço de Utilização Comum dos Hospitais,63.0,111.0,23.0,81.0,36.783148,62.956630
Município da Lourinhã,110.0,115.0,44.0,56.0,36.472592,72.294518
"Cascais Dinâmica - Gestão de Economia, Turismo e Empreendorismo, E. M., S. A.",29.0,28.0,89.0,88.0,34.645827,53.729165
"Agência Nacional para a Qualificação e o Ensino Profissional, I. P.",77.0,73.0,16.0,15.0,34.393556,43.078711
Faculdade de Letras da Universidade de Lisboa,98.0,96.0,42.0,39.0,32.653484,61.530697
Instituto Superior de Economia e Gestão,67.0,64.0,11.0,8.0,32.377976,36.475595

<font color='red'>These nodes change position dramatically depending on weighting scheme. Their importance depends on what we consider "importance". 

Pattern:
1. Mixed contract sizes
some large contracts
many small ones
2. irregular interaction structure
sporadic procurement behavior
3. heterogeneity in edges

sum_price -> rewards big contracts
avg_price -> smooths variability
log_sum -> rewards frequency
log_mean -> penalizes extreme dispersion

In [18]:
# # Visualize the graph
# # Layout (can take time for big graphs)
# pos = nx.spring_layout(G, k=0.15, iterations=20, seed=42)

# # Extract edge attributes
# weights = [G[u][v]['weight'] for u, v in G.edges()]
# widths = [G[u][v]['nr_concorrentes'] for u, v in G.edges()]

# # Avoid division by zero
# if len(widths) > 0 and max(widths) > 0:
#     widths = [w / max(widths) * 5 for w in widths]
# else:
#     widths = [1 for _ in widths]

# if len(weights) > 0 and max(weights) > 0:
#     weights_norm = [w / max(weights) for w in weights]
# else:
#     weights_norm = weights

# # Draw
# plt.figure(figsize=(12, 10))

# nx.draw_networkx_nodes(G, pos, node_size=50)

# nx.draw_networkx_edges(
#     G,
#     pos,
#     width=widths,                 # thickness = concorrentes
#     edge_color=weights_norm,      # color = log(price)
#     edge_cmap=plt.cm.Blues
# )

# plt.title("Network: Adjudicante → Adjudicatário")
# plt.axis('off')
# plt.show()

## <font size=5>**3.2 General Insights**</font> <a class="anchor" id="3.2"></a>
  
[Back to TOC](#toc)

In [19]:
# Number of nodes
print(f"Number of nodes: {G.number_of_nodes()}")
print(f"\t-> Number of adjudicantes: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicante', 'both']) / G.number_of_nodes() * 100:.2f}%")
print(f"\t-> Number of adjudicatarios: {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both'])}, i.e., {sum(1 for _, attr in G.nodes(data=True) if attr['node_type'] in ['adjudicatario', 'both']) / G.number_of_nodes() * 100:.2f}%")

# Number of edges
print(f"\nNumber of edges: {G.number_of_edges()}")

Number of nodes: 641
	-> Number of adjudicantes: 138, i.e., 21.53%
	-> Number of adjudicatarios: 504, i.e., 78.63%

Number of edges: 589

## <font size=5>**3.3 Rank All Entities By Degree (Number of Contracts)**</font> <a class="anchor" id="3.3"></a>
  
[Back to TOC](#toc)

In [20]:
def entity_type(node):
    node_type = G.nodes[node].get("node_type", "unknown")
    if node_type == "both":
        return "adjudicante and adjudicatario"
    return node_type

# Highest and lowest in-degree
highest_in = max(G.in_degree(), key=lambda x: x[1])
lowest_in = min(G.in_degree(), key=lambda x: x[1])

# Highest and lowest out-degree
highest_out = max(G.out_degree(), key=lambda x: x[1])
lowest_out = min(G.out_degree(), key=lambda x: x[1])

# Average in-degree and out-degree
in_degrees = [d for _, d in G.in_degree()]
out_degrees = [d for _, d in G.out_degree()]

avg_in = sum(in_degrees) / len(in_degrees)
avg_out = sum(out_degrees) / len(out_degrees)

print(f"Highest in-degree: {highest_in} -> {entity_type(highest_in[0])}")
print(f"Lowest out-degree: {lowest_out} -> {entity_type(lowest_out[0])}")

print(f"\nHighest out-degree: {highest_out} -> {entity_type(highest_out[0])}")
print(f"Lowest in-degree: {lowest_in} -> {entity_type(lowest_in[0])}")

print(f"\nAverage in-degree: {avg_in:.2f}")
print(f"Average out-degree: {avg_out:.2f}")

Highest in-degree: ('CLARANET II SOLUTIONS, S.A.', 11) -> adjudicatario
Lowest out-degree: ('CLARANET II SOLUTIONS, S.A.', 0) -> adjudicatario

Highest out-degree: ('Guarda Nacional Republicana', 66) -> adjudicante
Lowest in-degree: ('ACSS-Administração Central do Sistema de Saúde,IP', 0) -> adjudicante

Average in-degree: 0.92
Average out-degree: 0.92

The average in-degree and average out-degree are the same because, in any directed graph, the sum of all in-degrees equals the sum of all out-degrees, and both are equal to the number of edges.

Therefore:
  $$avg_{in}  = |E| / |V|$$
  $$avg_{out} = |E| / |V|$$

so they must be identical.

In [21]:
# Top 5 Degree Enitities
top5 = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:5]
print("Top 5 most connected entities:")
for entity, deg in top5:
    print(f"  {entity}: {deg}")

Top 5 most connected entities:
  Guarda Nacional Republicana: 66
  Secretaria-Geral do Ministério da Administração Interna: 28
  Serviços Municipalizados de Água e Saneamento de Sintra: 19
  Casa Pia de Lisboa, I. P.: 18
  Instituto Nacional de Medicina Legal e Ciências Forenses, I. P.: 18

In [22]:
# Degree-1 entities
deg1 = sorted(
    [(node, degree) for node, degree in G.degree() if degree == 1],
    key=lambda x: x[0]
)

print(f"Degree-1 entities: {len(deg1)}")
for i, (entity, degree) in enumerate(deg1[:20], start=1):
    node_type = G.nodes[entity].get("node_type", "unknown")
    if node_type == "both":
        node_type = "adjudicante and adjudicatario"
    print(f"{i:>3}. {entity} (degree={degree}, type={node_type})")

if len(deg1) > 20:
    print(f"... and {len(deg1) - 20} more")

Degree-1 entities: 499
  1. - - Beatriz Soares Ribeiro (degree=1, type=adjudicatario)
  2. - - EBSCO Information Services S.L.U. (degree=1, type=adjudicatario)
  3. - - J. VILASECA, SA (degree=1, type=adjudicatario)
  4. - - J.VILASECA, SA (degree=1, type=adjudicatario)
  5. - - MARIO ANDRE GONÇALVES REIS (degree=1, type=adjudicatario)
  6. - - Mariana de Jesus Gonçalves Mamede Lopes (degree=1, type=adjudicatario)
  7. - - NOA GmbH (degree=1, type=adjudicatario)
  8. - - Onretrieval Group SL (degree=1, type=adjudicatario)
  9. - - Sérgio José Mamede Gonçalves (degree=1, type=adjudicatario)
 10. 1 - MEO - SERVIÇOS DE COMUNICAÇÕES E MULTIMÉDIA, S.A. (degree=1, type=adjudicatario)
 11. 2WayView Lda (degree=1, type=adjudicatario)
 12. : VECTORTRIBUTE UNIPESSOAL, LDA (degree=1, type=adjudicatario)
 13. A. Barreira, Lda. (degree=1, type=adjudicatario)
 14. A. Do Carmo , Importação , Exportação e Comercio, LDA (degree=1, type=adjudicatario)
 15. A. Gouv - Reparação e Manutenção de Veiculos, Lda (degree=1, type=adjudicatario)
 16. A. Salgado, Distribuição, Unipessoal, Lda (degree=1, type=adjudicatario)
 17. ALACER, Mobiliário de Escritório, Lda. (degree=1, type=adjudicatario)
 18. ALMEIDA &amp; NEVES LDA (degree=1, type=adjudicatario)
 19. ALPIA 2 - NEW CONCEPT, LDA (degree=1, type=adjudicatario)
 20. ALPIA2 -NEW CONCEPT, LIMITADA (degree=1, type=adjudicatario)
... and 479 more

In [23]:
# All contract pairs with amounts
print("Contracts with their amounts:")
for u, v, data in G.edges(data=True):
    print(f"  {u} -- {v} : €{data['weight']:,}")

Contracts with their amounts:
  ACSS-Administração Central do Sistema de Saúde,IP -- CLARANET II SOLUTIONS, S.A. : €8.433811582477187
  ACSS-Administração Central do Sistema de Saúde,IP -- Primavera – Business Software Solutions S.A : €8.990615968707628
  ACSS-Administração Central do Sistema de Saúde,IP -- Timestamp - Sistemas de Informação, S.A. : €11.34954392823967
  ADENE - Agência para a Energia -- Digibéria Information Technologies S.A. : €11.923709734555993
  ADENE - Agência para a Energia -- Páginas aos Blocos, Lda. : €8.160932447399158
  ARTE - Agência para a Reforma Tecnológica do Estado -- MULTIMAC HITO INNOVATION, S.A. : €13.128303817996628
  AdP Valor - Serviços Ambientais, S. A. -- HCCM CONSULTING, S.A. : €13.283143542126385
  Administração Central do Sistema de Saúde, I. P. -- Claranet Portugal, S.A : €6.763908002983978
  Agrupamento de Escolas José Afonso, Loures -- Beltrão Coelho – Sistemas de Escritório, Lda : €13.064400840343946
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- CHIEF SECURITY OFFICERS S.A. : €9.099967314494812
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- CHIEF SECURITY OFFICERS, SA : €9.286579856556685
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- DATAGATE, DESENVOLVIMENTO SOLUÇÕES INFORMÁTICAS, LDA. : €7.461640392208575
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- EDNI  - Empresa Distribiudora de Material Informático, Lda : €7.622345896835734
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- Exitus, Soluções Tecnológicas, Lda. : €7.595889917718538
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- IDONEOS, LDA. : €10.882753083571671
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- INETUM ESPAÑA, S.A. - Sucursal em Portugal : €11.232409653423147
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- Knowledge Inside, Lda : €10.231553123382788
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- PH - Informática e Microssistemas S. A. : €9.141836666542293
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- RIS 2048 - Sistemas Informáticos e Comunicações, S.A : €7.769391283704896
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P. -- jelskey jose gomes unipessoal limitada : €9.52806656577634
  Agência para a Modernização Administrativa, I. P. -- Axianseu Digital Solutions, S.A : €10.459181373890983
  Agência para a Modernização Administrativa, I. P. -- BASE2, LDA : €9.733937409075018
  Agência para a Modernização Administrativa, I. P. -- CLARANET II SOLUTIONS, S.A. : €10.606251661480803
  Agência para a Modernização Administrativa, I. P. -- Claranet Portugal, S.A. : €12.350357734342314
  Agência para a Modernização Administrativa, I. P. -- DIGIBÉRIA INFORMATION TECHNOLOGIES, S.A. : €9.631769478969021
  Agência para a Modernização Administrativa, I. P. -- GLFV Unipessoal Lda : €10.808138807753252
  Agência para a Modernização Administrativa, I. P. -- PSE - Produtos e Serviços de Estatística , Lda : €7.773173680482536
  Agência para a Modernização Administrativa, I. P. -- Papelprint, lda : €5.298011616834201
  Agência para a Modernização Administrativa, I. P. -- Shield Domain, S.A. : €12.201153667168628
  Agência para a Modernização Administrativa, I. P. -- Sigmadetalhe, Lda : €10.505341474649683
  Agência para a Modernização Administrativa, I. P. -- Timestamp – Sistemas de Informação, S.A., : €11.183422983081186
  Agência para a Modernização Administrativa, I. P. -- Xpand Solutions - Informática e Novas Tecnologias, LDA : €10.423931982957537
  Agência para a Modernização Administrativa, I.P. -- APCER : €10.187349838885044
  Agência para a Modernização Administrativa, I.P. -- AXIANSEU DIGITAL SOLUTIONS, S.A. : €10.918720406175867
  Agência para a Reforma Tecnológica do Estado, IP -- MULTIMAC HITO INNOVATION, S.A. : €11.33015376687788
  Agência para a Reforma Tecnológica do Estado, IP -- PDM E FC-PROJECTO DESENVOLVIMENTO MANUTENÇÃO FORMAÇÃO E CONSULTADORIA S.A. : €11.765394781666265
  Agência para a Reforma Tecnológica do Estado, IP -- Portfolio Portugal, Lda. : €9.920211917428539
  Agência para o Investimento e Comércio Externo de Portugal, E. P. E. -- MOVEGREAT TRANSPORTS : €12.096536758461866
  Associação de Promoção da Região Autónoma da Madeira -- Diretriz Duradoura, Lda. : €12.047721489374798
  Autoridade Nacional de Comunicações -- Hewlett-Packard : €12.014054871993325
  Autoridade Nacional de Comunicações -- INETUM TECH PORTUGAL, S.A. : €9.260031082912578
  Autoridade Nacional de Comunicações -- Prosonic - Produtos de Imagem e Comunicação S.A. : €11.320553572322773
  Autoridade Nacional de Segurança Rodoviária -- Advanced Resources, Lda : €10.626739502775123
  Autoridade Nacional de Segurança Rodoviária -- Nova Expressão - Planeamento de Media e Publicidade, S.A. : €11.621975291077785
  Autoridade Tributária e Aduaneira -- HCCM CONSULTING, S.A. : €13.368441900001034
  Autoridade Tributária e Aduaneira -- Hewlett-Packard Portugal, s.A. : €12.095141084822892
  Autoridade Tributária e Aduaneira -- Homeostase 2 Intelligence, Lda. : €13.075271769870477
  Autoridade da Mobilidade e dos Transportes -- AMBISIG - Ambiente e Sistemas de Informação Geográfica, S.A : €10.676601437881464
  Autoridade da Mobilidade e dos Transportes -- BASE2, LDA : €10.19421498317387
  Autoridade para as Condições do Trabalho -- CLARANET II Solutions, S.A. : €11.843068968057189
  Autoridade para as Condições do Trabalho -- Devscope, S.A. : €9.5396153417263
  Autoridade para as Condições do Trabalho -- I.P.M. – Informática, Papelaria, Mobiliário, Lda. : €9.58023218699976
  Autoridade para as Condições do Trabalho -- ORAMIX – SISTEMAS DE INFORMAÇÃO, S.A. : €12.254743754993829
  Autoridade para as Condições do Trabalho -- PAPELPRINT, Lda. : €9.837162903888759
  Autoridade para as Condições do Trabalho -- SEBASI - Sistemas de Informação, SA : €11.218554404367652
  CASA PIA DE LISBOA, I.P. -- Escrinova - Mobiliário e Equipamentos de Escritório, Lda. : €7.600902459542082
  CASA PIA DE LISBOA, I.P. -- Ohmtécnica - Representações de Marcas, Lda : €7.507690077819904
  Casa Pia de Lisboa, I. P. -- Adelaide Ferreira, Lda. : €7.868525946943292
  Casa Pia de Lisboa, I. P. -- BRICANTEL - COMÉRCIO DE MATERIAL ELÉCTRICO DE BRAGANÇA S.A. : €9.314206571699875
  Casa Pia de Lisboa, I. P. -- CRC - Car Rental Company, Lda. : €10.600377719374908
  Casa Pia de Lisboa, I. P. -- Casobra, lda : €10.140918944783984
  Casa Pia de Lisboa, I. P. -- Didatiárea,Unipessoal LDA : €6.814103722900682
  Casa Pia de Lisboa, I. P. -- INETUM ESPAÑA S.A. - SUCURSAL EM PORTUGAL : €11.570409348061537
  Casa Pia de Lisboa, I. P. -- Izumix - Unipessoal Ldª : €11.56171562913966
  Casa Pia de Lisboa, I. P. -- PLANETAVERTICAL - LDA. : €7.467028150985755
  Casa Pia de Lisboa, I. P. -- Papelprint, lda : €10.98164727274205
  Casa Pia de Lisboa, I. P. -- PlanetaVertical, Lda : €11.484302405784561
  Casa Pia de Lisboa, I. P. -- Strongplan, Lda : €12.567237494741757
  Casa Pia de Lisboa, I. P. -- Topgim Ibrafer - Material Desportivo e Fitness Unipessoal Lda : €8.911014776029266
  Casa Pia de Lisboa, I. P. -- Tronicom Lda : €10.45965138933788
  Casa Pia de Lisboa, I. P. -- VALPI RENT, LDA : €9.909966518633837
  Casa Pia de Lisboa, I. P. -- VIANA MÚSICA - ARTIGOS MUSICAIS, UNIPESSOAL LDA : €9.71734419315976
  Casa Pia de Lisboa, I. P. -- Valpi Rent S.A. : €8.750524669117937
  Casa Pia de Lisboa, I. P. -- Vitor Escada - Comercio e Serviços Unipessoal, Lda : €8.986281401793944
  Casa Pia de Lisboa, I. P. -- Vitor Vaz - Unipessoal, Lda : €9.44608657521237
  Casa Pia de Lisboa, IP -- AMERICANA, PAPELARIA, S.A. : €7.839746116660362
  Casa Pia de Lisboa, IP -- Papelprint, lda : €7.278856659662342
  Cascais Dinâmica - Gestão de Economia, Turismo e Empreendorismo, E. M., S. A. -- SMA-Segurança Privada, S.A. : €13.513618939734075
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E. M., S. A. -- Carclasse - Comércio de Automóveis, S.a. : €10.760597120307324
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E. M., S. A. -- PRF - Gás, Tecnologia e Construção, SA : €11.512925464970229
  Centro Humanitário Vale do Dão da Cruz Vermelha Portuguesa -- MEDICINALIA CORMEDICA (CORMEDICA) : €11.342137143989946
  Centro de Emprego de Matosinhos -- SEBASI - Sistemas de Informação, SA : €12.264299099922814
  Centro de Emprego e Formação Profissional de Leiria -- BOLDINT, S.A., by Devoteam : €10.896739325546411
  Centro de Emprego e Formação Profissional de Santarém -- Papelprint, lda : €8.094256337396033
  Centro de Emprego e Formação Profissional de Santarém -- TCSI - Digiberia, tecnologia de inormação, Lda : €8.914101796841281
  Centro de Emprego e Formação Profissional de Setúbal -- WWS - Consultoria Informática, Lda : €13.065499861254253
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM) -- Caravela Companhia de Seguros SA : €9.363213378783923
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM) -- GENERALI SEGUROS, SA : €11.758375564974894
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM) -- Generali Seguros, SA : €10.015958727429002
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM) -- LUSITÂNIA - COMPANHIA DE SEGUROS, S.A : €10.892675523922948
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM) -- Zoller Ibérica, S.L.U : €10.035315495113096
  Centro de Formação Profissional da Reparação Automóvel -- Casobra, lda : €9.987415012471414
  Centro de Formação Profissional da Reparação Automóvel -- INTERMACO-COMÉRCIO E REPRESENTAÇÕES MÁQUINAS FERRAMENTAS, LDA : €9.795902341856191
  Centro de Formação Profissional da Reparação Automóvel -- Modutronic : €8.850804195756417
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- : VECTORTRIBUTE UNIPESSOAL, LDA : €9.718362068409439
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- ALACER, Mobiliário de Escritório, Lda. : €10.169767218727474
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- CLARANET PORTUGAL, S.A : €10.963257136596724
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- ENGIFRIO, SOCIEDADE DE REFRIGERAÇÃO, LDA : €11.230297266821127
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- EXITUS - SOLUÇÕES TECNOLÓGICAS, LDA. : €8.777555453213056
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- EXPT - SISTEMAS DE ENSINO E PESQUISA PARA LABORATÓRIO, LDA : €12.733755386362587
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- Gouveia Pereira, Costa Freitas &amp; Associados, Sociedade de Advogados, S.P., R.L. : €9.9281801651265
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- JMC Cleaning Services : €10.129586731675971
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- MODUTRONIC-Comércio de equipamentos Electrónicos LDA : €12.460714863903755
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- NAUTILUS S.A. : €10.454658641300215
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- Noveduc : €11.87114871963206
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- Noveduc - Material Didático Lda. : €10.308919326755392
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- OREY TÉCNICA-Serviços Navais, Lda : €10.90155928643844
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- QUATERNAIRE PORTUGAL, CONSULTORIA PARA O DESENVOLVIMENTO, S.AFórum Oceano - Associação da Economia do Mar : €11.399196699641886
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- RAAH - Services and Global Solutions, Lda : €9.877554170509624
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR) -- WAVELENGTH TECHNOLOGY CENTER, LDA : €9.82937265728152
  Comissão Nacional de Promoção dos Direitos e Proteção das Crianças e Jovens -- Valpi Rent, Lda. : €10.261420704598939
  Comissão para a Igualdade no Trabalho e no Emprego -- Ohmtécnica - Representações de Marcas, Lda : €5.075173815233827
  Direção-Geral da Segurança Social -- maquilotus-comercio de produtos de limpeza lda : €7.413029522309792
  Direção-Geral do Livro, dos Arquivos e das Bibliotecas -- - - NOA GmbH : €12.946009824594539
  Direção-Geral do Livro, dos Arquivos e das Bibliotecas -- Claranet II Solutions, S. A. : €13.909565559452686
  Direção-Geral do Tribunal de Contas -- CLARANET II SOLUTIONS, S.A. : €8.511496998871356
  Direção-Geral do Tribunal de Contas -- Zelo 2000 : €8.874727765766853
  Docapesca - Portos e Lotas, S. A. -- Avia-te ? Travel &amp; Events, Unipessoal Lda : €11.526039104115611
  Docapesca - Portos e Lotas, S. A. -- Market Access - Consultores em Negócio Internacional, Lda. : €11.829559359371776
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A. -- CITIRAMA - VIAGENS E TURISMO SA : €11.323216689742257
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A. -- ECM - MOBILIARIO URBANO S.A. : €11.329242982536933
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A. -- MERGING SELECT LDA : €10.398508132012998
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A. -- Maxiglobal - Equipamentos e Serviços de Informática, SA : €11.668676463603997
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A. -- NAN AUDIOVISUAIS - REPRESENTAÇÃO E DISTRIBUIÇÃO DE EQUIPAMENTOS : €11.97595545985258
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, EM, SA -- NAN AUDIOVISUAIS - REPRESENTAÇÃO E DISTRIBUIÇÃO DE EQUIPAMENTOS : €11.811336401772975
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, EM, SA -- STAGETEC - ESTRUTURAS ESPECIAIS, LDA : €10.992049505350737
  EMEL - EMPRESA MUNICIPAL DE MOBILIDADE E ESTACIONAMENTO DE LISBOA, E.M., S.A -- TIMESTAMP - SISTEMAS DE INFORMAÇÃO S.A. : €11.109698001466995
  ESNA - Europe Startup Nations Alliance, Associação -- BABEL IBÉRICA, S.A. : €12.534222849900223
  Edurumos, Educação, L.da -- Inforlandia S.A : €12.801248608864148
  Edurumos, Educação, L.da -- MEO - Serviços de Comunicações e Multimédia, S.AInforabreu, Lda, : €9.945110186459102
  Ensiprof - Ensino e Formação Profissional, L.da -- NAUTILUS, S.A : €10.024720187034527
  Ensiprof - Ensino e Formação Profissional, L.da -- RIS 2048 - Sistemas Informáticos e Comunicações, S.A : €12.534401097082725
  Entidade Orçamental -- Basedois-Informática e Telecomunicações, LDA : €10.487823827237893
  Entidade Orçamental -- Ohmtécnica - Representações de Marcas, Lda : €6.665123051084064
  Entidade Orçamental -- TOPTONER - Rec. e Comercialização Consumiveis Inf., Lda. : €5.902633333401366
  Escola Superior Náutica Infante D. Henrique -- Infosquad : €10.991708538137113
  Escola Superior Náutica Infante D. Henrique -- Ordem didática : €10.543278522886405
  Escola Superior Náutica Infante D. Henrique -- Wavecom, Soluções Rádio S.A. : €11.396388165562144
  Estrutura de Missão para a Extensão da Plataforma Continental -- VODAFONE PORTUGAL - Comunicações Pessoais, S.A. : €4.2414706271123945
  Faculdade de Arquitetura da Universidade de Lisboa -- RELOAD - CONSULTORIA INFORMÁTICA, UNIPESSOAL, LDA : €11.77475404752424
  Faculdade de Letras da Universidade de Lisboa -- APS - ESTUDOS PROJECTOS E MONTAGENS DE ILUMINAÇÃO, LDA. : €10.355322437721211
  Faculdade de Letras da Universidade de Lisboa -- EDNI  - Empresa Distribiudora de Material Informático, Lda : €8.035583268968203
  Faculdade de Letras da Universidade de Lisboa -- Exitus, Soluções Tecnológicas, Lda : €10.015534166340576
  Faculdade de Letras da Universidade de Lisboa -- MEO - Serviços de Comunicações e Multimédia, S.A. : €10.621983228109512
  Freguesia de Estrela -- Barraqueiro Transportes S.A : €12.092399901041597
  Freguesia de Estrela -- Graump - Maquinaria Industrial, Unipessoal Lda. : €12.211567521012135
  Freguesia de Estrela -- SMILE - VIAGENS E TURISMO, UNIPESSOAL, LDA : €12.02425096377787
  Freguesia de Marvila -- JPG - Transportes Unipessoal, Lda. : €12.27769538920314
  Freguesia de Silveira -- Meristema, SA : €11.44336057276776
  Fundação Centro Cultural de Belém -- Dcinema Unipessoal Lda : €11.320553572322773
  Fundação Centro Cultural de Belém -- Nan Audiovisuais - Representação e Distribuição de Equipamentos Audiovisuais, Lda. : €13.407459654567193
  Fundação Centro Cultural de Belém -- Ohmtécnica - Representações de Marcas, Lda : €7.897021341814079
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A. -- Autentifuturo - Restauros, Unipessoal, Lda : €11.12239822922627
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A. -- Crvm, Engenharia e Construção Unipessoal Lda : €10.927735425915376
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A. -- Rubricas Esplêndidas - Construções, Lda : €10.165851817003619
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A. -- Vínculo Perene – Engenharia e Construção, Lda : €11.335407193907288
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Autentifuturo - Restauros, Unipessoal, Lda : €10.735526731962691
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- COSMOTRIANGULAR LDA : €10.746691329302752
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- COSTA BRAGA, CONSTRUÇÕES UNIPESSOAL, LDA. : €11.211279685501061
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- CRVM, Engenharia e Construção Unipessoal, Lda : €11.122841458900366
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Casadarte Construção Civil  Lda : €10.777163016268934
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- DECLIVES E ARESTAS – Construções e Remodelações, Lda : €10.754595935591617
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Declives e Arestas – Construções e Remodelações, Lda : €10.682330661929695
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Horácio Mendes &amp; Bruno – Construções e Obras Públicas Lda : €10.64108214783137
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Juvenal Medeiros Lda – Construções e Remodelações Unipessoal Lda : €11.107278027630613
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Juvenal Medeiros, Construções &amp; Remodelações, Unipessoal : €11.07997096191945
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Margem Mítica-Manutenção e Reabilitação, Unipessoal, Lda : €10.645691046750661
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Metangular, Construções, Lda : €10.685412257861463
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Potencial Abcissa - Construções Unipessoal Lda : €10.9228543980539
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- RESPOSTA VERSÁTIL - Construção Civil Lda : €10.470970740806997
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Resposta Versátil, Lda : €10.815368575921584
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Rubricas Esplêndidas - Construções, Lda : €10.99650195482387
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A. -- Rúbricas Esplêndidas - Construções, Lda : €10.834363473060172
  Guarda Nacional Republicana -- - - Beatriz Soares Ribeiro : €8.699514748210191
  Guarda Nacional Republicana -- - - MARIO ANDRE GONÇALVES REIS : €9.487282928589401

## <font size=5>**3.4 Total Contracts Volume (Price) per Entity**</font> <a class="anchor" id="3.4"></a>
  
[Back to TOC](#toc)

In [24]:
volume = {node: 0 for node in G.nodes()}

# Step 2
for u, v, data in G.edges(data=True):
    volume[u] += data["weight"]
    volume[v] += data["weight"]

# Step 3
sorted_volume = sorted(volume.items(), key=lambda x: x[1], reverse=True)
print("Entity volume ranking:")
for entity, vol in sorted_volume:
    print(f"  {entity}: €{vol:,.0f}")

Entity volume ranking:
  Guarda Nacional Republicana: €646
  Secretaria-Geral do Ministério da Administração Interna: €303
  Serviços Municipalizados de Água e Saneamento de Sintra: €211
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A.: €184
  Casa Pia de Lisboa, I. P.: €177
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR): €171
  Instituto Nacional de Medicina Legal e Ciências Forenses, I. P.: €158
  Instituto Superior de Economia e Gestão: €142
  Santa Casa da Misericórdia de Lisboa: €136
  Agência para a Modernização Administrativa, I. P.: €121
  Instituto de Ação Social das Forças Armadas, I. P.: €119
  Serviços Intermunicipalizados de Águas e Resíduos dos Municípios de Loures e Odivelas: €119
  Município de Mafra: €112
  Ministério da Defesa Nacional - Marinha: €111
  CLARANET II SOLUTIONS, S.A.: €109
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P.: €100
  Município de Oeiras: €99
  ISEG - Instituto Superior de Economia e Gestão: €99
  Instituto da Mobilidade e dos Transportes, I. P.: €94
  Instituto Nacional de Estatística, I. P.: €92
  Município de Cascais: €89
  Município de Loures: €87
  Serviços Sociais da Administração Pública: €83
  Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P.: €81
  Autoridade para as Condições do Trabalho: €64
  Serviços Sociais da Guarda Nacional Republicana: €64
  Instituto Português do Mar e da Atmosfera, I. P.: €62
  Instituto de Informática, I. P.: €58
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A.: €57
  Município de Alenquer: €54
  Instituto de Proteção e Assistência na Doença, I. P.: €53
  Município da Amadora: €53
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM): €52
  Secretaria-Geral do MAI: €48
  Município de Odivelas: €47
  Escola Superior Náutica Infante D. Henrique: €44
  Serviços Intermunicipalizados de Água e Saneamento dos Municípios de Oeiras e Amadora: €44
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A.: €44
  Ohmtécnica - Representações de Marcas, Lda: €42
  Município do Cadaval: €41
  BASE2, LDA: €40
  HCCM CONSULTING, S.A.: €39
  Instituto de Gestão Financeira e Equipamentos da Justiça, I. P.: €39
  Faculdade de Letras da Universidade de Lisboa: €39
  SPMS - Serviços Partilhados do Ministério da Saúde, E. P. E.: €39
  Autoridade Tributária e Aduaneira: €39
  Instituto Português do Desporto e Juventude, I. P.: €38
  Imprensa Nacional - Casa da Moeda, S. A.: €37
  MEO - Serviços de Comunicações e Multimédia, S.A.: €37
  Secretaria-Geral do Ministério do Trabalho, Solidariedade e Segurança Social: €36
  Freguesia de Estrela: €36
  MULTIMAC HITO INNOVATION, S.A.: €36
  Planeta Vertical Lda: €36
  Warpcom Services, S.A.: €35
  RELOAD - Consultoria Informática, Unipessoal, Lda.: €35
  Infraestruturas de Portugal, S. A.: €35
  Serviços Sociais da GNR: €34
  INETUM ESPAÑA, S.A. - Sucursal em Portugal: €34
  Secretaria-Geral da Presidência da República: €34
  CONTENUR PORTUGAL,S.A.: €34
  Instituto Nacional de Investigação Agrária e Veterinária, I. P.: €33
  Agência para a Reforma Tecnológica do Estado, IP: €33
  Fundação Centro Cultural de Belém: €33
  Parques de Sintra - Monte da Lua, S. A.: €33
  Autoridade Nacional de Comunicações: €33
  Advanced Resources, Lda: €32
  Papelprint, lda: €32
  Laboratório Nacional de Engenharia Civil, I. P.: €29
  Município da Lourinhã: €29
  ACSS-Administração Central do Sistema de Saúde,IP: €29
  Centro de Formação Profissional da Reparação Automóvel: €29
  Exitus, Soluções Tecnológicas, Lda: €28
  Direção-Geral do Livro, dos Arquivos e das Bibliotecas: €27
  Vodafone Portugal, Comunicações Pessoais, S.A.: €27
  Instituto da Mobilidade e dos Transportes: €26
  XIX - Construção Projectos e Gestão, Lda.: €26
  Município de Sobral de Monte Agraço: €26
  IMPRENSA NACIONAL - CASA DA MOEDA SA: €25
  CRAYON SOFTWARE LICENSING, UNIPESSOAL LDA: €25
  Linkcom - Sistemas de Informacao, SA: €24
  Digibéria Information Technologies S.A.: €24
  AVVALE, UNIPESSOAL LDA: €24
  Carclasse - Comércio de Automóveis, S.a.: €24
  Fujitsu Technology Solutions, Lda: €24
  SAMSIC PORTUGAL - FACILITY SERVICES, S.A.: €24
  Serviços Municipalizados de Sintra (SMAS): €24
  Polícia de Segurança Pública: €24
  NAN AUDIOVISUAIS - REPRESENTAÇÃO E DISTRIBUIÇÃO DE EQUIPAMENTOS: €24
  AXIANSEU DIGITAL SOLUTIONS, S.A.: €24
  SEBASI - Sistemas de Informação, SA: €23
  Docapesca - Portos e Lotas, S. A.: €23
  Sopsa Eco Innovation, S.a: €23
  Renault Portugal, S.A.: €23
  NOI, LDA: €23
  Timestamp – Sistemas de Informação, S.A.: €23
  Entidade Orçamental: €23
  IBERAGAR S.A.: €23
  INSTITUTO DA MOBILIDADE E DOS TRANSPORTES, I.P. (IMT, I.P.): €23
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, EM, SA: €23
  JMC Cleaning Services: €23
  Edurumos, Educação, L.da: €23
  Ensiprof - Ensino e Formação Profissional, L.da: €23
  TML - Transportes Metropolitanos de Lisboa, E. M. T., S. A.: €22
  BRAVANTIC, SA: €22
  IDONEOS, LDA.: €22
  Instituto para os Comportamentos Aditivos e as Dependências, I. P.: €22
  Cascais Próxima - Gestão de Mobilidade, Espaços Urbanos e Energias, E. M., S. A.: €22
  Autoridade Nacional de Segurança Rodoviária: €22
  Código Azul, Lda: €22
  Autentifuturo - Restauros, Unipessoal, Lda: €22
  Tecnirede, Comunicação de Dados S. A.: €22
  Laboratório Nacional de Engenharia Civil, IP: €22
  BASEDOIS - Informática e Telecomunicações, Lda.: €22
  CHIEF SECURITY OFFICERS S.A.: €21
  Superintendência do Material - Direção de Infraestruturas: €21
  Rubricas Esplêndidas - Construções, Lda: €21
  Agência para a Modernização Administrativa, I.P.: €21
  LNEC - Laboratório Nacional de Engenharia Civil,IP: €21
  Eurest Portugal Lda: €21
  Autoridade da Mobilidade e dos Transportes: €21
  PETROGAL, S.A.: €21
  RIS 2048 - Sistemas Informáticos e Comunicações, S.A: €20
  PERENE, S.A.: €20
  EDNI  - Empresa Distribiudora de Material Informático, Lda: €20
  Exitus, Soluções Tecnológicas, Lda.: €20
  Casobra, lda: €20
  Nautiradar - Sistemas Marítimos de Electrónica e de Telecomunicações, Lda.: €20
  ADENE - Agência para a Energia: €20
  NTG, Lda.: €20
  Knowledge Inside, Lda: €20
  SUCH | Serviço de Utilização Comum dos Hospitais: €20
  Gestinventos - Energias e Representações de Equipamentos, Unipessoal, Lda: €19
  VNeto - Soluções, Lda.: €19
  ANTERO LOPES, LDA: €18
  Megabarcelos – Informática e Tecnologia, Unipessoal, Lda: €18
  Direção-Geral do Tribunal de Contas: €17
  Centro de Emprego e Formação Profissional de Santarém: €17
  Casa Pia de Lisboa, IP: €15
  CASA PIA DE LISBOA, I.P.: €15
  Paldata, SA: €15
  INSTITUTO DE PROTEÇAO E ASSISTENCIA NA DOENÇA IP ADSE IP: €15
  NÓS COMUNICAÇÕES S.A.: €15
  Instituto do Emprego e Formação Profissional, IP: €15
  INETUM ESPAÑA, S.A. - SUCURSAL EM PORTUGAL: €15
  Claranet II Solutions, S. A.: €14
  VÓRTICE, EQUIPAMENTOS CIENTÍFICOS, LDA.: €14
  Cascais Dinâmica - Gestão de Economia, Turismo e Empreendorismo, E. M., S. A.: €14
  SMA-Segurança Privada, S.A.: €14
  Tecradio,Lda: €14
  Nan Audiovisuais - Representação e Distribuição de Equipamentos Audiovisuais, Lda.: €13
  Navallethes, Lda: €13
  SIBAFIL, LDA: €13
  CONSTRUÇÕES PRAGOSA, S.A.: €13
  AdP Valor - Serviços Ambientais, S. A.: €13
  CERTOMA - Comércio Técnico Máquinas, Lda: €13
  Sibafil – Sociedade de Empreitadas, Lda: €13
  UNIKONSTROI, LDA.,: €13
  BOLDINT, S.A.: €13
  ARTE - Agência para a Reforma Tecnológica do Estado: €13
  Simopeças - Peças e Componentes para Viaturas de Limpeza Urbana, Lda.: €13
  Homeostase 2 Intelligence, Lda.: €13
  Centro de Emprego e Formação Profissional de Setúbal: €13
  WWS - Consultoria Informática, Lda: €13
  Agrupamento de Escolas José Afonso, Loures: €13
  Beltrão Coelho – Sistemas de Escritório, Lda: €13
  Lisboa Ocidental, SRU - Sociedade de Reabilitação Urbana E. M., S. A.: €13
  Pemofam - Facility Services, Lda.: €13
  - - NOA GmbH: €13
  IMPRENSA NACIONAL CASA DA MOEDA: €13
  - - J. VILASECA, SA: €13
  Águas do Vale do Tejo, S. A.: €13
  Ripórtico - Engenharia, Lda: €13
  EUGREB INVEST, LDA: €13
  CARLOS RAMOS MARQUES -: €13
  Ediperfil: €13
  Janz - Contagem e Gestão de Fluídos, S.A.: €13
  Inforlandia S.A: €13
  BLUEOTTER CIRCULAR, S.A.: €13
  TMLJ - FACILITY SERVICES, UNIPESSOAL LDA: €13
  INSTITUTO DE GESTÃO FINANCEIRA E EQUIPAMENTOS DA JUSTIÇA, I.P.: €13
  Polícia Judiciária: €13
  EVONIC - EVOLUTION AND INNOVATION CONSULTING, LDA: €13
  Oramix Sistemas de Informação S.A: €13
  EXPT - SISTEMAS DE ENSINO E PESQUISA PARA LABORATÓRIO, LDA: €13
  LIVRARIA E PAPELARIA NOVA, UNIPESSOAL, LDA.: €13
  Know How - Sociedade de Ensino de LÃ­nguas e Acção Social, Unipessoal Lda.: €13
  - - J.VILASECA, SA: €13
  Litovale, Ldª.: €13
  Strongplan, Lda: €13
  Reditus Networks Innovation, Lda: €13
  Protecnil - Sociedade Tecnica de Construções, SA: €13
  MEO - Serviços de Comunicações e Multimédia, S.A: €13
  ESNA - Europe Startup Nations Alliance, Associação: €13
  BABEL IBÉRICA, S.A.: €13
  MODUTRONIC-Comércio de equipamentos Electrónicos LDA: €12
  NORS VT Trucks and Buses, S.A.: €12
  Costa &amp; Porfírio, Lda: €12
  Universidade do Minho: €12
  SCHMID – CONSTRUÇÕES, Lda.: €12
  Claranet Portugal, S.A.: €12
  Obrimix - Calçadas E Construções Lda: €12
  TOPTONER - Rec. e Comercialização Consumiveis Inf., Lda.: €12
  AVVALE, UNIPESSOAL, LDA: €12
  Freguesia de Marvila: €12
  JPG - Transportes Unipessoal, Lda.: €12
  Irlandox Laboratórios de Química Analítica, Lda.: €12
  Centro de Emprego de Matosinhos: €12
  ORAMIX – SISTEMAS DE INFORMAÇÃO, S.A.: €12
  Graump - Maquinaria Industrial, Unipessoal Lda.: €12
  Shield Domain, S.A.: €12
  TECNIREDE COMUNICAÇÃO DE DADOS LDA: €12
  Olimec, Lda.: €12
  Simopeças: €12
  BARRAQUEIRO TRANSPORTES, S.A.: €12
  CNMF &amp; Associados, SP, RL: €12
  Instituto Superior de Engenharia de Lisboa: €12
  Agência para o Investimento e Comércio Externo de Portugal, E. P. E.: €12
  MOVEGREAT TRANSPORTS: €12
  Hewlett-Packard Portugal, s.A.: €12
  Barraqueiro Transportes S.A: €12
  Instituto Nacional de Estatística, IP: €12
  IDW – Consultoria em Serviços de Informação, Lda.: €12
  Bricantel, Comércio de Material Electrico de Bragança, S.A.: €12
  CLARANET PORTUGAL, S.A.: €12
  Associação de Promoção da Região Autónoma da Madeira: €12
  Diretriz Duradoura, Lda.: €12
  INETUM ESPAÑA, S.A - SUCURSAL EM PORTUGAL: €12
  SMILE - VIAGENS E TURISMO, UNIPESSOAL, LDA: €12
  Goldfarma- Comércio de Produtos Farmacêuticos Lda.: €12
  Hewlett-Packard: €12
  OMEP-OBRAS MEDIÇÕES E PROJETOS, LDª: €12
  Fidelidade, SA: €12
  Tecnilab AV Portugal, SA: €12
  RENAULT PORTUGAL SA: €12
  MC Computadores, S.A.: €12
  Instituto Superior Técnico: €12
  PRN Informática, Lda.: €12
  Pinto &amp; Cruz - Motores e Equipamentos, SA: €12
  BAJOMICO-ORG HOTEL E SIMILARES LDA: €12
  Noveduc: €12
  Movex - Produção, Venda e Aluguer de Módulos Pre Fabricados, SA: €12
  RASO-VIAGENS E TURISMO, S.A.: €12
  MARINHA - Direção de Navios: €12
  SHAMROCK LDA: €12
  Lucena &amp; Lucena, Lda: €12
  CLARANET II Solutions, S.A.: €12
  Market Access - Consultores em Negócio Internacional, Lda.: €12
  M.R.A. INSTRUMENTAÇAO PARA MEDIÇAO, REGISTO E ANALISES,SA: €12
  RELOAD - CONSULTORIA INFORMÁTICA, LDA.: €12
  Petrogal, S.A.: €12
  FLOW SYSTEMS - SISTEMAS DE MEDIÇÃO DE FLUÍDOS, UNIPESSOAL, LDA.: €12
  Faculdade de Arquitetura da Universidade de Lisboa: €12
  RELOAD - CONSULTORIA INFORMÁTICA, UNIPESSOAL, LDA: €12
  RHMais, SA: €12
  PDM E FC-PROJECTO DESENVOLVIMENTO MANUTENÇÃO FORMAÇÃO E CONSULTADORIA S.A.: €12
  GENERALI SEGUROS, SA: €12
  Science4you, S.A.: €12
  INCM - Imprensa Nacional-Casa da Moeda, S.A.: €12
  Almeida &amp; Neves, Lda: €12
  Interessantequação Produtos Consultoria e Serviços Lda: €12
  A. Barreira, Lda.: €12
  RSF, Têxteis, Lda: €12
  SHIELD DOMAIN, S.A.: €12
  Lactogal-Produtos Alimentares, SA: €12
  Instituto para os Comportamentos Aditivos e as Dependências, I.P.: €12
  Maxiglobal - Equipamentos e Serviços de Informática, SA: €12
  Nova Expressão - Planeamento de Media e Publicidade, S.A.: €12
  Motivo - Comércio e Motivação de Mercados, S. A.: €12
  Provedoria de Justiça: €12
  SPIR - Sociedade Portuguesa de Inovação em Restauração Unipessoal, Lda: €12
  Xanauto - Comércio de Veículos Automóveis, Unipessoal Lda: €12
  Amigalecrim: €12
  Fidelidade - Companhia de Seguros, S.A.: €12
  INETUM ESPAÑA S.A. - SUCURSAL EM PORTUGAL: €12
  Izumix - Unipessoal Ldª: €12
  TROPICHANCE - Metalúrgica e Construções, Lda.: €12
  Diversões Simões &amp; Filhos, Lda: €12
  Avia-te ? Travel &amp; Events, Unipessoal Lda: €12
  MDN - Direção-Geral da Autoridade Marítima: €12
  Azores Sub, LDA: €12
  PRF - Gás, Tecnologia e Construção, SA: €12
  Claranet II Solutions, S.A: €12
  Euphoric Flash Unipessoal Lda: €12
  PRN - INFORMATICA LDA: €11
  JOPIRAMOS, UNIPESSOAL LDA: €11
  PlanetaVertical, Lda: €11
  Shield Domain, SA: €11
  Fachaimper Lda: €11
  Logicalis Portugal, S.A.: €11
  Misterioportuno Unipessoal Lda: €11
  Instituto do Emprego e da Formação Profissional, I. P.: €11
  Freitas Rosa, Lda.: €11
  Freguesia de Silveira: €11
  Meristema, SA: €11
  FUNEREXPRESS, LDA: €11
  Pedcarsegur Unipessoal Lda.: €11
  QUATERNAIRE PORTUGAL, CONSULTORIA PARA O DESENVOLVIMENTO, S.AFórum Oceano - Associação da Economia do Mar: €11
  MOTICRISTO: €11
  Wavecom, Soluções Rádio S.A.: €11
  Novo Corpo Exercício Físico e Reabilitação Lda: €11
  Timestamp - Sistemas de Informação, S.A.: €11
  Globaltendas, Lda: €11
  Centro Humanitário Vale do Dão da Cruz Vermelha Portuguesa: €11
  MEDICINALIA CORMEDICA (CORMEDICA): €11
  Especial 1 Segurança Privada S.A.: €11
  Vínculo Perene – Engenharia e Construção, Lda: €11
  ECM - MOBILIARIO URBANO S.A.: €11
  CITIRAMA - VIAGENS E TURISMO SA: €11
  Prosonic - Produtos de Imagem e Comunicação S.A.: €11
  Dcinema Unipessoal Lda: €11
  AUTOGIRAR - SOC COMERCIAL AUTOMOVEIS LDA: €11
  Blue Ocean Medical Rescue, Ld.ª: €11
  PH Informática: €11
  Instituto Nacional da Propriedade Industrial, I. P.: €11
  Raso - Viagens e Turismo, S.A.: €11
  Openline Facility Services, S.A.: €11
  Pricewaterhouse/AG - Assessoria de Gestão, Lda.: €11
  Nonstop Tradition, Unipessoal, Lda.: €11
  Solvit - Innovation Development On Telecommunications Lda: €11
  SIMAR – Serviços Intermunicipalizados de Loures e Odivelas: €11
  ENERMETER-SISTEMAS MEDIÇAO, LDA: €11
  LITORAL LEITURAS LDA: €11
  M.COUTINHO NORDESTE-COMERCIO DE AUTOMÓVEIS,S.A.: €11
  ENGIFRIO, SOCIEDADE DE REFRIGERAÇÃO, LDA: €11
  IDW - CONSULTORIA EM SERVIÇOS DE INFORMAÇÃO, LDA.: €11
  CONSUMA EUROPA FOODS, UNIPESSOAL: €11
  BRAVANTIC EVOLVING TECHNOLOGY, SA: €11
  Alive Portugal, S.A.: €11
  DOT Viagens e Turismo, Lda: €11
  União para Acção Cultural e Juvenil Educativa: €11
  SMILE - VIAGENS E TURISMO UNIPESSOAL LDA: €11
  COSTA BRAGA, CONSTRUÇÕES UNIPESSOAL, LDA.: €11
  INDRA Sistemas Portugal, S.A.: €11
  Mega Local, Lda: €11
  CYBEROPS, LDA.: €11
  Árvores &amp;amp; Pessoas - Gestão Árvore Espaço Urbano: €11
  Timestamp – Sistemas de Informação, S.A.,: €11
  Anditec Tecnologias Reabilitação, Lda: €11
  LOCARENT - COMPANHIA PORTUGUESA DE ALUGUER DE VIATURAS, S.A.: €11
  Toyota Caetano Portugal: €11
  CRVM, Engenharia e Construção Unipessoal, Lda: €11
  Instituto da Mobilidade e dos Transportes, IP: €11
  DOT Viagens e Turismo, Lda.: €11
  EMEL - EMPRESA MUNICIPAL DE MOBILIDADE E ESTACIONAMENTO DE LISBOA, E.M., S.A: €11
  TIMESTAMP - SISTEMAS DE INFORMAÇÃO S.A.: €11
  Juvenal Medeiros Lda – Construções e Remodelações Unipessoal Lda: €11
  Juvenal Medeiros, Construções &amp; Remodelações, Unipessoal: €11
  - - EBSCO Information Services S.L.U.: €11
  IP - Infraestruturas de Portugal, S.A.: €11
  Inforlandia - Sistemas e Serviços de Informática, S.A.: €11
  Micotec - Electrónica, Lda: €11
  STAGETEC - ESTRUTURAS ESPECIAIS, LDA: €11
  Infosquad: €11
  TOP PARTNER - VIAGENS &amp; SOLUÇÕES EMPRESARIAIS, S.A.: €11
  ConfigBit - Soluções Tecnologicas, Lda: €11
  Mendes &amp; Irmãos, S.A.: €11
  CLARANET PORTUGAL, S.A: €11
  Carmo Estruturas em Madeira, S.A.: €11
  Periodic Table of Events, lda: €11
  STROBOSOM, Lda.: €11
  Waste To Me, Unipessoal, Lda.: €11
  Crvm, Engenharia e Construção Unipessoal Lda: €11
  MEO - Serviços de Comunicações Multimédia, S.A.: €11
  Potencial Abcissa - Construções Unipessoal Lda: €11
  RIS 2048 - Sistemas Informáticos e Comunicações, S.A.: €11
  ECO IMPACT, S.A.: €11
  OREY TÉCNICA-Serviços Navais, Lda: €11
  Centro de Emprego e Formação Profissional de Leiria: €11
  BOLDINT, S.A., by Devoteam: €11
  Auto Reno Minho Comercio de Automóveis Lda.: €11
  LUSITÂNIA - COMPANHIA DE SEGUROS, S.A: €11
  ECOAMBIENTE - SERVIÇOS E MEIO AMBIENTE, S.A.: €11
  Rúbricas Esplêndidas - Construções, Lda: €11
  Resposta Versátil, Lda: €11
  GLFV Unipessoal Lda: €11
  Casadarte Construção Civil  Lda: €11
  DECLIVES E ARESTAS – Construções e Remodelações, Lda: €11
  COSMOTRIANGULAR LDA: €11
  José Silva Carvalho - Catering, S.A.: €11
  Alexandre Martos Martinez: €11
  Etnaga - Consultores Sistemas de Informação, Lda: €11
  JOSE CARLOS ANDRÉ TRANSPORTES LDA: €11
  maquilotus-comercio de produtos de limpeza lda: €11
  Ageas Portugal, Companhia de Seguros, SA: €11
  Metangular, Construções, Lda: €11
  Declives e Arestas – Construções e Remodelações, Lda: €11
  RRI - SERVIÇOS AMBIENTAIS, S. A.: €11
  Isoroof - Impermeabilizações Unipessoal, Lda.: €11
  AMBISIG - Ambiente e Sistemas de Informação Geográfica, S.A: €11
  Instituto Nacional de Estatística, IP (INE): €11
  Margem Mítica-Manutenção e Reabilitação, Unipessoal, Lda: €11
  - - Sérgio José Mamede Gonçalves: €11
  SANTOMARGO - CONSTRUÇÕES, LDA.: €11
  Horácio Mendes &amp; Bruno – Construções e Obras Públicas Lda: €11
  Manuel Gonzalez Martins &amp;amp; Filhos, S.A.: €11
  WRDN - Serviços de Assistência e Manutenção Global Unipessoal, Lda.: €11
  Leiridiesel- Comércio e Rep. de Autom., SA: €11
  NOVA EXPRESSÃO- Planeamento de Meios e Publicidade , S.A.: €11
  CRC - Car Rental Company, Lda.: €11
  Lusodoc: €11
  ESTERIPLAS, LDA.: €11
  deltagel: €11
  NOESIS PORTUGAL - CONSULTADORIA EM SISTEMAS INFORMÁTICOS, S.A.: €11
  Gartécnica Unip. Lda: €11
  NAUTILUS, S.A.: €11
  Ordem didática: €11
  Oceano Franzino, Lda: €11
  Sigmadetalhe, Lda: €11
  Contisystems Tecnologias de Informação SA: €10
  Basedois-Informática e Telecomunicações, LDA: €10
  RESPOSTA VERSÁTIL - Construção Civil Lda: €10
  Tronicom Lda: €10
  Axianseu Digital Solutions, S.A: €10
  MARL - Mercado Abastecedor da Região de Lisboa, S. A.: €10
  UNNISA- REVESTIMENTOS, MANUTENÇÃO E CONSTRUÇÃO S.A: €10
  Specanalítica - Equipamentos Analíticos, Lda: €10
  Lucstockfood, Venda e Distribuição Alimentar Unipessoal, Lda.: €10
  NAUTILUS S.A.: €10
  NAUTITEJO, LDA: €10
  inCentea - Tecnologia de Gestão, SA: €10
  Xpand Solutions - Informática e Novas Tecnologias, LDA: €10
  REDSHIFT CONSULTING, Lda: €10
  SMILE - VIAGENS E TURISMO, UNIPESSOAL LDA: €10
  MERGING SELECT LDA: €10
  Unidade Local de Saúde de Lisboa Ocidental, E. P. E.: €10
  GETINGE GROUP PORTUGAL,UNIPESSOAL, LDA.: €10
  Arquirenova Reabilitação Edificios Estruturas Aços Leves: €10
  Jorge Fernandes, Lda.: €10
  MARINHA - Direção de Abastecimento: €10
  Reta- Serviços Técnicos e Rent-a-cargo, S.A.: €10
  APS - ESTUDOS PROJECTOS E MONTAGENS DE ILUMINAÇÃO, LDA.: €10
  Tiberone Portugal, Lda.: €10
  ConfigBit, Lda: €10
  PREMIUM GREEN MAIL, LDA: €10
  Instituto Hidrográfico: €10
  MarSensing, Lda.: €10
  Armasul, Distribuidor de Materiais Electricos, S.A.: €10
  Noveduc - Material Didático Lda.: €10
  ASC - Arménio Salgado Costa Comércio de Produtos de Higiene, Lda.: €10
  A. Gouv - Reparação e Manutenção de Veiculos, Lda: €10
  Claranet II Solutions, SA: €10
  SFS, GESTÃO E CONSULTORIA, S.A.: €10
  Paulo Silva Santos - Engenharia e Construções, Lda.: €10
  ANTÃO MEDICAL - EQUIPAMENTOS MÉDICO-CIRÚRGICOS, LDA.: €10
  Comissão Nacional de Promoção dos Direitos e Proteção das Crianças e Jovens: €10
  Valpi Rent, Lda.: €10
  WPP Media: €10

## <font size=5>**3.5 Degree VS Volume**</font> <a class="anchor" id="3.5"></a>
  
[Back to TOC](#toc)

- Degree $\rightarrow$ number of contracts associated with each entity (network degree = in_degree + out_degree)
- Volume $\rightarrow$ total contracted amount associated with each entity (sum of incident edge weights)

**Purpose**: assess which entities are most valuable and how activity (degree) relates to economic impact (volume).

Planned steps:
- compute degree and volume per node
- plot degree vs. volume (use log–log scatter), annotate top entities
- report Pearson and Spearman correlations
- fit a linear model on log-transformed values and flag outliers (high volume/low degree and high degree/low volume)

In [25]:
# Degree and volume per node
metrics = pd.DataFrame({
    "degree": pd.Series(dict(G.degree())),
    "volume": pd.Series(volume)
}).fillna(0)

In [26]:
# Keep only positive values for log-log analysis
pos = metrics[(metrics["degree"] > 0) & (metrics["volume"] > 0)].copy()
pos["log_degree"] = np.log10(pos["degree"])
pos["log_volume"] = np.log10(pos["volume"])

# Correlations on log-transformed values
pearson = pos["log_degree"].corr(pos["log_volume"], method="pearson")
spearman = pos["log_degree"].corr(pos["log_volume"], method="spearman")

print(f"Nodes used in log-log analysis: {len(pos)}")
print(f"Pearson correlation (log10):  {pearson:.4f}")
print(f"Spearman correlation (log10): {spearman:.4f}")

Nodes used in log-log analysis: 641
Pearson correlation (log10):  0.9593
Spearman correlation (log10): 0.7202

In [27]:
# Linear model in log-log space
slope, intercept = np.polyfit(pos["log_degree"], pos["log_volume"], 1)
pos["pred_log_volume"] = intercept + slope * pos["log_degree"]
pos["residual"] = pos["log_volume"] - pos["pred_log_volume"]

print(f"\nlog10(volume) = {intercept:.4f} + {slope:.4f} * log10(degree)")

log10(volume) = 1.0177 + 1.0032 * log10(degree)

In [28]:
# Flag outliers using the box-plot rule (IQR)
degree_dict = dict(G.degree())

q1 = pd.Series(volume).quantile(0.25)
q3 = pd.Series(volume).quantile(0.75)
iqr = q3 - q1
volume_threshold = q3 + 1.5 * iqr

print(f"Volume threshold from box plot rule: €{volume_threshold:,.0f}")
print("Flagged entities (degree ≥ 3 AND volume above upper fence):")

flagged = []
for entity in G.nodes():
    if degree_dict[entity] >= 3 and volume[entity] > volume_threshold:
        flagged.append((entity, degree_dict[entity], volume[entity]))

flagged.sort(key=lambda x: x[2], reverse=True)
for entity, deg, vol in flagged:
    print(f"  {entity}  degree={deg}  volume=€{vol:,.0f}")

print(f"\nTotal flagged: {len(flagged)}")

Volume threshold from box plot rule: €18
Flagged entities (degree ≥ 3 AND volume above upper fence):
  Guarda Nacional Republicana  degree=66  volume=€646
  Secretaria-Geral do Ministério da Administração Interna  degree=28  volume=€303
  Serviços Municipalizados de Água e Saneamento de Sintra  degree=19  volume=€211
  Gebalis - Gestão do Arrendamento da Habitação Municipal de Lisboa, E. M., S. A.  degree=17  volume=€184
  Casa Pia de Lisboa, I. P.  degree=18  volume=€177
  Centro de Formação Profissional das Pescas e do Mar (FOR-MAR)  degree=16  volume=€171
  Instituto Nacional de Medicina Legal e Ciências Forenses, I. P.  degree=18  volume=€158
  Instituto Superior de Economia e Gestão  degree=16  volume=€142
  Santa Casa da Misericórdia de Lisboa  degree=15  volume=€136
  Agência para a Modernização Administrativa, I. P.  degree=12  volume=€121
  Instituto de Ação Social das Forças Armadas, I. P.  degree=11  volume=€119
  Serviços Intermunicipalizados de Águas e Resíduos dos Municípios de Loures e Odivelas  degree=11  volume=€119
  Município de Mafra  degree=10  volume=€112
  Ministério da Defesa Nacional - Marinha  degree=11  volume=€111
  CLARANET II SOLUTIONS, S.A.  degree=11  volume=€109
  Agência Nacional para a Qualificação e o Ensino Profissional, I. P.  degree=11  volume=€100
  Município de Oeiras  degree=9  volume=€99
  ISEG - Instituto Superior de Economia e Gestão  degree=10  volume=€99
  Instituto da Mobilidade e dos Transportes, I. P.  degree=9  volume=€94
  Instituto Nacional de Estatística, I. P.  degree=8  volume=€92
  Município de Cascais  degree=8  volume=€89
  Município de Loures  degree=7  volume=€87
  Serviços Sociais da Administração Pública  degree=8  volume=€83
  Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P.  degree=9  volume=€81
  Autoridade para as Condições do Trabalho  degree=6  volume=€64
  Serviços Sociais da Guarda Nacional Republicana  degree=6  volume=€64
  Instituto Português do Mar e da Atmosfera, I. P.  degree=5  volume=€62
  Instituto de Informática, I. P.  degree=6  volume=€58
  EGEAC - Empresa de Gestão de Equipamentos e Animação Cultural, E. M., S. A.  degree=5  volume=€57
  Município de Alenquer  degree=5  volume=€54
  Instituto de Proteção e Assistência na Doença, I. P.  degree=6  volume=€53
  Município da Amadora  degree=4  volume=€53
  Centro de Formação Profissional da Industria Metalúrgica e Metalomecânica (CENFIM)  degree=5  volume=€52
  Secretaria-Geral do MAI  degree=4  volume=€48
  Município de Odivelas  degree=4  volume=€47
  Escola Superior Náutica Infante D. Henrique  degree=4  volume=€44
  Serviços Intermunicipalizados de Água e Saneamento dos Municípios de Oeiras e Amadora  degree=4  volume=€44
  GEBALIS - Gestão do Arrendamento da Habitação Municipal de Lisboa, E.M., S.A.  degree=4  volume=€44
  Ohmtécnica - Representações de Marcas, Lda  degree=6  volume=€42
  Município do Cadaval  degree=4  volume=€41
  BASE2, LDA  degree=4  volume=€40
  HCCM CONSULTING, S.A.  degree=3  volume=€39
  Instituto de Gestão Financeira e Equipamentos da Justiça, I. P.  degree=3  volume=€39
  Faculdade de Letras da Universidade de Lisboa  degree=4  volume=€39
  SPMS - Serviços Partilhados do Ministério da Saúde, E. P. E.  degree=3  volume=€39
  Autoridade Tributária e Aduaneira  degree=3  volume=€39
  Instituto Português do Desporto e Juventude, I. P.  degree=3  volume=€38
  Imprensa Nacional - Casa da Moeda, S. A.  degree=4  volume=€37
  MEO - Serviços de Comunicações e Multimédia, S.A.  degree=3  volume=€37
  Secretaria-Geral do Ministério do Trabalho, Solidariedade e Segurança Social  degree=3  volume=€36
  Freguesia de Estrela  degree=3  volume=€36
  MULTIMAC HITO INNOVATION, S.A.  degree=3  volume=€36
  Planeta Vertical Lda  degree=4  volume=€36
  Warpcom Services, S.A.  degree=3  volume=€35
  RELOAD - Consultoria Informática, Unipessoal, Lda.  degree=3  volume=€35
  Infraestruturas de Portugal, S. A.  degree=3  volume=€35
  Serviços Sociais da GNR  degree=3  volume=€34
  INETUM ESPAÑA, S.A. - Sucursal em Portugal  degree=3  volume=€34
  Secretaria-Geral da Presidência da República  degree=3  volume=€34
  CONTENUR PORTUGAL,S.A.  degree=3  volume=€34
  Instituto Nacional de Investigação Agrária e Veterinária, I. P.  degree=3  volume=€33
  Agência para a Reforma Tecnológica do Estado, IP  degree=3  volume=€33
  Fundação Centro Cultural de Belém  degree=3  volume=€33
  Parques de Sintra - Monte da Lua, S. A.  degree=3  volume=€33
  Autoridade Nacional de Comunicações  degree=3  volume=€33
  Advanced Resources, Lda  degree=3  volume=€32
  Papelprint, lda  degree=4  volume=€32
  Laboratório Nacional de Engenharia Civil, I. P.  degree=3  volume=€29
  Município da Lourinhã  degree=3  volume=€29
  ACSS-Administração Central do Sistema de Saúde,IP  degree=3  volume=€29
  Centro de Formação Profissional da Reparação Automóvel  degree=3  volume=€29
  Exitus, Soluções Tecnológicas, Lda  degree=3  volume=€28
  Entidade Orçamental  degree=3  volume=€23
  EDNI  - Empresa Distribiudora de Material Informático, Lda  degree=3  volume=€20

Total flagged: 74

In [29]:
# Plotting

# prepare fit line
x_line = np.logspace(np.log10(pos["degree"].min()), np.log10(pos["degree"].max()), 200)
y_line = 10 ** (intercept + slope * np.log10(x_line))

# main traces
scatter = go.Scatter(
    x=pos["degree"],
    y=pos["volume"],
    mode="markers",
    marker=dict(size=6, color="steelblue", opacity=0.5),
    name="nodes",
    hovertemplate="%{text}<br>Degree: %{x}<br>Volume: €%{y:,.0f}",
    text=pos.index
)

fit_line = go.Scatter(
    x=x_line,
    y=y_line,
    mode="lines",
    line=dict(color="crimson", width=2),
    name="log-log fit"
)

# annotations for top entities
annotations = []
top_entities = [entity for entity, _ in top5]

for node in top_entities:
    x = metrics.loc[node, "degree"]
    y = metrics.loc[node, "volume"]
    annotations.append(
        dict(
            x=x,
            y=y,
            text=node,
            showarrow=True,
            arrowhead=2,
            ax=10,
            ay=-10,
            font=dict(size=10),
        )
    )

fig = go.Figure(data=[scatter, fit_line])
fig.update_layout(
    title="Degree VS Volume",
    xaxis=dict(title="Degree", type="log"),
    yaxis=dict(title="Volume (€)", type="log"),
    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_layout(
    title="Degree vs Volume",
    
    xaxis=dict(
        title="Degree",
        type="log",
        dtick=1,              # only 10^n ticks → 1, 10, 100, 1000
        tickformat=".0f"      # show full numbers instead of scientific notation
    ),
    
    yaxis=dict(
        title="Volume (€)",
        type="log",
        dtick=1,
        # tickformat=".0f"
    ),

    annotations=annotations,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=60, r=20, t=60, b=60)
)

fig.update_xaxes(showgrid=True, gridwidth=1)
fig.update_yaxes(showgrid=True, gridwidth=1)

fig.show()

In [30]:
# TODO: add attribute adjudicante/adjudicatario to hoover in plot and maybe change the color of the point based on it

**NETWORK MUNICIPALITY**

In [46]:
import pandas as pd
import numpy as np
import networkx as nx


# =========================================================
# 1. INPUT HANDLING (DICT / LIST / DF SAFE)
# =========================================================
def ensure_dataframe(data):

    if isinstance(data, pd.DataFrame):
        return data.copy()

    if isinstance(data, list):
        return pd.DataFrame(data)

    if isinstance(data, dict):
        # dict of dataframes
        for v in data.values():
            if isinstance(v, pd.DataFrame):
                return v.copy()

        # dict of records
        return pd.DataFrame(data)

    raise TypeError(f"Unsupported input type: {type(data)}")


# =========================================================
# 2. WEIGHT FUNCTION
# =========================================================
def compute_weight(x, mode="log_sum"):
    x = np.array(x)

    if mode == "log_sum":
        return np.log1p(x).sum()
    elif mode == "sum":
        return x.sum()
    elif mode == "mean":
        return x.mean()
    else:
        raise ValueError("Unknown weight mode")


def standardize_contract_data(df):

    df = df.copy()

    # =====================================================
    # 1. SOURCE (company)
    # =====================================================
    if 'source_company' in df.columns:
        pass

    elif 'adjudicante' in df.columns:
        df['source_company'] = df['adjudicante']

    elif 'source' in df.columns:
        df['source_company'] = df['source']

    elif 'adjudicatarios' in df.columns:
        # fallback case where structure is inverted/mixed
        df['source_company'] = df['adjudicante'] if 'adjudicante' in df.columns else np.nan

    else:
        raise ValueError(f"Cannot find source column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 2. TARGET (company)
    # =====================================================
    if 'target_company' in df.columns:
        pass

    elif 'adjudicatarios' in df.columns:
        df['target_company'] = df['adjudicatarios']

    elif 'target' in df.columns:
        df['target_company'] = df['target']

    else:
        raise ValueError(f"Cannot find target column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 3. PRICE
    # =====================================================
    if 'price' in df.columns:
        pass

    elif 'precoContratual' in df.columns:
        df['price'] = df['precoContratual']

    else:
        raise ValueError(f"Cannot find price column. Columns: {df.columns.tolist()}")

    # =====================================================
    # 4. CLEAN
    # =====================================================
    required = ['source_company', 'target_company', 'price']

    df = df.dropna(subset=required)
    df = df[df['price'] > 0]

    return df





# =========================================================
# 5. MUNICIPALITY NETWORK
# =========================================================
def build_municipality_network(data, weight_mode="log_sum"):

    df = ensure_dataframe(data)
    df = standardize_contract_data(df)

    if 'city' not in df.columns:
        raise ValueError("Missing 'city' column")

    df['source_municipality'] = df['city']
    df['target_company'] = df['target_company']

    edge_df = (
        df.groupby(['source_municipality', 'target_company'], as_index=False)
        .agg(
            total_price=('price', 'sum'),
            contracts=('price', 'count'),
            avg_price=('price', 'mean'),
            price_series=('price', list)
        )
    )

    edge_df['weight'] = edge_df['price_series'].apply(
        lambda x: compute_weight(x, mode=weight_mode)
    )

    G = nx.DiGraph()

    for row in edge_df.itertuples(index=False):
        G.add_edge(
            row.source_municipality,
            row.target_company,
            weight=row.weight,
            total_price=row.total_price,
            contracts=row.contracts,
            avg_price=row.avg_price
        )

    return G


# =========================================================
# 6. VISUAL ATTRIBUTES (OPTIONAL)
# =========================================================
def add_visual_attributes(
    G,
    thickness_mode="linear",
    size_mode="linear",
    scale_min=1,
    scale_max=5,
    suffix=""
):

    conc = np.array([d.get('nr_concorrentes', 0) for _, _, d in G.edges(data=True)])
    weight = np.array([d['weight'] for _, _, d in G.edges(data=True)])

    def normalize(x):
        if len(x) == 0:
            return x

        r = np.ptp(x)
        if r == 0:
            return np.zeros_like(x)

        return (x - np.min(x)) / (r + 1e-9)

    if thickness_mode == "log":
        conc = np.log1p(conc)

    if size_mode == "log":
        weight = np.log1p(weight)

    conc_norm = normalize(conc)
    weight_norm = normalize(weight)

    def scale(x):
        return scale_min + (scale_max - scale_min) * x

    for i, (_, _, d) in enumerate(G.edges(data=True)):
        d[f'edge_thickness{suffix}'] = scale(conc_norm[i])
        d[f'edge_size{suffix}'] = scale(weight_norm[i])

    return G


# =========================================================
# 7. PIPELINE USAGE
# =========================================================

df = data  # raw input (dict/list/DataFrame supported)

# MUNICIPALITY NETWORK
G_municipality = build_municipality_network(df)
G_municipality = add_visual_attributes(G_municipality)

ValueError: Cannot find source column. Columns: ['weight', 'total_price', 'nr_concorrentes', 'contracts', 'weight_mode', 'idcontrato', 'tipoContrato', 'tipoFimContrato', 'CPV', 'precoBaseProcedimento', 'precoContratual', 'PrecoTotalEfetivo', 'dataDecisaoAdjudicacao', 'dataCelebracaoContrato', 'dataPublicacao', 'dataFechoContrato', 'nr_concorrentes_list', 'contribuinte_adjudicante', 'contribuinte_adjudicatarios', 'city', 'cpv_prefix', 'agg_cpv']

In [40]:
df = _ensure_dataframe(data)
print(df.columns)

Index(['weight', 'total_price', 'nr_concorrentes', 'contracts', 'weight_mode',
       'idcontrato', 'tipoContrato', 'tipoFimContrato', 'CPV',
       'precoBaseProcedimento', 'precoContratual', 'PrecoTotalEfetivo',
       'dataDecisaoAdjudicacao', 'dataCelebracaoContrato', 'dataPublicacao',
       'dataFechoContrato', 'nr_concorrentes_list', 'contribuinte_adjudicante',
       'contribuinte_adjudicatarios', 'city', 'cpv_prefix', 'agg_cpv'],
      dtype='str')

## <font size=5>**3.6 Exporting It**</font> <a class="anchor" id="3.6"></a>
  
[Back to TOC](#toc)

In [31]:
output_path = '../graphs/gephi_graph01.gexf'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
nx.write_gexf(G, output_path)
print(f'Graph exported to {output_path}')

TypeError: cannot unpack non-iterable int object