<font size=10>**EXPLORATION**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

**Project**: [*Portal BASE*](https://www.base.gov.pt/Base4/pt/pesquisa/?type=contratos&texto=&adjudicante=&adjudicataria=&tipo=2&tipocontrato=0&cpv=&aqinfo=&desdeprazoexecucao=&ateprazoexecucao=&sel_price=price_11&desdeprecocontrato=&ateprecocontrato=&desdeprecoefectivo=&ateprecoefectivo=&sel_date=date_11&desdedatacontrato=2023-01-01&atedatacontrato=2026-03-31&desdedatapublicacao=&atedatapublicacao=&desdedatafecho=&atedatafecho=&pais=0&distrito=0&concelho=0)

**Filters Applied**: 
- Procurement Procedure Type: Public
- Contract Start Date: 2023-01-01   
- Contract End Date: 2026-03-31  

**Group B**
- Beatriz Marques 20231605
- Maria Inês Santos 20231630
- Luís Soeiro 20211536
- Rodrigo Silva 20231602

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a>  
- [1. Imports](#1)  
- [2. Data Integration](#2)  
- [3. Data Exploration](#3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from my_utils import *
from visualizations import *

# <font color='#BFD72F' size=6>**2. Data Integration**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [4]:
df = load_dataset("../data/data.csv")
df.head()

,﻿Objeto do Contrato,Tipo de Procedimento,Tipo(s) de Contrato,CPV,CPV Tipo,CPV Designação,CPV Valor,Entidade(s) Adjudicante(s),Entidade(s) Adjudicatária(s),Preço Contratual,...,Descrição do Acordo Quadro,Procedimento Centralizado,Ligação para Peças do Procedimento,Lista de Fornecedores (cocontratantes),Aquisição ao Abrigo de Acordo Quadro de outro Estado-membro da UE,Medidas especiais,Regime,Critérios Materiais,CCP,groupMembers
0,"Remodelação da praia das Palmeiras, manutenção...",Concurso público,Empreitadas de obras públicas,45259000-7,Principal,Reparação e manutenção de instalações,138440.2 €,Município de Santa Cruz (511244681),SCTM - Sociedade Construções Técnicas da Madei...,"138.440,20 €",...,Não aplicável.,False,https://www.acingov.pt/acingovprod/2/zonaPubli...,False,NaN,NaN,Código dos Contratos Públicos (DL 111-B/2017) ...,False,False,NaN
1,Empreitada de Reabilitação de Fogos Devolutos ...,Concurso público,Empreitadas de obras públicas,45453100-8,Principal,Obras de recuperação,275000.0 €,"IHM - Investimentos Habitacionais da Madeira, ...","Sales, Faria & Andrade- Sociedade de Construçõ...","275.000,00 €",...,Não aplicável.,False,https://www.acingov.pt/acingovprod/2/zonaPubli...,False,NaN,NaN,Código dos Contratos Públicos (DL 111-B/2017) ...,False,False,NaN
2,Concurso Público com publicidade no Jornal Ofi...,Concurso público,Aquisição de bens móveis,48200000-0,Principal,"Pacote de software para ligações em rede, Inte...",338257.16 €,Instituto para os Comportamentos Aditivos e as...,"Claranet II Solutions, SA (510728189)","338.257,16 €",...,Não aplicável.,True,https://community.vortal.biz/Public/public-ten...,False,NaN,NaN,Código dos Contratos Públicos (DL111-B/2017) e...,False,False,NaN
3,Serviços análise de dados para manutenção evol...,Concurso público,Aquisição de serviços,72500000-0,Principal,Serviços relacionados com a informática,283966.4 €,"Serviços Partilhados do Ministério da Saúde, E...","Integer Consulting, S.A. (507969332)","283.966,40 €",...,Não aplicável.,False,https://community.vortal.biz/Public/public-ten...,False,NaN,NaN,Código dos Contratos Públicos (DL111-B/2017) e...,False,False,NaN
4,"Serviços de técnico de suporte IT, para o supo...",Concurso público,Aquisição de serviços,72500000-0,Principal,Serviços relacionados com a informática,489828.77 €,"Serviços Partilhados do Ministério da Saúde, E...","IDW - CONSULTORIA EM SERVIÇOS DE INFORMAÇÃO, L...","489.828,77 €",...,Não aplicável.,False,https://community.vortal.biz/Public/public-ten...,False,NaN,NaN,Código dos Contratos Públicos (DL111-B/2017) e...,False,False,NaN

# <font color='#BFD72F' size=6>**3. Data Exploration**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 32 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   ﻿Objeto do Contrato                                                250 non-null    str
 1   Tipo de Procedimento                                               250 non-null    str
 2   Tipo(s) de Contrato                                                250 non-null    str
 3   CPV                                                                250 non-null    str
 4   CPV Tipo                                                           250 non-null    str
 5   CPV Designação                                                     250 non-null    str
 6   CPV Valor                                                          250 non-null    str
 7   Entidade(s) Adjudicante(s)                                         250 non-null    str
 8   Entidade(s) Adjudicatária(s)                                       250 non-null    str
 9   Preço Contratual                                                   250 non-null    str
 10  Data de Publicação                                                 250 non-null    str
 11  Data de Celebração do Contrato                                     250 non-null    str
 12  Prazo de Execução                                                  250 non-null    str
 13  Local de Execução                                                  250 non-null    str
 14  Fundamentação                                                      250 non-null    str
 15  Causa de Extinção do Contrato                                      0 non-null      float64
 16  Data de Fecho do Contrato                                          0 non-null      float64
 17  Preço Total Efetivo                                                0 non-null      float64
 18  Causas das Alterações ao Prazo                                     0 non-null      float64
 19  Causas das Alterações ao Preço                                     0 non-null      float64
 20  Estado                                                             0 non-null      float64
 21  N.º registo do Acordo Quadro                                       250 non-null    str
 22  Descrição do Acordo Quadro                                         250 non-null    str
 23  Procedimento Centralizado                                          250 non-null    bool
 24  Ligação para Peças do Procedimento                                 249 non-null    str
 25  Lista de Fornecedores (cocontratantes)                             250 non-null    bool
 26  Aquisição ao Abrigo de Acordo Quadro de outro Estado-membro da UE  0 non-null      float64
 27  Medidas especiais                                                  0 non-null      float64
 28  Regime                                                             250 non-null    str
 29  Critérios Materiais                                                250 non-null    bool
 30  CCP                                                                250 non-null    bool
 31  groupMembers                                                       0 non-null      float64
dtypes: bool(4), float64(9), str(19)
memory usage: 55.8 KB

In [6]:
print("There are {} Public Entities.".format(df['Entidade(s) Adjudicante(s)'].nunique()))
print("There are {} Companies.".format(df['Entidade(s) Adjudicatária(s)'].nunique()))

print("So, in total our analysis contains {} Nodes.".format(
    df['Entidade(s) Adjudicatária(s)'].nunique() + 
    df['Entidade(s) Adjudicante(s)'].nunique()))

There are 131 Public Entities.
There are 209 Companies.
So, in total our analysis contains 340 Nodes.

In [7]:
print("{} Contracts, characterised by {} columns.".format(df.shape[0], df.shape[1]))

250 Contracts, characterised by 32 columns.

In [13]:
for col in df.columns:
    print("\n" + "="*60)
    print(f"Column: {col}")
    print("="*60)
    
    display(
        df[col]
        .value_counts(dropna=False)
        .reset_index()
        .rename(columns={"index": col, col: "count"})
    )

============================================================
Column: ﻿Objeto do Contrato
============================================================

                                                 count  count
0                       Aquisição de Material para UCI     19
1    Aquisição de Medicamentos do Sistema Nervoso C...     13
2    Aquisição de serviços de Encarregado de Proteç...      7
3    CP 08-2026 Aquisição de reagentes para a Área ...      6
4    Concurso Público com publicação no JOUE para a...      5
..                                                 ...    ...
163  Fornecimento continuo de contadores de água li...      1
164  BM_01.2026 -Aquisição de Veículos Operacionais...      1
165  Aluguer e instalação de equipamentos para a Fe...      1
166  4025026849/DA/P0017A/2025-Aquisição de Colchõe...      1
167                   Aquisição de equipamento de rede      1

[168 rows x 2 columns]

============================================================
Column: Tipo de Procedimento
============================================================

              count  count
0  Concurso público    250

============================================================
Column: Tipo(s) de Contrato
============================================================

                                               count  count
0                           Aquisição de bens móveis    139
1                              Aquisição de serviços     69
2                      Empreitadas de obras públicas     31
3                             Locação de bens móveis     10
4  Aquisição de bens móveis<br/>Aquisição de serv...      1

============================================================
Column: CPV
============================================================

          count  count
0    33140000-3     40
1    33661000-1     13
2    33696500-0      9
3    79000000-4      7
4    72500000-0      6
..          ...    ...
128  38421100-3      1
129  34144210-3      1
130  79952000-2      1
131  39143112-4      1
132  32400000-7      1

[133 rows x 2 columns]

============================================================
Column: CPV Tipo
============================================================

                     count  count
0                Principal    248
1  Principal | Suplementar      2

============================================================
Column: CPV Designação
============================================================

                                                 count  count
0                           Material médico de consumo     40
1                  Medicamentos para o sistema nervoso     13
2                             Reagentes de laboratório      9
3    Serviços a empresas: direito, comercialização,...      7
4              Serviços relacionados com a informática      6
..                                                 ...    ...
128                                 Contadores de água      1
129                    Veículos de combate a incêndios      1
130                                Serviços de eventos      1
131                                           Colchões      1
132                                              Redes      1

[133 rows x 2 columns]

============================================================
Column: CPV Valor
============================================================

           count  count
0    Inexistente      6
1     66000.0 €       2
2      7040.0 €       2
3    138440.2 €       1
4    275000.0 €       1
..           ...    ...
238   14488.0 €       1
239   83380.0 €       1
240   37914.0 €       1
241  140000.0 €       1
242  70233.94 €       1

[243 rows x 2 columns]

============================================================
Column: Entidade(s) Adjudicante(s)
============================================================

                                                 count  count
0     Santa Casa da Misericórdia de Lisboa (500745471)     21
1    Unidade Local de Saúde do Algarve, EPE (510745...     20
2    Unidade Local de Saúde de Lisboa Ocidental, EP...      9
3    Serviços Partilhados do Ministério da Saúde, E...      7
4    Unidade Local de Saúde de Entre o Douro e Voug...      7
..                                                 ...    ...
126  Agência de Inovação e Modernização da Região A...      1
127  Vimágua - Empresa de Água e Saneamento de Guim...      1
128        Município de Fornos de Algodres (505592959)      1
129  Gabinete do Chefe do Estado-Maior do Exército ...      1
130        Instituto Politécnico de Lisboa (508519713)      1

[131 rows x 2 columns]

============================================================
Column: Entidade(s) Adjudicatária(s)
============================================================

                                                 count  count
0    PricewterhouseCoopers Legal - SOCIEDADE DE ADV...      6
1                    JOHNSON & JOHNSON LDA (500153370)      6
2                               Efima, Lda (513097759)      4
3    MEDTRONIC PORTUGAL, UNIPESSOAL,  LDA. (504223933)      3
4                        Monte &amp; Monte (504008404)      3
..                                                 ...    ...
204  JANZ - Contagem e Gestão de Fluidos, SA (50523...      1
205                  Espaço Mecânico, S.A. (502930462)      1
206                        VTE EVENTOS LDA (510782582)      1
207               J. J. LOURO PEREIRA S.A. (501135227)      1
208                         Officelan, Lda (507236912)      1

[209 rows x 2 columns]

============================================================
Column: Preço Contratual
============================================================

            count  count
0          0,00 €      6
1     66.000,00 €      2
2      7.040,00 €      2
3    138.440,20 €      1
4    275.000,00 €      1
..            ...    ...
238   14.488,00 €      1
239   83.380,00 €      1
240   37.914,00 €      1
241  140.000,00 €      1
242   70.233,94 €      1

[243 rows x 2 columns]

============================================================
Column: Data de Publicação
============================================================

        count  count
0  01-04-2026    128
1  02-04-2026     83
2  06-04-2026     29
3  31-03-2026      5
4  03-04-2026      3
5  04-04-2026      2

============================================================
Column: Data de Celebração do Contrato
============================================================

         count  count
0   31-03-2026     61
1   30-03-2026     44
2   19-03-2026     21
3   25-03-2026     13
4   04-03-2026     12
5   23-03-2026     10
6   17-03-2026      9
7   26-03-2026      9
8   27-03-2026      8
9   24-03-2026      8
10  12-03-2026      5
11  10-02-2026      5
12  20-03-2026      4
13  18-03-2026      4
14  02-03-2026      2
15  16-03-2026      2
16  11-03-2026      2
17  01-01-2026      2
18  05-03-2026      2
19  11-12-2025      1
20  03-10-2025      1
21  24-02-2026      1
22  24-01-2025      1
23  12-02-2026      1
24  09-01-2026      1
25  26-01-2026      1
26  12-11-2025      1
27  06-03-2026      1
28  27-02-2026      1
29  24-07-2025      1
30  03-03-2026      1
31  25-02-2026      1
32  06-12-2024      1
33  26-02-2026      1
34  13-03-2026      1
35  14-10-2025      1
36  03-02-2026      1
37  18-12-2025      1
38  18-02-2026      1
39  27-01-2026      1
40  19-02-2026      1
41  09-03-2026      1
42  13-08-2025      1
43  20-01-2026      1
44  01-03-2026      1
45  19-12-2025      1

============================================================
Column: Prazo de Execução
============================================================

        count  count
0    365 dias     64
1    731 dias     26
2   1096 dias     22
3     60 dias     10
4     90 dias      7
..        ...    ...
59  2830 dias      1
60   345 dias      1
61  3287 dias      1
62     7 dias      1
63    40 dias      1

[64 rows x 2 columns]

============================================================
Column: Local de Execução
============================================================

                                                count  count
0                            Portugal, Lisboa, Lisboa     58
1                                            Portugal     40
2                              Portugal, Porto, Porto     20
3   Portugal, Faro, Portimão<BR/>Portugal, Faro, Faro     12
4   Portugal, Faro, Faro<BR/>Portugal, Faro, Portimão      8
..                                                ...    ...
60                          Portugal, Braga, Barcelos      1
61       Portugal, Lisboa, Lisboa<BR/>Portugal, Porto      1
62  Portugal, Região Autónoma da Madeira, Funchal<...      1
63                              Portugal, Beja, Serpa      1
64               Portugal, Guarda, Fornos de Algodres      1

[65 rows x 2 columns]

============================================================
Column: Fundamentação
============================================================

                                                count  count
0   Artigo 20.º, n.º 1, alínea b) do Código dos Co...    113
1   Artigo 20.º, n.º 1, alínea a) do Código dos Co...     92
2   Artigo 19.º, alínea b) do Código dos Contratos...     23
3   Artigo 19.º, alínea a) do Código dos Contratos...      6
4   Artigo 252.º, n.º 1, alínea b) do Código dos C...      5
5       Artigo 155.º do Código dos Contratos Públicos      5
6   Artigo 155.º, alínea b) do Código dos Contrato...      2
7         Artigo 11º do Código dos Contratos Públicos      1
8   Artigo 33.º, n.º 1 do Código dos Contratos Púb...      1
9   Artigo 20.º, alínea b) do Decreto Legislativo ...      1
10  Artigo 155.º, alínea a) do Código dos Contrato...      1

============================================================
Column: Causa de Extinção do Contrato
============================================================

   count  count
0    NaN    250

============================================================
Column: Data de Fecho do Contrato
============================================================

   count  count
0    NaN    250

============================================================
Column: Preço Total Efetivo
============================================================

   count  count
0    NaN    250

============================================================
Column: Causas das Alterações ao Prazo
============================================================

   count  count
0    NaN    250

============================================================
Column: Causas das Alterações ao Preço
============================================================

   count  count
0    NaN    250

============================================================
Column: Estado
============================================================

   count  count
0    NaN    250

============================================================
Column: N.º registo do Acordo Quadro
============================================================

            count  count
0  Não aplicável.    245
1         7857310      5

============================================================
Column: Descrição do Acordo Quadro
============================================================

                                               count  count
0                                     Não aplicável.    245
1  Concurso Público com publicação no JOUE para a...      5

============================================================
Column: Procedimento Centralizado
============================================================

   count  count
0  False    238
1   True     12

============================================================
Column: Ligação para Peças do Procedimento
============================================================

                                                 count  count
0    https://community.vortal.biz/Public/public-ten...     19
1    https://www.acingov.pt/acingovprod/2/zonaPubli...     13
2    https://www.acingov.pt/acingovprod/2/zonaPubli...      7
3    https://www.acingov.pt/acingovprod/2/zonaPubli...      6
4    https://www.acingov.pt/acingovprod/2/zonaPubli...      5
..                                                 ...    ...
162  https://www.acingov.pt/acingovprod/2/zonaPubli...      1
163  https://community.vortal.biz/Public/public-ten...      1
164  https://www.acingov.pt/acingovprod/2/zonaPubli...      1
165  https://www.acingov.pt/acingovprod/2/zonaPubli...      1
166  https://www.acingov.pt/acingovprod/2/zonaPubli...      1

[167 rows x 2 columns]

============================================================
Column: Lista de Fornecedores (cocontratantes)
============================================================

   count  count
0  False    250

============================================================
Column: Aquisição ao Abrigo de Acordo Quadro de outro Estado-membro da UE
============================================================

   count  count
0    NaN    250

============================================================
Column: Medidas especiais
============================================================

   count  count
0    NaN    250

============================================================
Column: Regime
============================================================

                                               count  count
0  Código dos Contratos Públicos (DL111-B/2017) e...    238
1    Código dos Contratos Públicos ( DL 111-B/2017 )      6
2  Código dos Contratos Públicos (DL 111-B/2017) ...      5
3                        DLR n.º 27/2015/A, de 29.12      1

============================================================
Column: Critérios Materiais
============================================================

   count  count
0  False    250

============================================================
Column: CCP
============================================================

   count  count
0  False    250

============================================================
Column: groupMembers
============================================================

   count  count
0    NaN    250

In [14]:
cols_to_keep = ["Entidade(s) Adjudicante(s)",
                "Entidade(s) Adjudicatária(s)",
                "groupMembers",
                "Data de Celebração do Contrato",
                "Local de Execução",
                "CPV Designação",
                "Preço Total Efetivo"]

In [17]:
df_subset = df[cols_to_keep]
df_subset.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entidade(s) Adjudicante(s)      250 non-null    str
 1   Entidade(s) Adjudicatária(s)    250 non-null    str
 2   groupMembers                    0 non-null      float64
 3   Data de Celebração do Contrato  250 non-null    str
 4   Local de Execução               250 non-null    str
 5   CPV Designação                  250 non-null    str
 6   Preço Total Efetivo             0 non-null      float64
dtypes: float64(2), str(5)
memory usage: 13.8 KB

In [18]:
for col in df_subset.columns:
    print("\n" + "="*60)
    print(f"Column: {col}")
    print("="*60)
    
    display(
        df[col]
        .value_counts(dropna=False)
        .reset_index()
        .rename(columns={"index": col, col: "count"})
    )

============================================================
Column: Entidade(s) Adjudicante(s)
============================================================

                                                 count  count
0     Santa Casa da Misericórdia de Lisboa (500745471)     21
1    Unidade Local de Saúde do Algarve, EPE (510745...     20
2    Unidade Local de Saúde de Lisboa Ocidental, EP...      9
3    Serviços Partilhados do Ministério da Saúde, E...      7
4    Unidade Local de Saúde de Entre o Douro e Voug...      7
..                                                 ...    ...
126  Agência de Inovação e Modernização da Região A...      1
127  Vimágua - Empresa de Água e Saneamento de Guim...      1
128        Município de Fornos de Algodres (505592959)      1
129  Gabinete do Chefe do Estado-Maior do Exército ...      1
130        Instituto Politécnico de Lisboa (508519713)      1

[131 rows x 2 columns]

============================================================
Column: Entidade(s) Adjudicatária(s)
============================================================

                                                 count  count
0    PricewterhouseCoopers Legal - SOCIEDADE DE ADV...      6
1                    JOHNSON & JOHNSON LDA (500153370)      6
2                               Efima, Lda (513097759)      4
3    MEDTRONIC PORTUGAL, UNIPESSOAL,  LDA. (504223933)      3
4                        Monte &amp; Monte (504008404)      3
..                                                 ...    ...
204  JANZ - Contagem e Gestão de Fluidos, SA (50523...      1
205                  Espaço Mecânico, S.A. (502930462)      1
206                        VTE EVENTOS LDA (510782582)      1
207               J. J. LOURO PEREIRA S.A. (501135227)      1
208                         Officelan, Lda (507236912)      1

[209 rows x 2 columns]

============================================================
Column: groupMembers
============================================================

   count  count
0    NaN    250

============================================================
Column: Data de Celebração do Contrato
============================================================

         count  count
0   31-03-2026     61
1   30-03-2026     44
2   19-03-2026     21
3   25-03-2026     13
4   04-03-2026     12
5   23-03-2026     10
6   17-03-2026      9
7   26-03-2026      9
8   27-03-2026      8
9   24-03-2026      8
10  12-03-2026      5
11  10-02-2026      5
12  20-03-2026      4
13  18-03-2026      4
14  02-03-2026      2
15  16-03-2026      2
16  11-03-2026      2
17  01-01-2026      2
18  05-03-2026      2
19  11-12-2025      1
20  03-10-2025      1
21  24-02-2026      1
22  24-01-2025      1
23  12-02-2026      1
24  09-01-2026      1
25  26-01-2026      1
26  12-11-2025      1
27  06-03-2026      1
28  27-02-2026      1
29  24-07-2025      1
30  03-03-2026      1
31  25-02-2026      1
32  06-12-2024      1
33  26-02-2026      1
34  13-03-2026      1
35  14-10-2025      1
36  03-02-2026      1
37  18-12-2025      1
38  18-02-2026      1
39  27-01-2026      1
40  19-02-2026      1
41  09-03-2026      1
42  13-08-2025      1
43  20-01-2026      1
44  01-03-2026      1
45  19-12-2025      1

============================================================
Column: Local de Execução
============================================================

                                                count  count
0                            Portugal, Lisboa, Lisboa     58
1                                            Portugal     40
2                              Portugal, Porto, Porto     20
3   Portugal, Faro, Portimão<BR/>Portugal, Faro, Faro     12
4   Portugal, Faro, Faro<BR/>Portugal, Faro, Portimão      8
..                                                ...    ...
60                          Portugal, Braga, Barcelos      1
61       Portugal, Lisboa, Lisboa<BR/>Portugal, Porto      1
62  Portugal, Região Autónoma da Madeira, Funchal<...      1
63                              Portugal, Beja, Serpa      1
64               Portugal, Guarda, Fornos de Algodres      1

[65 rows x 2 columns]

============================================================
Column: CPV Designação
============================================================

                                                 count  count
0                           Material médico de consumo     40
1                  Medicamentos para o sistema nervoso     13
2                             Reagentes de laboratório      9
3    Serviços a empresas: direito, comercialização,...      7
4              Serviços relacionados com a informática      6
..                                                 ...    ...
128                                 Contadores de água      1
129                    Veículos de combate a incêndios      1
130                                Serviços de eventos      1
131                                           Colchões      1
132                                              Redes      1

[133 rows x 2 columns]

============================================================
Column: Preço Total Efetivo
============================================================

   count  count
0    NaN    250

In [ ]:
# TODO: Data de Celebração do Contrato -> convert to datetime
# df_subset["Data de Celebração do Contrato"] = pd.to_datetime(df_subset["Data de Celebração do Contrato"], errors='coerce')

In [9]:
df_counts = df['Tipo(s) de Contrato'].value_counts().reset_index()
df_counts.columns = ['Tipo(s) de Contrato', 'count']

bar_chart(
    data=df_counts,
    x='Tipo(s) de Contrato',
    y='count',
    title='Number of Contracts by Contract Type',
    labels={'Tipo(s) de Contrato': 'Contract Type', 'count': 'Number of Contracts'},
    top_n=20
)